package com.gistandard.transport.system.webservice.client.payinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-27T10:04:15.327+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "QueryCalcManagerWebServiceImplService", 
                  wsdlLocation = "http://172.17.1.12:8080/WebService/QueryCalcManagerWebService?wsdl",
                  targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/") 
public class QueryCalcManagerWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "QueryCalcManagerWebServiceImplService");
    public final static QName QueryCalcManagerWebServiceImplPort = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "QueryCalcManagerWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.1.12:8080/WebService/QueryCalcManagerWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryCalcManagerWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.17.1.12:8080/WebService/QueryCalcManagerWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryCalcManagerWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryCalcManagerWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryCalcManagerWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QueryCalcManagerWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryCalcManagerWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryCalcManagerWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QueryCalcManagerWebService
     */
    @WebEndpoint(name = "QueryCalcManagerWebServiceImplPort")
    public QueryCalcManagerWebService getQueryCalcManagerWebServiceImplPort() {
        return super.getPort(QueryCalcManagerWebServiceImplPort, QueryCalcManagerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryCalcManagerWebService
     */
    @WebEndpoint(name = "QueryCalcManagerWebServiceImplPort")
    public QueryCalcManagerWebService getQueryCalcManagerWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(QueryCalcManagerWebServiceImplPort, QueryCalcManagerWebService.class, features);
    }

}
