package com.gistandard.transport.system.webservice.client.payinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-27T10:04:15.321+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", name = "QueryCalcManagerWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryCalcManagerWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "QueryExpressTransportPayMoney", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.payinfo.QueryExpressTransportPayMoney")
    @WebMethod(operationName = "QueryExpressTransportPayMoney")
    @ResponseWrapper(localName = "QueryExpressTransportPayMoneyResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.payinfo.QueryExpressTransportPayMoneyResponse")
    public ValidBillMst queryExpressTransportPayMoney(
            @WebParam(name = "busiBookNo", targetNamespace = "")
            String busiBookNo,
            @WebParam(name = "dispatchId", targetNamespace = "")
            String dispatchId,
            @WebParam(name = "validCode", targetNamespace = "")
            String validCode,
            @WebParam(name = "gFUserFromCode", targetNamespace = "")
            String gFUserFromCode,
            @WebParam(name = "gFUserToCode", targetNamespace = "")
            String gFUserToCode
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetQuote", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.payinfo.GetQuote")
    @WebMethod(operationName = "GetQuote")
    @ResponseWrapper(localName = "GetQuoteResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.payinfo.GetQuoteResponse")
    public PlatFormOutModel getQuote(
            @WebParam(name = "arg0", targetNamespace = "")
            PlatFormInModel arg0
    ) throws Exception_Exception;
}
