
package com.gistandard.transport.system.webservice.client.payinfo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-27T10:04:15.283+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class QueryCalcManagerWebService_QueryCalcManagerWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "QueryCalcManagerWebServiceImplService");

    private QueryCalcManagerWebService_QueryCalcManagerWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QueryCalcManagerWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryCalcManagerWebServiceImplService ss = new QueryCalcManagerWebServiceImplService(wsdlURL, SERVICE_NAME);
        QueryCalcManagerWebService port = ss.getQueryCalcManagerWebServiceImplPort();  
        
        {
        System.out.println("Invoking queryExpressTransportPayMoney...");
        String _queryExpressTransportPayMoney_busiBookNo = "";
        String _queryExpressTransportPayMoney_dispatchId = "";
        String _queryExpressTransportPayMoney_validCode = "";
        String _queryExpressTransportPayMoney_gFUserFromCode = "";
        String _queryExpressTransportPayMoney_gFUserToCode = "";
        try {
            ValidBillMst _queryExpressTransportPayMoney__return = port.queryExpressTransportPayMoney(_queryExpressTransportPayMoney_busiBookNo, _queryExpressTransportPayMoney_dispatchId, _queryExpressTransportPayMoney_validCode, _queryExpressTransportPayMoney_gFUserFromCode, _queryExpressTransportPayMoney_gFUserToCode);
            System.out.println("queryExpressTransportPayMoney.result=" + _queryExpressTransportPayMoney__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getQuote...");
        PlatFormInModel _getQuote_arg0 = null;
        try {
            PlatFormOutModel _getQuote__return = port.getQuote(_getQuote_arg0);
            System.out.println("getQuote.result=" + _getQuote__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
