package com.gistandard.transport.system.webservice.client.calcWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-09-11T15:30:59.022+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "CalcWebServiceImplService", 
                  wsdlLocation = "http://172.17.1.12:8080/WebService/CalcWebService?wsdl",
                  targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/") 
public class CalcWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "CalcWebServiceImplService");
    public final static QName CalcWebServiceImplPort = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "CalcWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.1.12:8080/WebService/CalcWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalcWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.17.1.12:8080/WebService/CalcWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalcWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalcWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CalcWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalcWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalcWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CalcWebService
     */
    @WebEndpoint(name = "CalcWebServiceImplPort")
    public CalcWebService getCalcWebServiceImplPort() {
        return super.getPort(CalcWebServiceImplPort, CalcWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcWebService
     */
    @WebEndpoint(name = "CalcWebServiceImplPort")
    public CalcWebService getCalcWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CalcWebServiceImplPort, CalcWebService.class, features);
    }

}
