package com.gistandard.transport.system.webservice.client.calcWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-09-11T15:30:59.009+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", name = "CalcWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalcWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CheckParametersForOSettlementBatch", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CheckParametersForOSettlementBatch")
    @WebMethod(operationName = "CheckParametersForOSettlementBatch")
    @ResponseWrapper(localName = "CheckParametersForOSettlementBatchResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CheckParametersForOSettlementBatchResponse")
    public String checkParametersForOSettlementBatch(
            @WebParam(name = "arg0", targetNamespace = "")
            java.util.List<CheckOCalcForPrice> arg0
    );

    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "QueryPlatformQuoteIBatch", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPlatformQuoteIBatch")
    @WebMethod(operationName = "QueryPlatformQuoteIBatch")
    @ResponseWrapper(localName = "QueryPlatformQuoteIBatchResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPlatformQuoteIBatchResponse")
    public QueryPlatformQuoteIBatchResponse.Return queryPlatformQuoteIBatch(
            @WebParam(name = "platformQuoteIs", targetNamespace = "")
            java.util.List<PlatformQuoteI> platformQuoteIs
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelCalcForPriceO", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CancelCalcForPriceO")
    @WebMethod
    @ResponseWrapper(localName = "cancelCalcForPriceOResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CancelCalcForPriceOResponse")
    public String cancelCalcForPriceO(
            @WebParam(name = "orderNo", targetNamespace = "")
            String orderNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bidding", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.Bidding")
    @WebMethod
    @ResponseWrapper(localName = "biddingResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.BiddingResponse")
    public String bidding(
            @WebParam(name = "calcForBidding", targetNamespace = "")
            CalcForBidding calcForBidding
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CalcOperationPostToInvoice", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcOperationPostToInvoice")
    @WebMethod(operationName = "CalcOperationPostToInvoice")
    @ResponseWrapper(localName = "CalcOperationPostToInvoiceResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcOperationPostToInvoiceResponse")
    public DataResult calcOperationPostToInvoice(
            @WebParam(name = "orderId", targetNamespace = "")
            Integer orderId,
            @WebParam(name = "docNo", targetNamespace = "")
            String docNo,
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode,
            @WebParam(name = "taxCode", targetNamespace = "")
            String taxCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryBillStatus", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryBillStatus")
    @WebMethod
    @ResponseWrapper(localName = "queryBillStatusResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryBillStatusResponse")
    public BidingInfoResultBean queryBillStatus(
            @WebParam(name = "docNo", targetNamespace = "")
            String docNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "thirdPartyPay", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.ThirdPartyPay")
    @WebMethod
    @ResponseWrapper(localName = "thirdPartyPayResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.ThirdPartyPayResponse")
    public String thirdPartyPay(
            @WebParam(name = "docNo", targetNamespace = "")
            String docNo,
            @WebParam(name = "gFUser3FToCode", targetNamespace = "")
            String gFUser3FToCode,
            @WebParam(name = "gFUser3FToName", targetNamespace = "")
            String gFUser3FToName,
            @WebParam(name = "type", targetNamespace = "")
            Integer type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "QueryPlatformQuote2", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPlatformQuote2")
    @WebMethod(operationName = "QueryPlatformQuote2")
    @ResponseWrapper(localName = "QueryPlatformQuote2Response", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPlatformQuote2Response")
    public PlatformQuote queryPlatformQuote2(
            @WebParam(name = "systemFlag", targetNamespace = "")
            String systemFlag,
            @WebParam(name = "OrderNo", targetNamespace = "")
            String orderNo,
            @WebParam(name = "StartAccountId", targetNamespace = "")
            String startAccountId,
            @WebParam(name = "EndAccountId", targetNamespace = "")
            String endAccountId,
            @WebParam(name = "OrderCatalog", targetNamespace = "")
            int orderCatalog
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CheckParametersForODataSettlementBatch", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CheckParametersForODataSettlementBatch")
    @WebMethod(operationName = "CheckParametersForODataSettlementBatch")
    @ResponseWrapper(localName = "CheckParametersForODataSettlementBatchResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CheckParametersForODataSettlementBatchResponse")
    public String checkParametersForODataSettlementBatch(
            @WebParam(name = "oCalcForPrices", targetNamespace = "")
            java.util.List<CheckOCalcForPrice> oCalcForPrices
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CheckParametersForCalcForPrice", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CheckParametersForCalcForPrice")
    @WebMethod(operationName = "CheckParametersForCalcForPrice")
    @ResponseWrapper(localName = "CheckParametersForCalcForPriceResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CheckParametersForCalcForPriceResponse")
    public String checkParametersForCalcForPrice(
            @WebParam(name = "systemFlag", targetNamespace = "")
            String systemFlag,
            @WebParam(name = "orderCatalog", targetNamespace = "")
            int orderCatalog,
            @WebParam(name = "orderNo", targetNamespace = "")
            String orderNo,
            @WebParam(name = "calcParamaters", targetNamespace = "")
            String calcParamaters,
            @WebParam(name = "gFUserFromCode", targetNamespace = "")
            String gFUserFromCode,
            @WebParam(name = "gFUserToCode", targetNamespace = "")
            String gFUserToCode,
            @WebParam(name = "PaymentTerm", targetNamespace = "")
            String paymentTerm,
            @WebParam(name = "StationCode", targetNamespace = "")
            String stationCode,
            @WebParam(name = "QuotationNo", targetNamespace = "")
            String quotationNo,
            @WebParam(name = "orderId", targetNamespace = "")
            Integer orderId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "QueryPlatformQuote", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPlatformQuote")
    @WebMethod(operationName = "QueryPlatformQuote")
    @ResponseWrapper(localName = "QueryPlatformQuoteResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPlatformQuoteResponse")
    public java.util.List<PlatformQuote> queryPlatformQuote(
            @WebParam(name = "systemFlag", targetNamespace = "")
            String systemFlag,
            @WebParam(name = "ItemCode", targetNamespace = "")
            String itemCode,
            @WebParam(name = "UserScope", targetNamespace = "")
            String userScope
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllValidBillMst", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.FindAllValidBillMst")
    @WebMethod
    @ResponseWrapper(localName = "findAllValidBillMstResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.FindAllValidBillMstResponse")
    public ValidResultBean findAllValidBillMst(
            @WebParam(name = "gFUserCode", targetNamespace = "")
            String gFUserCode,
            @WebParam(name = "pageSize", targetNamespace = "")
            int pageSize,
            @WebParam(name = "pageNum", targetNamespace = "")
            int pageNum
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "purchase", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.Purchase")
    @WebMethod
    @ResponseWrapper(localName = "purchaseResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.PurchaseResponse")
    public String purchase(
            @WebParam(name = "purchaseCoupon", targetNamespace = "")
            PurchaseCoupon purchaseCoupon
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CalcForPrice", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcForPrice")
    @WebMethod(operationName = "CalcForPrice")
    @ResponseWrapper(localName = "CalcForPriceResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcForPriceResponse")
    public String calcForPrice(
            @WebParam(name = "systemFlag", targetNamespace = "")
            String systemFlag,
            @WebParam(name = "orderCatalog", targetNamespace = "")
            int orderCatalog,
            @WebParam(name = "orderNo", targetNamespace = "")
            String orderNo,
            @WebParam(name = "calcParamaters", targetNamespace = "")
            String calcParamaters,
            @WebParam(name = "gFUserFromCode", targetNamespace = "")
            String gFUserFromCode,
            @WebParam(name = "gFUserToCode", targetNamespace = "")
            String gFUserToCode,
            @WebParam(name = "PaymentTerm", targetNamespace = "")
            String paymentTerm,
            @WebParam(name = "StationCode", targetNamespace = "")
            String stationCode,
            @WebParam(name = "QuotationNo", targetNamespace = "")
            String quotationNo,
            @WebParam(name = "orderId", targetNamespace = "")
            Integer orderId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "QueryCalcStatus", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryCalcStatus")
    @WebMethod(operationName = "QueryCalcStatus")
    @ResponseWrapper(localName = "QueryCalcStatusResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryCalcStatusResponse")
    public String queryCalcStatus(
            @WebParam(name = "systemFlag", targetNamespace = "")
            String systemFlag,
            @WebParam(name = "orderNo", targetNamespace = "")
            String orderNo,
            @WebParam(name = "calcUserCode", targetNamespace = "")
            String calcUserCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CalcForPrice2", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcForPrice2")
    @WebMethod(operationName = "CalcForPrice2")
    @ResponseWrapper(localName = "CalcForPrice2Response", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcForPrice2Response")
    public String calcForPrice2(
            @WebParam(name = "systemFlag", targetNamespace = "")
            String systemFlag,
            @WebParam(name = "orderCatalog", targetNamespace = "")
            int orderCatalog,
            @WebParam(name = "orderNo", targetNamespace = "")
            String orderNo,
            @WebParam(name = "gFUserFromCode", targetNamespace = "")
            String gFUserFromCode,
            @WebParam(name = "gFUserToCode", targetNamespace = "")
            String gFUserToCode,
            @WebParam(name = "PaymentTerm", targetNamespace = "")
            String paymentTerm,
            @WebParam(name = "StartAccountId", targetNamespace = "")
            String startAccountId,
            @WebParam(name = "EndAccountId", targetNamespace = "")
            String endAccountId,
            @WebParam(name = "orderId", targetNamespace = "")
            Integer orderId,
            @WebParam(name = "systemFrom", targetNamespace = "")
            Integer systemFrom
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "QueryPayinfo", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPayinfo")
    @WebMethod(operationName = "QueryPayinfo")
    @ResponseWrapper(localName = "QueryPayinfoResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPayinfoResponse")
    public PayInfoResultBean queryPayinfo(
            @WebParam(name = "busiBookNo", targetNamespace = "")
            String busiBookNo,
            @WebParam(name = "validCode", targetNamespace = "")
            String validCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelPurchase", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CancelPurchase")
    @WebMethod
    @ResponseWrapper(localName = "cancelPurchaseResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CancelPurchaseResponse")
    public String cancelPurchase(
            @WebParam(name = "orderNo", targetNamespace = "")
            String orderNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "QueryIarPayinfo", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryIarPayinfo")
    @WebMethod(operationName = "QueryIarPayinfo")
    @ResponseWrapper(localName = "QueryIarPayinfoResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryIarPayinfoResponse")
    public PayInfoResultBean queryIarPayinfo(
            @WebParam(name = "busiBookNo", targetNamespace = "")
            String busiBookNo,
            @WebParam(name = "dispatchId", targetNamespace = "")
            String dispatchId,
            @WebParam(name = "scheducarno", targetNamespace = "")
            String scheducarno,
            @WebParam(name = "GFUserFromCode", targetNamespace = "")
            String gfUserFromCode,
            @WebParam(name = "validCode", targetNamespace = "")
            String validCode,
            @WebParam(name = "GFUserToCode", targetNamespace = "")
            String gfUserToCode,
            @WebParam(name = "ValidBillDocNo", targetNamespace = "")
            String validBillDocNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPurchaseValidBillList", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPurchaseValidBillList")
    @WebMethod
    @ResponseWrapper(localName = "queryPurchaseValidBillListResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.QueryPurchaseValidBillListResponse")
    public String queryPurchaseValidBillList(
            @WebParam(name = "gFUserToCode", targetNamespace = "")
            String gFUserToCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CalcForTempPrice", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcForTempPrice")
    @WebMethod(operationName = "CalcForTempPrice")
    @ResponseWrapper(localName = "CalcForTempPriceResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.CalcForTempPriceResponse")
    public String calcForTempPrice(
            @WebParam(name = "systemFlag", targetNamespace = "")
            String systemFlag,
            @WebParam(name = "allCalcParamaters", targetNamespace = "")
            String allCalcParamaters
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "reward", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.Reward")
    @WebMethod
    @ResponseWrapper(localName = "rewardResponse", targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/", className = "com.gistandard.transport.system.webservice.client.calcWebService.RewardResponse")
    public String reward(
            @WebParam(name = "calcForReward", targetNamespace = "")
            CalcForReward calcForReward
    );
}
