
package com.gistandard.transport.system.webservice.client.calcWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-09-11T15:30:58.944+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class CalcWebService_CalcWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "CalcWebServiceImplService");

    private CalcWebService_CalcWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CalcWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalcWebServiceImplService ss = new CalcWebServiceImplService(wsdlURL, SERVICE_NAME);
        CalcWebService port = ss.getCalcWebServiceImplPort();  
        
        {
        System.out.println("Invoking checkParametersForOSettlementBatch...");
        java.util.List<CheckOCalcForPrice> _checkParametersForOSettlementBatch_arg0 = null;
        String _checkParametersForOSettlementBatch__return = port.checkParametersForOSettlementBatch(_checkParametersForOSettlementBatch_arg0);
        System.out.println("checkParametersForOSettlementBatch.result=" + _checkParametersForOSettlementBatch__return);


        }
        {
        System.out.println("Invoking queryPlatformQuoteIBatch...");
        java.util.List<PlatformQuoteI> _queryPlatformQuoteIBatch_platformQuoteIs = null;
        QueryPlatformQuoteIBatchResponse.Return _queryPlatformQuoteIBatch__return = port.queryPlatformQuoteIBatch(_queryPlatformQuoteIBatch_platformQuoteIs);
        System.out.println("queryPlatformQuoteIBatch.result=" + _queryPlatformQuoteIBatch__return);


        }
        {
        System.out.println("Invoking cancelCalcForPriceO...");
        String _cancelCalcForPriceO_orderNo = "";
        String _cancelCalcForPriceO__return = port.cancelCalcForPriceO(_cancelCalcForPriceO_orderNo);
        System.out.println("cancelCalcForPriceO.result=" + _cancelCalcForPriceO__return);


        }
        {
        System.out.println("Invoking bidding...");
        CalcForBidding _bidding_calcForBidding = null;
        String _bidding__return = port.bidding(_bidding_calcForBidding);
        System.out.println("bidding.result=" + _bidding__return);


        }
        {
        System.out.println("Invoking calcOperationPostToInvoice...");
        Integer _calcOperationPostToInvoice_orderId = null;
        String _calcOperationPostToInvoice_docNo = "";
        String _calcOperationPostToInvoice_userCode = "";
        String _calcOperationPostToInvoice_taxCode = "";
        DataResult _calcOperationPostToInvoice__return = port.calcOperationPostToInvoice(_calcOperationPostToInvoice_orderId, _calcOperationPostToInvoice_docNo, _calcOperationPostToInvoice_userCode, _calcOperationPostToInvoice_taxCode);
        System.out.println("calcOperationPostToInvoice.result=" + _calcOperationPostToInvoice__return);


        }
        {
        System.out.println("Invoking queryBillStatus...");
        String _queryBillStatus_docNo = "";
        BidingInfoResultBean _queryBillStatus__return = port.queryBillStatus(_queryBillStatus_docNo);
        System.out.println("queryBillStatus.result=" + _queryBillStatus__return);


        }
        {
        System.out.println("Invoking thirdPartyPay...");
        String _thirdPartyPay_docNo = "";
        String _thirdPartyPay_gFUser3FToCode = "";
        String _thirdPartyPay_gFUser3FToName = "";
        Integer _thirdPartyPay_type = null;
        String _thirdPartyPay__return = port.thirdPartyPay(_thirdPartyPay_docNo, _thirdPartyPay_gFUser3FToCode, _thirdPartyPay_gFUser3FToName, _thirdPartyPay_type);
        System.out.println("thirdPartyPay.result=" + _thirdPartyPay__return);


        }
        {
        System.out.println("Invoking queryPlatformQuote2...");
        String _queryPlatformQuote2_systemFlag = "";
        String _queryPlatformQuote2_orderNo = "";
        String _queryPlatformQuote2_startAccountId = "";
        String _queryPlatformQuote2_endAccountId = "";
        int _queryPlatformQuote2_orderCatalog = 0;
        PlatformQuote _queryPlatformQuote2__return = port.queryPlatformQuote2(_queryPlatformQuote2_systemFlag, _queryPlatformQuote2_orderNo, _queryPlatformQuote2_startAccountId, _queryPlatformQuote2_endAccountId, _queryPlatformQuote2_orderCatalog);
        System.out.println("queryPlatformQuote2.result=" + _queryPlatformQuote2__return);


        }
        {
        System.out.println("Invoking checkParametersForODataSettlementBatch...");
        java.util.List<CheckOCalcForPrice> _checkParametersForODataSettlementBatch_oCalcForPrices = null;
        String _checkParametersForODataSettlementBatch__return = port.checkParametersForODataSettlementBatch(_checkParametersForODataSettlementBatch_oCalcForPrices);
        System.out.println("checkParametersForODataSettlementBatch.result=" + _checkParametersForODataSettlementBatch__return);


        }
        {
        System.out.println("Invoking checkParametersForCalcForPrice...");
        String _checkParametersForCalcForPrice_systemFlag = "";
        int _checkParametersForCalcForPrice_orderCatalog = 0;
        String _checkParametersForCalcForPrice_orderNo = "";
        String _checkParametersForCalcForPrice_calcParamaters = "";
        String _checkParametersForCalcForPrice_gFUserFromCode = "";
        String _checkParametersForCalcForPrice_gFUserToCode = "";
        String _checkParametersForCalcForPrice_paymentTerm = "";
        String _checkParametersForCalcForPrice_stationCode = "";
        String _checkParametersForCalcForPrice_quotationNo = "";
        Integer _checkParametersForCalcForPrice_orderId = null;
        String _checkParametersForCalcForPrice__return = port.checkParametersForCalcForPrice(_checkParametersForCalcForPrice_systemFlag, _checkParametersForCalcForPrice_orderCatalog, _checkParametersForCalcForPrice_orderNo, _checkParametersForCalcForPrice_calcParamaters, _checkParametersForCalcForPrice_gFUserFromCode, _checkParametersForCalcForPrice_gFUserToCode, _checkParametersForCalcForPrice_paymentTerm, _checkParametersForCalcForPrice_stationCode, _checkParametersForCalcForPrice_quotationNo, _checkParametersForCalcForPrice_orderId);
        System.out.println("checkParametersForCalcForPrice.result=" + _checkParametersForCalcForPrice__return);


        }
        {
        System.out.println("Invoking queryPlatformQuote...");
        String _queryPlatformQuote_systemFlag = "";
        String _queryPlatformQuote_itemCode = "";
        String _queryPlatformQuote_userScope = "";
        java.util.List<PlatformQuote> _queryPlatformQuote__return = port.queryPlatformQuote(_queryPlatformQuote_systemFlag, _queryPlatformQuote_itemCode, _queryPlatformQuote_userScope);
        System.out.println("queryPlatformQuote.result=" + _queryPlatformQuote__return);


        }
        {
        System.out.println("Invoking findAllValidBillMst...");
        String _findAllValidBillMst_gFUserCode = "";
        int _findAllValidBillMst_pageSize = 0;
        int _findAllValidBillMst_pageNum = 0;
        ValidResultBean _findAllValidBillMst__return = port.findAllValidBillMst(_findAllValidBillMst_gFUserCode, _findAllValidBillMst_pageSize, _findAllValidBillMst_pageNum);
        System.out.println("findAllValidBillMst.result=" + _findAllValidBillMst__return);


        }
        {
        System.out.println("Invoking purchase...");
        PurchaseCoupon _purchase_purchaseCoupon = null;
        String _purchase__return = port.purchase(_purchase_purchaseCoupon);
        System.out.println("purchase.result=" + _purchase__return);


        }
        {
        System.out.println("Invoking calcForPrice...");
        String _calcForPrice_systemFlag = "";
        int _calcForPrice_orderCatalog = 0;
        String _calcForPrice_orderNo = "";
        String _calcForPrice_calcParamaters = "";
        String _calcForPrice_gFUserFromCode = "";
        String _calcForPrice_gFUserToCode = "";
        String _calcForPrice_paymentTerm = "";
        String _calcForPrice_stationCode = "";
        String _calcForPrice_quotationNo = "";
        Integer _calcForPrice_orderId = null;
        String _calcForPrice__return = port.calcForPrice(_calcForPrice_systemFlag, _calcForPrice_orderCatalog, _calcForPrice_orderNo, _calcForPrice_calcParamaters, _calcForPrice_gFUserFromCode, _calcForPrice_gFUserToCode, _calcForPrice_paymentTerm, _calcForPrice_stationCode, _calcForPrice_quotationNo, _calcForPrice_orderId);
        System.out.println("calcForPrice.result=" + _calcForPrice__return);


        }
        {
        System.out.println("Invoking queryCalcStatus...");
        String _queryCalcStatus_systemFlag = "";
        String _queryCalcStatus_orderNo = "";
        String _queryCalcStatus_calcUserCode = "";
        String _queryCalcStatus__return = port.queryCalcStatus(_queryCalcStatus_systemFlag, _queryCalcStatus_orderNo, _queryCalcStatus_calcUserCode);
        System.out.println("queryCalcStatus.result=" + _queryCalcStatus__return);


        }
        {
        System.out.println("Invoking calcForPrice2...");
        String _calcForPrice2_systemFlag = "";
        int _calcForPrice2_orderCatalog = 0;
        String _calcForPrice2_orderNo = "";
        String _calcForPrice2_gFUserFromCode = "";
        String _calcForPrice2_gFUserToCode = "";
        String _calcForPrice2_paymentTerm = "";
        String _calcForPrice2_startAccountId = "";
        String _calcForPrice2_endAccountId = "";
        Integer _calcForPrice2_orderId = null;
        Integer _calcForPrice2_systemFrom = null;
        String _calcForPrice2__return = port.calcForPrice2(_calcForPrice2_systemFlag, _calcForPrice2_orderCatalog, _calcForPrice2_orderNo, _calcForPrice2_gFUserFromCode, _calcForPrice2_gFUserToCode, _calcForPrice2_paymentTerm, _calcForPrice2_startAccountId, _calcForPrice2_endAccountId, _calcForPrice2_orderId, _calcForPrice2_systemFrom);
        System.out.println("calcForPrice2.result=" + _calcForPrice2__return);


        }
        {
        System.out.println("Invoking queryPayinfo...");
        String _queryPayinfo_busiBookNo = "";
        String _queryPayinfo_validCode = "";
        PayInfoResultBean _queryPayinfo__return = port.queryPayinfo(_queryPayinfo_busiBookNo, _queryPayinfo_validCode);
        System.out.println("queryPayinfo.result=" + _queryPayinfo__return);


        }
        {
        System.out.println("Invoking cancelPurchase...");
        String _cancelPurchase_orderNo = "";
        String _cancelPurchase__return = port.cancelPurchase(_cancelPurchase_orderNo);
        System.out.println("cancelPurchase.result=" + _cancelPurchase__return);


        }
        {
        System.out.println("Invoking queryIarPayinfo...");
        String _queryIarPayinfo_busiBookNo = "";
        String _queryIarPayinfo_dispatchId = "";
        String _queryIarPayinfo_scheducarno = "";
        String _queryIarPayinfo_gfUserFromCode = "";
        String _queryIarPayinfo_validCode = "";
        String _queryIarPayinfo_gfUserToCode = "";
        String _queryIarPayinfo_validBillDocNo = "";
        PayInfoResultBean _queryIarPayinfo__return = port.queryIarPayinfo(_queryIarPayinfo_busiBookNo, _queryIarPayinfo_dispatchId, _queryIarPayinfo_scheducarno, _queryIarPayinfo_gfUserFromCode, _queryIarPayinfo_validCode, _queryIarPayinfo_gfUserToCode, _queryIarPayinfo_validBillDocNo);
        System.out.println("queryIarPayinfo.result=" + _queryIarPayinfo__return);


        }
        {
        System.out.println("Invoking queryPurchaseValidBillList...");
        String _queryPurchaseValidBillList_gFUserToCode = "";
        String _queryPurchaseValidBillList__return = port.queryPurchaseValidBillList(_queryPurchaseValidBillList_gFUserToCode);
        System.out.println("queryPurchaseValidBillList.result=" + _queryPurchaseValidBillList__return);


        }
        {
        System.out.println("Invoking calcForTempPrice...");
        String _calcForTempPrice_systemFlag = "";
        String _calcForTempPrice_allCalcParamaters = "";
        String _calcForTempPrice__return = port.calcForTempPrice(_calcForTempPrice_systemFlag, _calcForTempPrice_allCalcParamaters);
        System.out.println("calcForTempPrice.result=" + _calcForTempPrice__return);


        }
        {
        System.out.println("Invoking reward...");
        CalcForReward _reward_calcForReward = null;
        String _reward__return = port.reward(_reward_calcForReward);
        System.out.println("reward.result=" + _reward__return);


        }

        System.exit(0);
    }

}
