package com.gistandard.transport.order.webservice.client.order.transport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-08-24T10:20:27.813+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "emergentSchedu", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.EmergentSchedu")
    @WebMethod
    @ResponseWrapper(localName = "emergentScheduResponse", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.EmergentScheduResponse")
    public com.gistandard.transport.order.webservice.client.order.transport.ResultBean emergentSchedu(
            @WebParam(name = "arg0", targetNamespace = "")
            com.gistandard.transport.order.webservice.client.order.transport.EmergentScheduBean arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "scheduOrder", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.ScheduOrder")
    @WebMethod
    @ResponseWrapper(localName = "scheduOrderResponse", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.ScheduOrderResponse")
    public com.gistandard.transport.order.webservice.client.order.transport.ResultBean scheduOrder(
            @WebParam(name = "arg0", targetNamespace = "")
            com.gistandard.transport.order.webservice.client.order.transport.BroadcastOrderQueryParam arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryBroadcastOrderList", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.QueryBroadcastOrderList")
    @WebMethod
    @ResponseWrapper(localName = "queryBroadcastOrderListResponse", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.QueryBroadcastOrderListResponse")
    public String queryBroadcastOrderList(
            @WebParam(name = "arg0", targetNamespace = "")
            com.gistandard.transport.order.webservice.client.order.transport.BroadcastOrderQueryParam arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "comfirmedBroadcastOrder", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.ComfirmedBroadcastOrder")
    @WebMethod
    @ResponseWrapper(localName = "comfirmedBroadcastOrderResponse", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.ComfirmedBroadcastOrderResponse")
    public com.gistandard.transport.order.webservice.client.order.transport.ResultBean comfirmedBroadcastOrder(
            @WebParam(name = "arg0", targetNamespace = "")
            com.gistandard.transport.order.webservice.client.order.transport.BroadcastOrderQueryParam arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateScheduCarStatus", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.UpdateScheduCarStatus")
    @WebMethod
    @ResponseWrapper(localName = "updateScheduCarStatusResponse", targetNamespace = "http://service.server.WebService.HubPadServer.gsct.com/", className = "com.gistandard.transport.order.webservice.client.order.transport.UpdateScheduCarStatusResponse")
    public com.gistandard.transport.order.webservice.client.order.transport.ResultBean updateScheduCarStatus(
            @WebParam(name = "arg0", targetNamespace = "")
            com.gistandard.transport.order.webservice.client.order.transport.BroadcastOrderQueryParam arg0
    );
}
