package com.gistandard.transport.order.webservice.client.merchant.settlement;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-03-30T17:14:32.542+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "PreCalcManagerWebServiceImplService", 
                  wsdlLocation = "http://172.17.1.12:8080/WebService/PreCalcManagerWebService?wsdl",
                  targetNamespace = "http://webService.external.giifiCalc.transport.gistandard.com/") 
public class PreCalcManagerWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "PreCalcManagerWebServiceImplService");
    public final static QName PreCalcManagerWebServiceImplPort = new QName("http://webService.external.giifiCalc.transport.gistandard.com/", "PreCalcManagerWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.1.12:8080/WebService/PreCalcManagerWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PreCalcManagerWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.17.1.12:8080/WebService/PreCalcManagerWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PreCalcManagerWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PreCalcManagerWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PreCalcManagerWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PreCalcManagerWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PreCalcManagerWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PreCalcManagerWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PreCalcManagerWebService
     */
    @WebEndpoint(name = "PreCalcManagerWebServiceImplPort")
    public PreCalcManagerWebService getPreCalcManagerWebServiceImplPort() {
        return super.getPort(PreCalcManagerWebServiceImplPort, PreCalcManagerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PreCalcManagerWebService
     */
    @WebEndpoint(name = "PreCalcManagerWebServiceImplPort")
    public PreCalcManagerWebService getPreCalcManagerWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PreCalcManagerWebServiceImplPort, PreCalcManagerWebService.class, features);
    }

}
