package com.gistandard.transport.order.webservice.client.order.hub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-07-20T16:06:02.200+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "ExpreessOrderWebServiceService", 
                  wsdlLocation = "http://172.17.1.16:8080/WebService/expreessOrder?wsdl",
                  targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/") 
public class ExpreessOrderWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://order.server.mobilestation.webService.business.invent.valueplus.com/", "ExpreessOrderWebServiceService");
    public final static QName ExpreessOrderWebServicePort = new QName("http://order.server.mobilestation.webService.business.invent.valueplus.com/", "ExpreessOrderWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.1.16:8080/WebService/expreessOrder?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExpreessOrderWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.17.1.16:8080/WebService/expreessOrder?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExpreessOrderWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExpreessOrderWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpreessOrderWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ExpreessOrderWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExpreessOrderWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExpreessOrderWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ExpreessOrderWebService
     */
    @WebEndpoint(name = "ExpreessOrderWebServicePort")
    public ExpreessOrderWebService getExpreessOrderWebServicePort() {
        return super.getPort(ExpreessOrderWebServicePort, ExpreessOrderWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExpreessOrderWebService
     */
    @WebEndpoint(name = "ExpreessOrderWebServicePort")
    public ExpreessOrderWebService getExpreessOrderWebServicePort(WebServiceFeature... features) {
        return super.getPort(ExpreessOrderWebServicePort, ExpreessOrderWebService.class, features);
    }

}
