
package com.gistandard.transport.order.webservice.client.order.hub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-07-20T16:06:02.042+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class ExpreessOrderWebService_ExpreessOrderWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://order.server.mobilestation.webService.business.invent.valueplus.com/", "ExpreessOrderWebServiceService");

    private ExpreessOrderWebService_ExpreessOrderWebServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ExpreessOrderWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ExpreessOrderWebServiceService ss = new ExpreessOrderWebServiceService(wsdlURL, SERVICE_NAME);
        ExpreessOrderWebService port = ss.getExpreessOrderWebServicePort();  
        
        {
        System.out.println("Invoking applyExpreessOrder...");
        ApplyExpreessOrderRequest _applyExpreessOrder_applyExpreessOrderRequest = null;
        String _applyExpreessOrder__return = port.applyExpreessOrder(_applyExpreessOrder_applyExpreessOrderRequest);
        System.out.println("applyExpreessOrder.result=" + _applyExpreessOrder__return);


        }
        {
        System.out.println("Invoking mStationRefusOrder...");
        MStationRevOrderRequest _mStationRefusOrder_mStationRefusOrderRequest = null;
        String _mStationRefusOrder__return = port.mStationRefusOrder(_mStationRefusOrder_mStationRefusOrderRequest);
        System.out.println("mStationRefusOrder.result=" + _mStationRefusOrder__return);


        }
        {
        System.out.println("Invoking emergencySchudeCarOrder...");
        EmergencySchudeCarOrderRequest _emergencySchudeCarOrder_emergencySchudeCarOrderRequest = null;
        String _emergencySchudeCarOrder__return = port.emergencySchudeCarOrder(_emergencySchudeCarOrder_emergencySchudeCarOrderRequest);
        System.out.println("emergencySchudeCarOrder.result=" + _emergencySchudeCarOrder__return);


        }
        {
        System.out.println("Invoking mStationRefusOrderList...");
        java.util.List<MStationRevOrderRequest> _mStationRefusOrderList_mStationRefusOrderRequestList = null;
        String _mStationRefusOrderList__return = port.mStationRefusOrderList(_mStationRefusOrderList_mStationRefusOrderRequestList);
        System.out.println("mStationRefusOrderList.result=" + _mStationRefusOrderList__return);


        }
        {
        System.out.println("Invoking takeOverSchudeCarOrder...");
        TakeOverSchudeCarOrderRequest _takeOverSchudeCarOrder_takeOverSchudeCarOrderRequest = null;
        String _takeOverSchudeCarOrder__return = port.takeOverSchudeCarOrder(_takeOverSchudeCarOrder_takeOverSchudeCarOrderRequest);
        System.out.println("takeOverSchudeCarOrder.result=" + _takeOverSchudeCarOrder__return);


        }
        {
        System.out.println("Invoking failDeliverSchudeCarOrder...");
        FailDeliverSchudeCarOrderRequest _failDeliverSchudeCarOrder_failDeliverSchudeCarOrderRequest = null;
        String _failDeliverSchudeCarOrder__return = port.failDeliverSchudeCarOrder(_failDeliverSchudeCarOrder_failDeliverSchudeCarOrderRequest);
        System.out.println("failDeliverSchudeCarOrder.result=" + _failDeliverSchudeCarOrder__return);


        }
        {
        System.out.println("Invoking refuseSchudeCarOrder...");
        GiveUpSchudeCarOrderRequest _refuseSchudeCarOrder_refuseSchudeCarOrderRequest = null;
        String _refuseSchudeCarOrder__return = port.refuseSchudeCarOrder(_refuseSchudeCarOrder_refuseSchudeCarOrderRequest);
        System.out.println("refuseSchudeCarOrder.result=" + _refuseSchudeCarOrder__return);


        }
        {
        System.out.println("Invoking selectBusiStationInfo...");
        SelectBusiStationInfoRequest _selectBusiStationInfo_selectBusiStationInfoRequest = null;
        String _selectBusiStationInfo__return = port.selectBusiStationInfo(_selectBusiStationInfo_selectBusiStationInfoRequest);
        System.out.println("selectBusiStationInfo.result=" + _selectBusiStationInfo__return);


        }
        {
        System.out.println("Invoking queryExpreessOrderDetail...");
        QueryOrderDetailRequest _queryExpreessOrderDetail_queryExpreessOrderDetailRequest = null;
        String _queryExpreessOrderDetail__return = port.queryExpreessOrderDetail(_queryExpreessOrderDetail_queryExpreessOrderDetailRequest);
        System.out.println("queryExpreessOrderDetail.result=" + _queryExpreessOrderDetail__return);


        }
        {
        System.out.println("Invoking departSchudeCarOrder...");
        DepartSchudeCarOrderRequest _departSchudeCarOrder_departSchudeCarOrderRequest = null;
        String _departSchudeCarOrder__return = port.departSchudeCarOrder(_departSchudeCarOrder_departSchudeCarOrderRequest);
        System.out.println("departSchudeCarOrder.result=" + _departSchudeCarOrder__return);


        }
        {
        System.out.println("Invoking genSchecarId...");
        GenSchecarIdRequest _genSchecarId_genSchecarIdRequest = null;
        GenSchecarIdRequestResponse _genSchecarId__return = port.genSchecarId(_genSchecarId_genSchecarIdRequest);
        System.out.println("genSchecarId.result=" + _genSchecarId__return);


        }
        {
        System.out.println("Invoking getExpressScheduCarInfo...");
        GetExpressScheduCarInfoRequest _getExpressScheduCarInfo_getExpressScheduCarInfoRequest = null;
        String _getExpressScheduCarInfo__return = port.getExpressScheduCarInfo(_getExpressScheduCarInfo_getExpressScheduCarInfoRequest);
        System.out.println("getExpressScheduCarInfo.result=" + _getExpressScheduCarInfo__return);


        }
        {
        System.out.println("Invoking receiveExpreessOrder...");
        ReceiveExpreessOrderRequest _receiveExpreessOrder_receiveExpreessOrderRequest = null;
        String _receiveExpreessOrder__return = port.receiveExpreessOrder(_receiveExpreessOrder_receiveExpreessOrderRequest);
        System.out.println("receiveExpreessOrder.result=" + _receiveExpreessOrder__return);


        }
        {
        System.out.println("Invoking succDeliverSchudeCarOrderList...");
        java.util.List<SuccDeliverSchudeCarOrderRequest> _succDeliverSchudeCarOrderList_succDeliverSchudeCarOrderRequestList = null;
        String _succDeliverSchudeCarOrderList__return = port.succDeliverSchudeCarOrderList(_succDeliverSchudeCarOrderList_succDeliverSchudeCarOrderRequestList);
        System.out.println("succDeliverSchudeCarOrderList.result=" + _succDeliverSchudeCarOrderList__return);


        }
        {
        System.out.println("Invoking receiveExpreessOrderList...");
        java.util.List<ReceiveExpreessOrderRequest> _receiveExpreessOrderList_receiveExpreessOrderRequestList = null;
        String _receiveExpreessOrderList__return = port.receiveExpreessOrderList(_receiveExpreessOrderList_receiveExpreessOrderRequestList);
        System.out.println("receiveExpreessOrderList.result=" + _receiveExpreessOrderList__return);


        }
        {
        System.out.println("Invoking giveUpSchudeCarOrder...");
        GiveUpSchudeCarOrderRequest _giveUpSchudeCarOrder_refuseSchudeCarOrderRequest = null;
        String _giveUpSchudeCarOrder__return = port.giveUpSchudeCarOrder(_giveUpSchudeCarOrder_refuseSchudeCarOrderRequest);
        System.out.println("giveUpSchudeCarOrder.result=" + _giveUpSchudeCarOrder__return);


        }
        {
        System.out.println("Invoking mStationRevOrder...");
        MStationRevOrderRequest _mStationRevOrder_mStationRevOrderRequest = null;
        String _mStationRevOrder__return = port.mStationRevOrder(_mStationRevOrder_mStationRevOrderRequest);
        System.out.println("mStationRevOrder.result=" + _mStationRevOrder__return);


        }
        {
        System.out.println("Invoking succDeliverSchudeCarOrder...");
        SuccDeliverSchudeCarOrderRequest _succDeliverSchudeCarOrder_succDeliverSchudeCarOrderRequest = null;
        String _succDeliverSchudeCarOrder__return = port.succDeliverSchudeCarOrder(_succDeliverSchudeCarOrder_succDeliverSchudeCarOrderRequest);
        System.out.println("succDeliverSchudeCarOrder.result=" + _succDeliverSchudeCarOrder__return);


        }
        {
        System.out.println("Invoking refuseSchudeCarOrderList...");
        java.util.List<GiveUpSchudeCarOrderRequest> _refuseSchudeCarOrderList_refuseSchudeCarOrderRequestList = null;
        String _refuseSchudeCarOrderList__return = port.refuseSchudeCarOrderList(_refuseSchudeCarOrderList_refuseSchudeCarOrderRequestList);
        System.out.println("refuseSchudeCarOrderList.result=" + _refuseSchudeCarOrderList__return);


        }
        {
        System.out.println("Invoking returnDeliverSchudeCarOrder...");
        ReturnDeliverSchudeCarOrderRequest _returnDeliverSchudeCarOrder_returnDeliverSchudeCarOrderRequest = null;
        String _returnDeliverSchudeCarOrder__return = port.returnDeliverSchudeCarOrder(_returnDeliverSchudeCarOrder_returnDeliverSchudeCarOrderRequest);
        System.out.println("returnDeliverSchudeCarOrder.result=" + _returnDeliverSchudeCarOrder__return);


        }

        System.exit(0);
    }

}
