
package com.gistandard.transport.order.webservice.client.order.hub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-04-28T10:31:18.239+08:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "ExpreessException", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/")
public class ExpreessException_Exception extends Exception {
    
    private ExpreessException expreessException;

    public ExpreessException_Exception() {
        super();
    }
    
    public ExpreessException_Exception(String message) {
        super(message);
    }
    
    public ExpreessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ExpreessException_Exception(String message, ExpreessException expreessException) {
        super(message);
        this.expreessException = expreessException;
    }

    public ExpreessException_Exception(String message, ExpreessException expreessException, Throwable cause) {
        super(message, cause);
        this.expreessException = expreessException;
    }

    public ExpreessException getFaultInfo() {
        return this.expreessException;
    }
}
