package com.gistandard.transport.order.webservice.client.order.hub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-07-20T16:06:02.148+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", name = "ExpreessOrderWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ExpreessOrderWebService {

    @WebResult(name = "applyExpreessOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "applyExpreessOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ApplyExpreessOrder")
    @WebMethod
    @ResponseWrapper(localName = "applyExpreessOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ApplyExpreessOrderResponse")
    public String applyExpreessOrder(
            @WebParam(name = "applyExpreessOrderRequest", targetNamespace = "")
            ApplyExpreessOrderRequest applyExpreessOrderRequest
    );

    @WebResult(name = "mStationRefusOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "mStationRefusOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.MStationRefusOrder")
    @WebMethod
    @ResponseWrapper(localName = "mStationRefusOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.MStationRefusOrderResponse")
    public String mStationRefusOrder(
            @WebParam(name = "mStationRefusOrderRequest", targetNamespace = "")
            MStationRevOrderRequest mStationRefusOrderRequest
    );

    @WebResult(name = "emergencySchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "emergencySchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.EmergencySchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "emergencySchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.EmergencySchudeCarOrderResponse")
    public String emergencySchudeCarOrder(
            @WebParam(name = "emergencySchudeCarOrderRequest", targetNamespace = "")
            EmergencySchudeCarOrderRequest emergencySchudeCarOrderRequest
    );

    @WebResult(name = "mStationRefusOrderResultList", targetNamespace = "")
    @RequestWrapper(localName = "mStationRefusOrderList", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.MStationRefusOrderList")
    @WebMethod
    @ResponseWrapper(localName = "mStationRefusOrderListResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.MStationRefusOrderListResponse")
    public String mStationRefusOrderList(
            @WebParam(name = "mStationRefusOrderRequestList", targetNamespace = "")
            java.util.List<MStationRevOrderRequest> mStationRefusOrderRequestList
    );

    @WebResult(name = "takeOverSchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "takeOverSchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.TakeOverSchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "takeOverSchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.TakeOverSchudeCarOrderResponse")
    public String takeOverSchudeCarOrder(
            @WebParam(name = "takeOverSchudeCarOrderRequest", targetNamespace = "")
            TakeOverSchudeCarOrderRequest takeOverSchudeCarOrderRequest
    );

    @WebResult(name = "failDeliverSchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "failDeliverSchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.FailDeliverSchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "failDeliverSchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.FailDeliverSchudeCarOrderResponse")
    public String failDeliverSchudeCarOrder(
            @WebParam(name = "failDeliverSchudeCarOrderRequest", targetNamespace = "")
            FailDeliverSchudeCarOrderRequest failDeliverSchudeCarOrderRequest
    );

    @WebResult(name = "refuseSchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "refuseSchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.RefuseSchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "refuseSchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.RefuseSchudeCarOrderResponse")
    public String refuseSchudeCarOrder(
            @WebParam(name = "refuseSchudeCarOrderRequest", targetNamespace = "")
            GiveUpSchudeCarOrderRequest refuseSchudeCarOrderRequest
    );

    @WebResult(name = "selectBusiStationInfoResult", targetNamespace = "")
    @RequestWrapper(localName = "selectBusiStationInfo", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.SelectBusiStationInfo")
    @WebMethod
    @ResponseWrapper(localName = "selectBusiStationInfoResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.SelectBusiStationInfoResponse")
    public String selectBusiStationInfo(
            @WebParam(name = "selectBusiStationInfoRequest", targetNamespace = "")
            SelectBusiStationInfoRequest selectBusiStationInfoRequest
    );

    @WebResult(name = "queryExpreessOrderDetailResult", targetNamespace = "")
    @RequestWrapper(localName = "queryExpreessOrderDetail", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.QueryExpreessOrderDetail")
    @WebMethod
    @ResponseWrapper(localName = "queryExpreessOrderDetailResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.QueryExpreessOrderDetailResponse")
    public String queryExpreessOrderDetail(
            @WebParam(name = "queryExpreessOrderDetailRequest", targetNamespace = "")
            QueryOrderDetailRequest queryExpreessOrderDetailRequest
    );

    @WebResult(name = "departSchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "departSchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.DepartSchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "departSchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.DepartSchudeCarOrderResponse")
    public String departSchudeCarOrder(
            @WebParam(name = "departSchudeCarOrderRequest", targetNamespace = "")
            DepartSchudeCarOrderRequest departSchudeCarOrderRequest
    );

    @WebResult(name = "genSchecarIdResult", targetNamespace = "")
    @RequestWrapper(localName = "genSchecarId", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.GenSchecarId")
    @WebMethod
    @ResponseWrapper(localName = "genSchecarIdResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.GenSchecarIdResponse")
    public GenSchecarIdRequestResponse genSchecarId(
            @WebParam(name = "genSchecarIdRequest", targetNamespace = "")
            GenSchecarIdRequest genSchecarIdRequest
    );

    @WebResult(name = "getExpressScheduCarInfoResult", targetNamespace = "")
    @RequestWrapper(localName = "getExpressScheduCarInfo", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.GetExpressScheduCarInfo")
    @WebMethod
    @ResponseWrapper(localName = "getExpressScheduCarInfoResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.GetExpressScheduCarInfoResponse")
    public String getExpressScheduCarInfo(
            @WebParam(name = "getExpressScheduCarInfoRequest", targetNamespace = "")
            GetExpressScheduCarInfoRequest getExpressScheduCarInfoRequest
    );

    @WebResult(name = "receiveExpreessOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "receiveExpreessOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ReceiveExpreessOrder")
    @WebMethod
    @ResponseWrapper(localName = "receiveExpreessOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ReceiveExpreessOrderResponse")
    public String receiveExpreessOrder(
            @WebParam(name = "receiveExpreessOrderRequest", targetNamespace = "")
            ReceiveExpreessOrderRequest receiveExpreessOrderRequest
    );

    @WebResult(name = "succDeliverSchudeCarOrderResultList", targetNamespace = "")
    @RequestWrapper(localName = "succDeliverSchudeCarOrderList", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.SuccDeliverSchudeCarOrderList")
    @WebMethod
    @ResponseWrapper(localName = "succDeliverSchudeCarOrderListResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.SuccDeliverSchudeCarOrderListResponse")
    public String succDeliverSchudeCarOrderList(
            @WebParam(name = "succDeliverSchudeCarOrderRequestList", targetNamespace = "")
            java.util.List<SuccDeliverSchudeCarOrderRequest> succDeliverSchudeCarOrderRequestList
    );

    @WebResult(name = "receiveExpreessOrderListResult", targetNamespace = "")
    @RequestWrapper(localName = "receiveExpreessOrderList", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ReceiveExpreessOrderList")
    @WebMethod
    @ResponseWrapper(localName = "receiveExpreessOrderListResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ReceiveExpreessOrderListResponse")
    public String receiveExpreessOrderList(
            @WebParam(name = "receiveExpreessOrderRequestList", targetNamespace = "")
            java.util.List<ReceiveExpreessOrderRequest> receiveExpreessOrderRequestList
    );

    @WebResult(name = "refuseSchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "giveUpSchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.GiveUpSchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "giveUpSchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.GiveUpSchudeCarOrderResponse")
    public String giveUpSchudeCarOrder(
            @WebParam(name = "refuseSchudeCarOrderRequest", targetNamespace = "")
            GiveUpSchudeCarOrderRequest refuseSchudeCarOrderRequest
    );

    @WebResult(name = "mStationRevOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "mStationRevOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.MStationRevOrder")
    @WebMethod
    @ResponseWrapper(localName = "mStationRevOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.MStationRevOrderResponse")
    public String mStationRevOrder(
            @WebParam(name = "mStationRevOrderRequest", targetNamespace = "")
            MStationRevOrderRequest mStationRevOrderRequest
    );

    @WebResult(name = "succDeliverSchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "succDeliverSchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.SuccDeliverSchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "succDeliverSchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.SuccDeliverSchudeCarOrderResponse")
    public String succDeliverSchudeCarOrder(
            @WebParam(name = "succDeliverSchudeCarOrderRequest", targetNamespace = "")
            SuccDeliverSchudeCarOrderRequest succDeliverSchudeCarOrderRequest
    );

    @WebResult(name = "refuseSchudeCarOrderResultList", targetNamespace = "")
    @RequestWrapper(localName = "refuseSchudeCarOrderList", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.RefuseSchudeCarOrderList")
    @WebMethod
    @ResponseWrapper(localName = "refuseSchudeCarOrderListResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.RefuseSchudeCarOrderListResponse")
    public String refuseSchudeCarOrderList(
            @WebParam(name = "refuseSchudeCarOrderRequestList", targetNamespace = "")
            java.util.List<GiveUpSchudeCarOrderRequest> refuseSchudeCarOrderRequestList
    );

    @WebResult(name = "returnDeliverSchudeCarOrderResult", targetNamespace = "")
    @RequestWrapper(localName = "returnDeliverSchudeCarOrder", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ReturnDeliverSchudeCarOrder")
    @WebMethod
    @ResponseWrapper(localName = "returnDeliverSchudeCarOrderResponse", targetNamespace = "http://order.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.hub.ReturnDeliverSchudeCarOrderResponse")
    public String returnDeliverSchudeCarOrder(
            @WebParam(name = "returnDeliverSchudeCarOrderRequest", targetNamespace = "")
            ReturnDeliverSchudeCarOrderRequest returnDeliverSchudeCarOrderRequest
    );
}
