package com.gistandard.transport.order.webservice.client.order.expressbusiness;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-07-27T16:03:08.349+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", name = "ExpressBusinessOrderWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ExpressBusinessOrderWebService {

    @WebResult(name = "checkLocalConnectOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "checkLocalConnectOrder", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.CheckLocalConnectOrder")
    @WebMethod
    @ResponseWrapper(localName = "checkLocalConnectOrderResponse", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.CheckLocalConnectOrderResponse")
    public boolean checkLocalConnectOrder(
            @WebParam(name = "checkLocalConnectOrderRequest", targetNamespace = "")
            CheckLocalConnectOrderReq checkLocalConnectOrderRequest
    );

    @WebResult(name = "motorcateQuoteResponse", targetNamespace = "")
    @RequestWrapper(localName = "motorcateQuote", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.MotorcateQuote")
    @WebMethod
    @ResponseWrapper(localName = "motorcateQuoteResponse", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.MotorcateQuoteResponse")
    public ServiceResponse motorcateQuote(
            @WebParam(name = "motorcateQuoteRequest", targetNamespace = "")
            MotorcateQuoteReq motorcateQuoteRequest
    );

    @WebResult(name = "batchSyncBusinessOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "batchSyncBusinessOrder", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchSyncBusinessOrder")
    @WebMethod
    @ResponseWrapper(localName = "batchSyncBusinessOrderResponse", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchSyncBusinessOrderResponse")
    public ServiceResponse batchSyncBusinessOrder(
            @WebParam(name = "batchSyncBusinessOrderRequest", targetNamespace = "")
            BatchSyncBusinessOrderRequest batchSyncBusinessOrderRequest
    );

    @WebResult(name = "mainOrderNotifyResponse", targetNamespace = "")
    @RequestWrapper(localName = "mainOrderNotify", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.MainOrderNotify")
    @WebMethod
    @ResponseWrapper(localName = "mainOrderNotifyResponse", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.MainOrderNotifyResponse")
    public ServiceResponse mainOrderNotify(
            @WebParam(name = "mainOrderNotifyRequest", targetNamespace = "")
            com.gistandard.transport.order.webservice.client.order.expressbusiness.MainOrderNotifyRequest mainOrderNotifyRequest
    );

    @WebResult(name = "batchSyncOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "batchSyncOrder", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchSyncOrder")
    @WebMethod
    @ResponseWrapper(localName = "batchSyncOrderResponse", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchSyncOrderResponse")
    public ServiceResponse batchSyncOrder(
            @WebParam(name = "batchSyncOrderRequest", targetNamespace = "")
            BatchSyncOrderRequest batchSyncOrderRequest
    );

    @WebResult(name = "batchDeleteBusinessOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "batchDeleteBusinessOrder", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchDeleteBusinessOrder")
    @WebMethod
    @ResponseWrapper(localName = "batchDeleteBusinessOrderResponse", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchDeleteBusinessOrderResponse")
    public ServiceResponse batchDeleteBusinessOrder(
            @WebParam(name = "batchDeleteBusinessOrderRequest", targetNamespace = "")
            BatchDeleteBusinessOrderRequest batchDeleteBusinessOrderRequest
    );

    @WebResult(name = "batchQueryICalcForPriceResponse", targetNamespace = "")
    @RequestWrapper(localName = "batchQueryICalcForPrice", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchQueryICalcForPrice")
    @WebMethod
    @ResponseWrapper(localName = "batchQueryICalcForPriceResponse", targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", className = "com.gistandard.transport.order.webservice.client.order.expressbusiness.BatchQueryICalcForPriceResponse")
    public ServiceResponse batchQueryICalcForPrice(
            @WebParam(name = "batchQueryICalcForPriceRequest", targetNamespace = "")
            BatchQueryICalcForPriceRequest batchQueryICalcForPriceRequest
    );
}
