
package com.gistandard.transport.order.webservice.client.order.expressbusiness;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-07-27T16:03:08.250+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class ExpressBusinessOrderWebService_ExpressBusinessOrderWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", "ExpressBusinessOrderWebServiceService");

    private ExpressBusinessOrderWebService_ExpressBusinessOrderWebServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ExpressBusinessOrderWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ExpressBusinessOrderWebServiceService ss = new ExpressBusinessOrderWebServiceService(wsdlURL, SERVICE_NAME);
        ExpressBusinessOrderWebService port = ss.getExpressBusinessOrderWebServicePort();  
        
        {
        System.out.println("Invoking checkLocalConnectOrder...");
        CheckLocalConnectOrderReq _checkLocalConnectOrder_checkLocalConnectOrderRequest = null;
        boolean _checkLocalConnectOrder__return = port.checkLocalConnectOrder(_checkLocalConnectOrder_checkLocalConnectOrderRequest);
        System.out.println("checkLocalConnectOrder.result=" + _checkLocalConnectOrder__return);


        }
        {
        System.out.println("Invoking motorcateQuote...");
        MotorcateQuoteReq _motorcateQuote_motorcateQuoteRequest = null;
        ServiceResponse _motorcateQuote__return = port.motorcateQuote(_motorcateQuote_motorcateQuoteRequest);
        System.out.println("motorcateQuote.result=" + _motorcateQuote__return);


        }
        {
        System.out.println("Invoking batchSyncBusinessOrder...");
        BatchSyncBusinessOrderRequest _batchSyncBusinessOrder_batchSyncBusinessOrderRequest = null;
        ServiceResponse _batchSyncBusinessOrder__return = port.batchSyncBusinessOrder(_batchSyncBusinessOrder_batchSyncBusinessOrderRequest);
        System.out.println("batchSyncBusinessOrder.result=" + _batchSyncBusinessOrder__return);


        }
        {
        System.out.println("Invoking mainOrderNotify...");
        com.gistandard.transport.order.webservice.client.order.expressbusiness.MainOrderNotifyRequest _mainOrderNotify_mainOrderNotifyRequest = null;
        ServiceResponse _mainOrderNotify__return = port.mainOrderNotify(_mainOrderNotify_mainOrderNotifyRequest);
        System.out.println("mainOrderNotify.result=" + _mainOrderNotify__return);


        }
        {
        System.out.println("Invoking batchSyncOrder...");
        BatchSyncOrderRequest _batchSyncOrder_batchSyncOrderRequest = null;
        ServiceResponse _batchSyncOrder__return = port.batchSyncOrder(_batchSyncOrder_batchSyncOrderRequest);
        System.out.println("batchSyncOrder.result=" + _batchSyncOrder__return);


        }
        {
        System.out.println("Invoking batchDeleteBusinessOrder...");
        BatchDeleteBusinessOrderRequest _batchDeleteBusinessOrder_batchDeleteBusinessOrderRequest = null;
        ServiceResponse _batchDeleteBusinessOrder__return = port.batchDeleteBusinessOrder(_batchDeleteBusinessOrder_batchDeleteBusinessOrderRequest);
        System.out.println("batchDeleteBusinessOrder.result=" + _batchDeleteBusinessOrder__return);


        }
        {
        System.out.println("Invoking batchQueryICalcForPrice...");
        BatchQueryICalcForPriceRequest _batchQueryICalcForPrice_batchQueryICalcForPriceRequest = null;
        ServiceResponse _batchQueryICalcForPrice__return = port.batchQueryICalcForPrice(_batchQueryICalcForPrice_batchQueryICalcForPriceRequest);
        System.out.println("batchQueryICalcForPrice.result=" + _batchQueryICalcForPrice__return);


        }

        System.exit(0);
    }

}
