package com.gistandard.transport.order.webservice.client.order.expressbusiness;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-07-27T16:03:08.356+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "ExpressBusinessOrderWebServiceService", 
                  wsdlLocation = "http://172.17.1.16:8080/WebService/expreessBusinessOrder?wsdl",
                  targetNamespace = "http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/") 
public class ExpressBusinessOrderWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", "ExpressBusinessOrderWebServiceService");
    public final static QName ExpressBusinessOrderWebServicePort = new QName("http://businessOrder.server.mobilestation.webService.business.invent.valueplus.com/", "ExpressBusinessOrderWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.1.16:8080/WebService/expreessBusinessOrder?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExpressBusinessOrderWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.17.1.16:8080/WebService/expreessBusinessOrder?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExpressBusinessOrderWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExpressBusinessOrderWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpressBusinessOrderWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ExpressBusinessOrderWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExpressBusinessOrderWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExpressBusinessOrderWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ExpressBusinessOrderWebService
     */
    @WebEndpoint(name = "ExpressBusinessOrderWebServicePort")
    public ExpressBusinessOrderWebService getExpressBusinessOrderWebServicePort() {
        return super.getPort(ExpressBusinessOrderWebServicePort, ExpressBusinessOrderWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExpressBusinessOrderWebService
     */
    @WebEndpoint(name = "ExpressBusinessOrderWebServicePort")
    public ExpressBusinessOrderWebService getExpressBusinessOrderWebServicePort(WebServiceFeature... features) {
        return super.getPort(ExpressBusinessOrderWebServicePort, ExpressBusinessOrderWebService.class, features);
    }

}
