package com.gistandard.transport.order.webservice.client.FreightCommonService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-09-30T17:41:50.541+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "FreightCommonService", 
                  wsdlLocation = "http://182.150.61.188/freight/zrxservices/FreightCommonService?wsdl",
                  targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight") 
public class FreightCommonService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wss.cpic.com.cn/propertyinsurance/commonservice/freight", "FreightCommonService");
    public final static QName FreightCommonServicePort = new QName("http://wss.cpic.com.cn/propertyinsurance/commonservice/freight", "FreightCommonServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://182.150.61.188/freight/zrxservices/FreightCommonService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FreightCommonService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://182.150.61.188/freight/zrxservices/FreightCommonService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FreightCommonService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FreightCommonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FreightCommonService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FreightCommonService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FreightCommonService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FreightCommonService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IZrxCommonService
     */
    @WebEndpoint(name = "FreightCommonServicePort")
    public IZrxCommonService getFreightCommonServicePort() {
        return super.getPort(FreightCommonServicePort, IZrxCommonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IZrxCommonService
     */
    @WebEndpoint(name = "FreightCommonServicePort")
    public IZrxCommonService getFreightCommonServicePort(WebServiceFeature... features) {
        return super.getPort(FreightCommonServicePort, IZrxCommonService.class, features);
    }

}
