
package com.gistandard.transport.order.webservice.client.FreightCommonService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-09-30T17:41:50.490+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class IZrxCommonService_FreightCommonServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://wss.cpic.com.cn/propertyinsurance/commonservice/freight", "FreightCommonService");

    private IZrxCommonService_FreightCommonServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FreightCommonService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FreightCommonService ss = new FreightCommonService(wsdlURL, SERVICE_NAME);
        IZrxCommonService port = ss.getFreightCommonServicePort();  
        
        {
        System.out.println("Invoking endorse...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.EndorseRequest _endorse_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.EndorseResponse2 _endorse__return = port.endorse(_endorse_request);
            System.out.println("endorse.result=" + _endorse__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking claimReportInfo...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _claimReportInfo_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _claimReportInfo__return = port.claimReportInfo(_claimReportInfo_request);
            System.out.println("claimReportInfo.result=" + _claimReportInfo__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking doIssuedPaymentPolicy...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _doIssuedPaymentPolicy_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _doIssuedPaymentPolicy__return = port.doIssuedPaymentPolicy(_doIssuedPaymentPolicy_request);
            System.out.println("doIssuedPaymentPolicy.result=" + _doIssuedPaymentPolicy__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking doClaimSettl...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _doClaimSettl_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _doClaimSettl__return = port.doClaimSettl(_doClaimSettl_request);
            System.out.println("doClaimSettl.result=" + _doClaimSettl__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryApplicationStatus...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _queryApplicationStatus_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _queryApplicationStatus__return = port.queryApplicationStatus(_queryApplicationStatus_request);
            System.out.println("queryApplicationStatus.result=" + _queryApplicationStatus__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancelApplication...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _cancelApplication_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _cancelApplication__return = port.cancelApplication(_cancelApplication_request);
            System.out.println("cancelApplication.result=" + _cancelApplication__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking doQueryBasicData...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _doQueryBasicData_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _doQueryBasicData__return = port.doQueryBasicData(_doQueryBasicData_request);
            System.out.println("doQueryBasicData.result=" + _doQueryBasicData__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryPolicyStatus...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _queryPolicyStatus_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _queryPolicyStatus__return = port.queryPolicyStatus(_queryPolicyStatus_request);
            System.out.println("queryPolicyStatus.result=" + _queryPolicyStatus__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking postApplication...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _postApplication_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _postApplication__return = port.postApplication(_postApplication_request);
            System.out.println("postApplication.result=" + _postApplication__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking approval...");
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest _approval_request = null;
        try {
            com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 _approval__return = port.approval(_approval_request);
            System.out.println("approval.result=" + _approval__return);

        } catch (WssException_Exception e) { 
            System.out.println("Expected exception: WssException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
