package com.gistandard.transport.order.webservice.client.FreightCommonService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-09-30T17:41:50.533+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight", name = "IZrxCommonService")
@XmlSeeAlso({ObjectFactory.class})
public interface IZrxCommonService {

    @WebResult(name = "endorseReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "endorse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.Endorse")
    @WebMethod
    @ResponseWrapper(localName = "endorseResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.EndorseResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.EndorseResponse2 endorse(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.EndorseRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "claimReportInfo", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.ClaimReportInfo")
    @WebMethod
    @ResponseWrapper(localName = "claimReportInfoResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.ClaimReportInfoResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 claimReportInfo(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "doIssuedPaymentPolicy", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.DoIssuedPaymentPolicy")
    @WebMethod
    @ResponseWrapper(localName = "doIssuedPaymentPolicyResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.DoIssuedPaymentPolicyResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 doIssuedPaymentPolicy(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "doClaimSettl", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.DoClaimSettl")
    @WebMethod
    @ResponseWrapper(localName = "doClaimSettlResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.DoClaimSettlResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 doClaimSettl(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "queryApplicationStatus", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.QueryApplicationStatus")
    @WebMethod
    @ResponseWrapper(localName = "queryApplicationStatusResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.QueryApplicationStatusResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 queryApplicationStatus(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "cancelApplication", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.CancelApplication")
    @WebMethod
    @ResponseWrapper(localName = "cancelApplicationResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.CancelApplicationResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 cancelApplication(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "doQueryBasicData", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.DoQueryBasicData")
    @WebMethod
    @ResponseWrapper(localName = "doQueryBasicDataResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.DoQueryBasicDataResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 doQueryBasicData(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "queryPolicyStatus", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.QueryPolicyStatus")
    @WebMethod
    @ResponseWrapper(localName = "queryPolicyStatusResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.QueryPolicyStatusResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 queryPolicyStatus(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "postApplication", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.PostApplication")
    @WebMethod
    @ResponseWrapper(localName = "postApplicationResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.PostApplicationResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 postApplication(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;

    @WebResult(name = "approvalReturn", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
    @RequestWrapper(localName = "approval", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.Approval")
    @WebMethod
    @ResponseWrapper(localName = "approvalResponse", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types", className = "com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse")
    public com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalResponse2 approval(
        @WebParam(name = "request", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight/types")
        com.gistandard.transport.order.webservice.client.FreightCommonService.ApprovalRequest request
    ) throws WssException_Exception;
}
