
package com.gistandard.transport.order.webservice.client.FreightCommonService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-09-30T17:41:50.527+08:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "fault", targetNamespace = "http://wss.cpic.com.cn/propertyinsurance/commonservice/freight")
public class WssException_Exception extends Exception {
    
    private com.gistandard.transport.order.webservice.client.FreightCommonService.WssException fault;

    public WssException_Exception() {
        super();
    }
    
    public WssException_Exception(String message) {
        super(message);
    }
    
    public WssException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WssException_Exception(String message, com.gistandard.transport.order.webservice.client.FreightCommonService.WssException fault) {
        super(message);
        this.fault = fault;
    }

    public WssException_Exception(String message, com.gistandard.transport.order.webservice.client.FreightCommonService.WssException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.gistandard.transport.order.webservice.client.FreightCommonService.WssException getFaultInfo() {
        return this.fault;
    }
}
