
package com.gistandard.transport.calculate.webservice.generalAcctService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-04-25T15:58:56.178+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class GeneralAcctWebService_GeneralAcctWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.webservice.gistandard.com/", "GeneralAcctWebServiceService");

    private GeneralAcctWebService_GeneralAcctWebServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GeneralAcctWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GeneralAcctWebServiceService ss = new GeneralAcctWebServiceService(wsdlURL, SERVICE_NAME);
        GeneralAcctWebService port = ss.getGeneralAcctWebServicePort();  
        
        {
        System.out.println("Invoking confirmPayment1...");
        java.util.List<com.gistandard.transport.calculate.webservice.generalAcctService.OrderConfirmPayBean> _confirmPayment1_arg0 = null;
        String _confirmPayment1__return = port.confirmPayment1(_confirmPayment1_arg0);
        System.out.println("confirmPayment1.result=" + _confirmPayment1__return);


        }
        {
        System.out.println("Invoking confirmPayment...");
        java.util.List<ConfirmPayRequestBean> _confirmPayment_arg0 = null;
        String _confirmPayment__return = port.confirmPayment(_confirmPayment_arg0);
        System.out.println("confirmPayment.result=" + _confirmPayment__return);


        }
        {
        System.out.println("Invoking confirmPayAtMS...");
        java.util.List<GatrxMstRequestBean> _confirmPayAtMS_arg0 = null;
        String _confirmPayAtMS__return = port.confirmPayAtMS(_confirmPayAtMS_arg0);
        System.out.println("confirmPayAtMS.result=" + _confirmPayAtMS__return);


        }
        {
        System.out.println("Invoking confirmPay...");
        java.util.List<ConfirmPayRequestBean> _confirmPay_arg0 = null;
        String _confirmPay__return = port.confirmPay(_confirmPay_arg0);
        System.out.println("confirmPay.result=" + _confirmPay__return);


        }

        System.exit(0);
    }

}
