package com.gistandard.transport.calculate.webservice.generalAcctService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-04-25T15:58:56.225+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "GeneralAcctWebServiceService", 
                  wsdlLocation = "http://172.17.1.13:8080/generalAcctWebService/generalAcct?wsdl",
                  targetNamespace = "http://server.webservice.gistandard.com/") 
public class GeneralAcctWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.webservice.gistandard.com/", "GeneralAcctWebServiceService");
    public final static QName GeneralAcctWebServicePort = new QName("http://server.webservice.gistandard.com/", "GeneralAcctWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.1.13:8080/generalAcctWebService/generalAcct?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneralAcctWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.17.1.13:8080/generalAcctWebService/generalAcct?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeneralAcctWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneralAcctWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneralAcctWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GeneralAcctWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GeneralAcctWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GeneralAcctWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GeneralAcctWebService
     */
    @WebEndpoint(name = "GeneralAcctWebServicePort")
    public GeneralAcctWebService getGeneralAcctWebServicePort() {
        return super.getPort(GeneralAcctWebServicePort, GeneralAcctWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneralAcctWebService
     */
    @WebEndpoint(name = "GeneralAcctWebServicePort")
    public GeneralAcctWebService getGeneralAcctWebServicePort(WebServiceFeature... features) {
        return super.getPort(GeneralAcctWebServicePort, GeneralAcctWebService.class, features);
    }

}
