package com.gistandard.transport.calculate.webservice.generalAcctService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-04-25T15:58:56.219+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://server.webservice.gistandard.com/", name = "GeneralAcctWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface GeneralAcctWebService {

    @WebResult(name = "confirmPayment1", targetNamespace = "")
    @RequestWrapper(localName = "confirmPayment1", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPayment1")
    @WebMethod
    @ResponseWrapper(localName = "confirmPayment1Response", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPayment1Response")
    public String confirmPayment1(
            @WebParam(name = "arg0", targetNamespace = "")
            java.util.List<com.gistandard.transport.calculate.webservice.generalAcctService.OrderConfirmPayBean> arg0
    );

    @WebResult(name = "confirmPayment", targetNamespace = "")
    @RequestWrapper(localName = "confirmPayment", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPayment")
    @WebMethod
    @ResponseWrapper(localName = "confirmPaymentResponse", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPaymentResponse")
    public String confirmPayment(
            @WebParam(name = "arg0", targetNamespace = "")
            java.util.List<ConfirmPayRequestBean> arg0
    );

    @WebResult(name = "confirmPayAtMS", targetNamespace = "")
    @RequestWrapper(localName = "confirmPayAtMS", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPayAtMS")
    @WebMethod
    @ResponseWrapper(localName = "confirmPayAtMSResponse", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPayAtMSResponse")
    public String confirmPayAtMS(
            @WebParam(name = "arg0", targetNamespace = "")
            java.util.List<GatrxMstRequestBean> arg0
    );

    @WebResult(name = "confirmPay", targetNamespace = "")
    @RequestWrapper(localName = "confirmPay", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPay")
    @WebMethod
    @ResponseWrapper(localName = "confirmPayResponse", targetNamespace = "http://server.webservice.gistandard.com/", className = "com.gistandard.transport.calculate.webservice.generalAcctService.ConfirmPayResponse")
    public String confirmPay(
            @WebParam(name = "arg0", targetNamespace = "")
            java.util.List<ConfirmPayRequestBean> arg0
    );
}
