
package com.gistandard.transport.sms.webservice.smsService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-02-05T10:26:14.214+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class CmccMasWbs_CmccMasWbs_Client {

    private static final QName SERVICE_NAME = new QName("http://www.csapi.org/service", "cmcc_mas_wbs");

    private CmccMasWbs_CmccMasWbs_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CmccMasWbs_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CmccMasWbs_Service ss = new CmccMasWbs_Service(wsdlURL, SERVICE_NAME);
        CmccMasWbs port = ss.getCmccMasWbs();  
        
        {
        System.out.println("Invoking endUssd...");
        EndUssdRequest _endUssd_endUssdRequest = null;
        try {
            port.endUssd(_endUssd_endUssdRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendPush...");
        SendPushRequest _sendPush_sendPushRequest = null;
        try {
            SendPushResponse _sendPush__return = port.sendPush(_sendPush_sendPushRequest);
            System.out.println("sendPush.result=" + _sendPush__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notifySmsDeliveryStatus...");
        com.gistandard.transport.sms.webservice.smsService.NotifySmsDeliveryStatusRequest _notifySmsDeliveryStatus_notifySmsDeliveryStatusRequest = null;
        try {
            port.notifySmsDeliveryStatus(_notifySmsDeliveryStatus_notifySmsDeliveryStatusRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking apSvcAuthentic...");
        APSvcAuthenticReq _apSvcAuthentic_apSvcAuthenticReq = null;
        try {
            APSvcAuthenticRsp _apSvcAuthentic__return = port.apSvcAuthentic(_apSvcAuthentic_apSvcAuthenticReq);
            System.out.println("apSvcAuthentic.result=" + _apSvcAuthentic__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendSms...");
        SendSmsRequest _sendSms_sendSmsRequest = null;
        try {
            SendSmsResponse _sendSms__return = port.sendSms(_sendSms_sendSmsRequest);
            System.out.println("sendSms.result=" + _sendSms__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getLocation...");
        GetLocationRequest _getLocation_getLocationRequest = null;
        try {
            GetLocationResponse _getLocation__return = port.getLocation(_getLocation_getLocationRequest);
            System.out.println("getLocation.result=" + _getLocation__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getReceivedMessages...");
        GetReceivedMessagesRequest _getReceivedMessages_getReceivedMessagesRequest = null;
        try {
            GetReceivedMessagesResponse _getReceivedMessages__return = port.getReceivedMessages(_getReceivedMessages_getReceivedMessagesRequest);
            System.out.println("getReceivedMessages.result=" + _getReceivedMessages__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notifyPushDeliveryReceipt...");
        com.gistandard.transport.sms.webservice.smsService.NotifyPushDeliveryReceiptRequest _notifyPushDeliveryReceipt_notifyPushDeliveryReceiptRequest = null;
        try {
            port.notifyPushDeliveryReceipt(_notifyPushDeliveryReceipt_notifyPushDeliveryReceiptRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking stopNotification...");
        StopNotificationRequest _stopNotification_stopNotificationRequest = null;
        try {
            port.stopNotification(_stopNotification_stopNotificationRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking endNotification...");
        EndNotificationRequest _endNotification_endNotificationRequest = null;
        try {
            port.endNotification(_endNotification_endNotificationRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPushDeliveryStatus...");
        com.gistandard.transport.sms.webservice.smsService.GetPushDeliveryStatusRequest _getPushDeliveryStatus_getPushDeliveryStatusRequest = null;
        try {
            com.gistandard.transport.sms.webservice.smsService.GetPushDeliveryStatusResponse _getPushDeliveryStatus__return = port.getPushDeliveryStatus(_getPushDeliveryStatus_getPushDeliveryStatusRequest);
            System.out.println("getPushDeliveryStatus.result=" + _getPushDeliveryStatus__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getReceivedSms...");
        GetReceivedSmsRequest _getReceivedSms_getReceivedSmsRequest = null;
        try {
            GetReceivedSmsResponse _getReceivedSms__return = port.getReceivedSms(_getReceivedSms_getReceivedSmsRequest);
            System.out.println("getReceivedSms.result=" + _getReceivedSms__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking apLogOut...");
        APLogOutReq _apLogOut_apLogOutReq = null;
        try {
            APLogOutRsp _apLogOut__return = port.apLogOut(_apLogOut_apLogOutReq);
            System.out.println("apLogOut.result=" + _apLogOut__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notifyMessageReception...");
            com.gistandard.transport.sms.webservice.smsService.NotifyMessageReceptionRequest _notifyMessageReception_notifyMessageReceptionRequest = null;
        try {
            port.notifyMessageReception(_notifyMessageReception_notifyMessageReceptionRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendMessage...");
        SendMessageRequest _sendMessage_sendMessageRequest = null;
        try {
            SendMessageResponse _sendMessage__return = port.sendMessage(_sendMessage_sendMessageRequest);
            System.out.println("sendMessage.result=" + _sendMessage__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking apSvcPerfReport...");
        APSvcPerfReportReq _apSvcPerfReport_apSvcPerfReportReq = null;
        try {
            port.apSvcPerfReport(_apSvcPerfReport_apSvcPerfReportReq);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking apSvcAlarm...");
        AlarmReq _apSvcAlarm_alarmReq = null;
        try {
            AlarmRsp _apSvcAlarm__return = port.apSvcAlarm(_apSvcAlarm_alarmReq);
            System.out.println("apSvcAlarm.result=" + _apSvcAlarm__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking locationError...");
        LocationErrorRequest _locationError_locationErrorRequest = null;
        try {
            port.locationError(_locationError_locationErrorRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notifySmsReception...");
        NotifySmsReceptionRequest _notifySmsReception_notifySmsReceptionRequest = null;
        try {
            port.notifySmsReception(_notifySmsReception_notifySmsReceptionRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notifyUssdEnd...");
        NotifyUssdEndRequest _notifyUssdEnd_notifyUssdEndRequest = null;
        try {
            port.notifyUssdEnd(_notifyUssdEnd_notifyUssdEndRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking handleUssd...");
        HandleUssdRequest _handleUssd_handleUssdRequest = null;
        try {
            HandleUssdResponse _handleUssd__return = port.handleUssd(_handleUssd_handleUssdRequest);
            System.out.println("handleUssd.result=" + _handleUssd__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notifyMessageDeliveryReceipt...");
        com.gistandard.transport.sms.webservice.smsService.NotifyMessageDeliveryReceiptRequest _notifyMessageDeliveryReceipt_notifyMessageDeliveryReceiptRequest = null;
        try {
            port.notifyMessageDeliveryReceipt(_notifyMessageDeliveryReceipt_notifyMessageDeliveryReceiptRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking apStatusRep...");
        APStatusRepReq _apStatusRep_apStatusRepReq = null;
        try {
            APStatusRepRsp _apStatusRep__return = port.apStatusRep(_apStatusRep_apStatusRepReq);
            System.out.println("apStatusRep.result=" + _apStatusRep__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getLocationForGroup...");
        GetLocationForGroupRequest _getLocationForGroup_getLocationForGroupRequest = null;
        try {
            GetLocationForGroupResponse _getLocationForGroup__return = port.getLocationForGroup(_getLocationForGroup_getLocationForGroupRequest);
            System.out.println("getLocationForGroup.result=" + _getLocationForGroup__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking startNotification...");
        StartNotificationRequest _startNotification_startNotificationRequest = null;
        try {
            port.startNotification(_startNotification_startNotificationRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking apRegistration...");
        APRegistrationReq _apRegistration_apRegistrationReq = null;
        try {
            APRegistrationRsp _apRegistration__return = port.apRegistration(_apRegistration_apRegistrationReq);
            System.out.println("apRegistration.result=" + _apRegistration__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking pauseAP...");
        PauseAPReq _pauseAP_pauseAPReq = null;
        try {
            PauseAPRsp _pauseAP__return = port.pauseAP(_pauseAP_pauseAPReq);
            System.out.println("pauseAP.result=" + _pauseAP__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking locationNotification...");
        LocationNotificationRequest _locationNotification_locationNotificationRequest = null;
        try {
            port.locationNotification(_locationNotification_locationNotificationRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking locationEnd...");
        LocationEndRequest _locationEnd_locationEndRequest = null;
        try {
            port.locationEnd(_locationEnd_locationEndRequest);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking startPeriodicNotification...");
        com.gistandard.transport.sms.webservice.smsService.StartPeriodicNotificationRequest _startPeriodicNotification_startPeriodicNotificationRequest = null;
        try {
            com.gistandard.transport.sms.webservice.smsService.StartPeriodicNotificationResponse _startPeriodicNotification__return = port.startPeriodicNotification(_startPeriodicNotification_startPeriodicNotificationRequest);
            System.out.println("startPeriodicNotification.result=" + _startPeriodicNotification__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSmsDeliveryStatus...");
        GetSmsDeliveryStatusRequest _getSmsDeliveryStatus_getSmsDeliveryStatusRequest = null;
        try {
            com.gistandard.transport.sms.webservice.smsService.GetSmsDeliveryStatusResponse _getSmsDeliveryStatus__return = port.getSmsDeliveryStatus(_getSmsDeliveryStatus_getSmsDeliveryStatusRequest);
            System.out.println("getSmsDeliveryStatus.result=" + _getSmsDeliveryStatus__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMessageDeliveryStatus...");
        com.gistandard.transport.sms.webservice.smsService.GetMessageDeliveryStatusRequest _getMessageDeliveryStatus_getMessageDeliveryStatusRequest = null;
        try {
            com.gistandard.transport.sms.webservice.smsService.GetMessageDeliveryStatusResponse _getMessageDeliveryStatus__return = port.getMessageDeliveryStatus(_getMessageDeliveryStatus_getMessageDeliveryStatusRequest);
            System.out.println("getMessageDeliveryStatus.result=" + _getMessageDeliveryStatus__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking makeUssd...");
        MakeUssdRequest _makeUssd_makeUssdRequest = null;
        try {
            MakeUssdResponse _makeUssd__return = port.makeUssd(_makeUssd_makeUssdRequest);
            System.out.println("makeUssd.result=" + _makeUssd__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMessage...");
        GetMessageRequest _getMessage_getMessageRequest = null;
        try {
            GetMessageResponse _getMessage__return = port.getMessage(_getMessage_getMessageRequest);
            System.out.println("getMessage.result=" + _getMessage__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking apSvcPerfCmd...");
        APSvcPerfCmdReq _apSvcPerfCmd_apSvcPerfCmdReq = null;
        try {
            port.apSvcPerfCmd(_apSvcPerfCmd_apSvcPerfCmdReq);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking recoveryAP...");
        RecoveryAPReq _recoveryAP_recoveryAPReq = null;
        try {
            RecoveryAPRsp _recoveryAP__return = port.recoveryAP(_recoveryAP_recoveryAPReq);
            System.out.println("recoveryAP.result=" + _recoveryAP__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking ussdContinue...");
        UssdContinueRequest _ussdContinue_ussdContinueRequest = null;
        try {
            UssdContinueResponse _ussdContinue__return = port.ussdContinue(_ussdContinue_ussdContinueRequest);
            System.out.println("ussdContinue.result=" + _ussdContinue__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        } catch (PolicyException_Exception e) { 
            System.out.println("Expected exception: PolicyException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
