
package com.gistandard.transport.sms.webservice.smsService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-02-05T10:26:14.332+08:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "PolicyException", targetNamespace = "http://www.csapi.org/schema/common/v2_0")
public class PolicyException_Exception extends Exception {
    
    private PolicyException policyException;

    public PolicyException_Exception() {
        super();
    }
    
    public PolicyException_Exception(String message) {
        super(message);
    }
    
    public PolicyException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PolicyException_Exception(String message, PolicyException policyException) {
        super(message);
        this.policyException = policyException;
    }

    public PolicyException_Exception(String message, PolicyException policyException, Throwable cause) {
        super(message, cause);
        this.policyException = policyException;
    }

    public PolicyException getFaultInfo() {
        return this.policyException;
    }
}
