
package com.gistandard.transport.order.webservice.client.merchant.order;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-04-24T15:12:19.958+08:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "Exception", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public Exception getFaultInfo() {
        return this.exception;
    }
}
