package com.gistandard.transport.order.webservice.client.merchant.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-04-24T15:12:19.983+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "MobileRecOrderWebServiceImplService", 
                  wsdlLocation = "http://172.17.1.11:8080/WebService/MobileRecOrderWebService?wsdl",
                  targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/") 
public class MobileRecOrderWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", "MobileRecOrderWebServiceImplService");
    public final static QName MobileRecOrderWebServiceImplPort = new QName("http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", "MobileRecOrderWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.1.11:8080/WebService/MobileRecOrderWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MobileRecOrderWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.17.1.11:8080/WebService/MobileRecOrderWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MobileRecOrderWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MobileRecOrderWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileRecOrderWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MobileRecOrderWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MobileRecOrderWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MobileRecOrderWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MobileRecOrderWebService
     */
    @WebEndpoint(name = "MobileRecOrderWebServiceImplPort")
    public MobileRecOrderWebService getMobileRecOrderWebServiceImplPort() {
        return super.getPort(MobileRecOrderWebServiceImplPort, MobileRecOrderWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileRecOrderWebService
     */
    @WebEndpoint(name = "MobileRecOrderWebServiceImplPort")
    public MobileRecOrderWebService getMobileRecOrderWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MobileRecOrderWebServiceImplPort, MobileRecOrderWebService.class, features);
    }

}
