package com.gistandard.transport.order.webservice.client.merchant.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-04-24T15:12:19.965+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", name = "MobileRecOrderWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface MobileRecOrderWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateRouteEndTran", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateRouteEndTran")
    @WebMethod
    @ResponseWrapper(localName = "updateRouteEndTranResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateRouteEndTranResponse")
    public BaseRequestResult updateRouteEndTran(
            @WebParam(name = "busiNo", targetNamespace = "")
                    String busiNo,
            @WebParam(name = "dispatchId", targetNamespace = "")
                    long dispatchId,
            @WebParam(name = "type", targetNamespace = "")
                    String type,
            @WebParam(name = "createAccountId", targetNamespace = "")
                    Integer createAccountId,
            @WebParam(name = "toAccountId", targetNamespace = "")
                    Integer toAccountId
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CheckRouteExists", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckRouteExists")
    @WebMethod(operationName = "CheckRouteExists")
    @ResponseWrapper(localName = "CheckRouteExistsResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckRouteExistsResponse")
    public BaseRequestResult checkRouteExists(
            @WebParam(name = "arg0", targetNamespace = "")
                    double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    double arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    double arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    double arg3
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectRouteByBusi", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.SelectRouteByBusi")
    @WebMethod
    @ResponseWrapper(localName = "selectRouteByBusiResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.SelectRouteByBusiResponse")
    public String selectRouteByBusi(
            @WebParam(name = "busiNo", targetNamespace = "")
                    String busiNo,
            @WebParam(name = "type", targetNamespace = "")
                    String type,
            @WebParam(name = "wAccountId", targetNamespace = "")
                    Integer wAccountId
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateDispatchStatusById", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateDispatchStatusById")
    @WebMethod
    @ResponseWrapper(localName = "updateDispatchStatusByIdResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateDispatchStatusByIdResponse")
    public BaseRequestResult updateDispatchStatusById(
            @WebParam(name = "arg0", targetNamespace = "")
                    Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "AddRouteEndTran", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.AddRouteEndTran")
    @WebMethod(operationName = "AddRouteEndTran")
    @ResponseWrapper(localName = "AddRouteEndTranResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.AddRouteEndTranResponse")
    public java.util.List<BaseRequestResult> addRouteEndTran(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<DispatchExtend> arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetDispatchDetail", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetDispatchDetail")
    @WebMethod(operationName = "GetDispatchDetail")
    @ResponseWrapper(localName = "GetDispatchDetailResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetDispatchDetailResponse")
    public RequestDetailResult getDispatchDetail(
            @WebParam(name = "arg0", targetNamespace = "")
                    Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SelectOrderCustomerList", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.SelectOrderCustomerList")
    @WebMethod(operationName = "SelectOrderCustomerList")
    @ResponseWrapper(localName = "SelectOrderCustomerListResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.SelectOrderCustomerListResponse")
    public String selectOrderCustomerList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Integer arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "batchMobileToMobile", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchMobileToMobile")
    @WebMethod
    @ResponseWrapper(localName = "batchMobileToMobileResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchMobileToMobileResponse")
    public java.util.List<MobileToMobileDataResult> batchMobileToMobile(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<MobileToMobileParam> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CheckAccountExistRoute", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckAccountExistRoute")
    @WebMethod(operationName = "CheckAccountExistRoute")
    @ResponseWrapper(localName = "CheckAccountExistRouteResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckAccountExistRouteResponse")
    public String checkAccountExistRoute(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "RevokeRouteWPath", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.RevokeRouteWPath")
    @WebMethod(operationName = "RevokeRouteWPath")
    @ResponseWrapper(localName = "RevokeRouteWPathResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.RevokeRouteWPathResponse")
    public BaseRequestResult revokeRouteWPath(
            @WebParam(name = "busiBookNo", targetNamespace = "")
                    String busiBookNo,
            @WebParam(name = "fromAccountId", targetNamespace = "")
                    Integer fromAccountId
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetRouteTimeBySchemaId", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetRouteTimeBySchemaId")
    @WebMethod(operationName = "GetRouteTimeBySchemaId")
    @ResponseWrapper(localName = "GetRouteTimeBySchemaIdResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetRouteTimeBySchemaIdResponse")
    public String getRouteTimeBySchemaId(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<Long> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CheckRouteExistsByAddress", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckRouteExistsByAddress")
    @WebMethod(operationName = "CheckRouteExistsByAddress")
    @ResponseWrapper(localName = "CheckRouteExistsByAddressResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckRouteExistsByAddressResponse")
    public BaseRequestResult checkRouteExistsByAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    double arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    double arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    double arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    String arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    String arg7,
            @WebParam(name = "arg8", targetNamespace = "")
                    String arg8,
            @WebParam(name = "arg9", targetNamespace = "")
                    String arg9
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllWaMiStationByRouteAndExpressCode", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetAllWaMiStationByRouteAndExpressCode")
    @WebMethod
    @ResponseWrapper(localName = "getAllWaMiStationByRouteAndExpressCodeResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetAllWaMiStationByRouteAndExpressCodeResponse")
    public String getAllWaMiStationByRouteAndExpressCode(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "AddRouteWPath", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.AddRouteWPath")
    @WebMethod(operationName = "AddRouteWPath")
    @ResponseWrapper(localName = "AddRouteWPathResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.AddRouteWPathResponse")
    public BaseRequestResult addRouteWPath(
            @WebParam(name = "busiBookNo", targetNamespace = "")
                    String busiBookNo,
            @WebParam(name = "fromAccountId", targetNamespace = "")
                    Integer fromAccountId
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "MobileToHub", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.MobileToHub")
    @WebMethod(operationName = "MobileToHub")
    @ResponseWrapper(localName = "MobileToHubResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.MobileToHubResponse")
    public MobileToHubDataResult mobileToHub(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<OrderObject> arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Integer arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "UpdateOrderRouteSchemaId", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateOrderRouteSchemaId")
    @WebMethod(operationName = "UpdateOrderRouteSchemaId")
    @ResponseWrapper(localName = "UpdateOrderRouteSchemaIdResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateOrderRouteSchemaIdResponse")
    public RouteRequestResult updateOrderRouteSchemaId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Double arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Double arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    Integer arg3
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "batchAddRoutePoPTran", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchAddRoutePoPTran")
    @WebMethod
    @ResponseWrapper(localName = "batchAddRoutePoPTranResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchAddRoutePoPTranResponse")
    public java.util.List<BaseRequestResult> batchAddRoutePoPTran(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<RoutePoPTranParam> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "HubAcceptOrder", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.HubAcceptOrder")
    @WebMethod(operationName = "HubAcceptOrder")
    @ResponseWrapper(localName = "HubAcceptOrderResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.HubAcceptOrderResponse")
    public HubToHubDataResult hubAcceptOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "MStationAcceptOrder", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.MStationAcceptOrder")
    @WebMethod(operationName = "MStationAcceptOrder")
    @ResponseWrapper(localName = "MStationAcceptOrderResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.MStationAcceptOrderResponse")
    public BaseRequestResult mStationAcceptOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CheckCancelDispatch", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckCancelDispatch")
    @WebMethod(operationName = "CheckCancelDispatch")
    @ResponseWrapper(localName = "CheckCancelDispatchResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CheckCancelDispatchResponse")
    public RequestDetailResult checkCancelDispatch(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "RecOrder", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.RecOrder")
    @WebMethod(operationName = "RecOrder")
    @ResponseWrapper(localName = "RecOrderResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.RecOrderResponse")
    public RequestResult recOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Long arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    Integer arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ArrangeOrder", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.ArrangeOrder")
    @WebMethod(operationName = "ArrangeOrder")
    @ResponseWrapper(localName = "ArrangeOrderResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.ArrangeOrderResponse")
    public RequestResult arrangeOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Long arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    Integer arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    Integer arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg5
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "OperateOrder", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.OperateOrder")
    @WebMethod(operationName = "OperateOrder")
    @ResponseWrapper(localName = "OperateOrderResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.OperateOrderResponse")
    public BaseRequestResult operateOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<Long> arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "batchUpdateOrderRouteId", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchUpdateOrderRouteId")
    @WebMethod
    @ResponseWrapper(localName = "batchUpdateOrderRouteIdResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchUpdateOrderRouteIdResponse")
    public BaseRequestResult batchUpdateOrderRouteId(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<String> arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetRouteInfoBySchemaIds", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetRouteInfoBySchemaIds")
    @WebMethod(operationName = "GetRouteInfoBySchemaIds")
    @ResponseWrapper(localName = "GetRouteInfoBySchemaIdsResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetRouteInfoBySchemaIdsResponse")
    public String getRouteInfoBySchemaIds(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<Long> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "UpdateOrderRouteId", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateOrderRouteId")
    @WebMethod(operationName = "UpdateOrderRouteId")
    @ResponseWrapper(localName = "UpdateOrderRouteIdResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.UpdateOrderRouteIdResponse")
    public BaseRequestResult updateOrderRouteId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ApplyCancelHubToHub", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.ApplyCancelHubToHub")
    @WebMethod(operationName = "ApplyCancelHubToHub")
    @ResponseWrapper(localName = "ApplyCancelHubToHubResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.ApplyCancelHubToHubResponse")
    public HubToHubDataResult applyCancelHubToHub(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    long arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "NewMobileToWHub", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.NewMobileToWHub")
    @WebMethod(operationName = "NewMobileToWHub")
    @ResponseWrapper(localName = "NewMobileToWHubResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.NewMobileToWHubResponse")
    public HubToHubDataResult newMobileToWHub(
            @WebParam(name = "arg0", targetNamespace = "")
                    NewMobileToWHubParam arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "DeleteHubToHub", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.DeleteHubToHub")
    @WebMethod(operationName = "DeleteHubToHub")
    @ResponseWrapper(localName = "DeleteHubToHubResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.DeleteHubToHubResponse")
    public HubToHubDataResult deleteHubToHub(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    long arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "MobileToMobile", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.MobileToMobile")
    @WebMethod(operationName = "MobileToMobile")
    @ResponseWrapper(localName = "MobileToMobileResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.MobileToMobileResponse")
    public MobileToMobileDataResult mobileToMobile(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Integer arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    Integer arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    Integer arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    String arg6
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "batchMStationAcceptOrder", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchMStationAcceptOrder")
    @WebMethod
    @ResponseWrapper(localName = "batchMStationAcceptOrderResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchMStationAcceptOrderResponse")
    public java.util.List<BaseRequestResult> batchMStationAcceptOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<MsAcceptOrderParam> arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CancelMobileDispatch", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CancelMobileDispatch")
    @WebMethod(operationName = "CancelMobileDispatch")
    @ResponseWrapper(localName = "CancelMobileDispatchResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.CancelMobileDispatchResponse")
    public RequestDetailResult cancelMobileDispatch(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ConfirmCancelDispatch", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.ConfirmCancelDispatch")
    @WebMethod(operationName = "ConfirmCancelDispatch")
    @ResponseWrapper(localName = "ConfirmCancelDispatchResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.ConfirmCancelDispatchResponse")
    public RequestDetailResult confirmCancelDispatch(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    boolean arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "AddRoutePoPTran", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.AddRoutePoPTran")
    @WebMethod(operationName = "AddRoutePoPTran")
    @ResponseWrapper(localName = "AddRoutePoPTranResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.AddRoutePoPTranResponse")
    public BaseRequestResult addRoutePoPTran(
            @WebParam(name = "busiBookNo", targetNamespace = "")
                    String busiBookNo,
            @WebParam(name = "fromAccountId", targetNamespace = "")
                    Integer fromAccountId
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "batchCheckRouteExists", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchCheckRouteExists")
    @WebMethod
    @ResponseWrapper(localName = "batchCheckRouteExistsResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.BatchCheckRouteExistsResponse")
    public BaseRequestResult batchCheckRouteExists(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<Locitude> arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetRouteInfoBySchemaId", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetRouteInfoBySchemaId")
    @WebMethod(operationName = "GetRouteInfoBySchemaId")
    @ResponseWrapper(localName = "GetRouteInfoBySchemaIdResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetRouteInfoBySchemaIdResponse")
    public String getRouteInfoBySchemaId(
            @WebParam(name = "arg0", targetNamespace = "")
                    Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "HubToHub", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.HubToHub")
    @WebMethod(operationName = "HubToHub")
    @ResponseWrapper(localName = "HubToHubResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.HubToHubResponse")
    public HubToHubDataResult hubToHub(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<DispatchExtend> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllMiMovingByMiStopId", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetAllMiMovingByMiStopId")
    @WebMethod
    @ResponseWrapper(localName = "getAllMiMovingByMiStopIdResponse", targetNamespace = "http://webService.mobileRecOrder.dispatch.transport.gistandard.com/", className = "com.gistandard.transport.order.webservice.client.merchant.order.GetAllMiMovingByMiStopIdResponse")
    public String getAllMiMovingByMiStopId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );
}
