
package com.gistandard.transport.system.webservice.client.gps;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-09-06T14:28:33.171+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class PnWebService_PnWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.manage.gps.com/", "PnWebServiceService");

    private PnWebService_PnWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PnWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PnWebServiceService ss = new PnWebServiceService(wsdlURL, SERVICE_NAME);
        PnWebService port = ss.getPnWebServicePort();  
        
        {
        System.out.println("Invoking getAllGiBizOrderCount...");
        double _getAllGiBizOrderCount_lng = 0.0;
        double _getAllGiBizOrderCount_lat = 0.0;
        String _getAllGiBizOrderCount_sourceProvince = "";
        String _getAllGiBizOrderCount_sourceCity = "";
        String _getAllGiBizOrderCount_sourceDistrict = "";
        String _getAllGiBizOrderCount_jsonAllRoleCode = "";
        long _getAllGiBizOrderCount__return = port.getAllGiBizOrderCount(_getAllGiBizOrderCount_lng, _getAllGiBizOrderCount_lat, _getAllGiBizOrderCount_sourceProvince, _getAllGiBizOrderCount_sourceCity, _getAllGiBizOrderCount_sourceDistrict, _getAllGiBizOrderCount_jsonAllRoleCode);
        System.out.println("getAllGiBizOrderCount.result=" + _getAllGiBizOrderCount__return);


        }
        {
        System.out.println("Invoking getIsOnlineGpsByUserCode...");
        String _getIsOnlineGpsByUserCode_userCode = "";
        String _getIsOnlineGpsByUserCode_appTag = "";
        String _getIsOnlineGpsByUserCode_jsonAllRoleCode = "";
        String _getIsOnlineGpsByUserCode__return = port.getIsOnlineGpsByUserCode(_getIsOnlineGpsByUserCode_userCode, _getIsOnlineGpsByUserCode_appTag, _getIsOnlineGpsByUserCode_jsonAllRoleCode);
        System.out.println("getIsOnlineGpsByUserCode.result=" + _getIsOnlineGpsByUserCode__return);


        }
        {
        System.out.println("Invoking getAllGiAdminConcernPcdByUserCode...");
        String _getAllGiAdminConcernPcdByUserCode_userCode = "";
        GiAdminResult _getAllGiAdminConcernPcdByUserCode__return = port.getAllGiAdminConcernPcdByUserCode(_getAllGiAdminConcernPcdByUserCode_userCode);
        System.out.println("getAllGiAdminConcernPcdByUserCode.result=" + _getAllGiAdminConcernPcdByUserCode__return);


        }
        {
        System.out.println("Invoking getAllGicbFenceGeo...");
        String _getAllGicbFenceGeo__return = port.getAllGicbFenceGeo();
        System.out.println("getAllGicbFenceGeo.result=" + _getAllGicbFenceGeo__return);


        }
        {
        System.out.println("Invoking getLastMlOrderTraceByBusiNo...");
        String _getLastMlOrderTraceByBusiNo_busiNo = "";
        MlOrderTrace _getLastMlOrderTraceByBusiNo__return = port.getLastMlOrderTraceByBusiNo(_getLastMlOrderTraceByBusiNo_busiNo);
        System.out.println("getLastMlOrderTraceByBusiNo.result=" + _getLastMlOrderTraceByBusiNo__return);


        }
        {
        System.out.println("Invoking getAllGiPositionUserByAddress...");
        double _getAllGiPositionUserByAddress_lng = 0.0;
        double _getAllGiPositionUserByAddress_lat = 0.0;
        String _getAllGiPositionUserByAddress_appTag = "";
        String _getAllGiPositionUserByAddress_jsonAllRoleCode = "";
        String _getAllGiPositionUserByAddress_jsonAllStationCandidate = "";
        String _getAllGiPositionUserByAddress__return = port.getAllGiPositionUserByAddress(_getAllGiPositionUserByAddress_lng, _getAllGiPositionUserByAddress_lat, _getAllGiPositionUserByAddress_appTag, _getAllGiPositionUserByAddress_jsonAllRoleCode, _getAllGiPositionUserByAddress_jsonAllStationCandidate);
        System.out.println("getAllGiPositionUserByAddress.result=" + _getAllGiPositionUserByAddress__return);


        }
        {
        System.out.println("Invoking getAllGicbFenceGeoByCityName...");
        String _getAllGicbFenceGeoByCityName_cityName = "";
        String _getAllGicbFenceGeoByCityName_districtName = "";
        java.util.List<GicbFenceGeo> _getAllGicbFenceGeoByCityName__return = port.getAllGicbFenceGeoByCityName(_getAllGicbFenceGeoByCityName_cityName, _getAllGicbFenceGeoByCityName_districtName);
        System.out.println("getAllGicbFenceGeoByCityName.result=" + _getAllGicbFenceGeoByCityName__return);


        }
        {
        System.out.println("Invoking getAllLocExpressByLanLatRadWithHifu...");
        double _getAllLocExpressByLanLatRadWithHifu_longitude = 0.0;
        double _getAllLocExpressByLanLatRadWithHifu_latitude = 0.0;
        double _getAllLocExpressByLanLatRadWithHifu_radius = 0.0;
        boolean _getAllLocExpressByLanLatRadWithHifu_isHifu = false;
        String _getAllLocExpressByLanLatRadWithHifu__return = port.getAllLocExpressByLanLatRadWithHifu(_getAllLocExpressByLanLatRadWithHifu_longitude, _getAllLocExpressByLanLatRadWithHifu_latitude, _getAllLocExpressByLanLatRadWithHifu_radius, _getAllLocExpressByLanLatRadWithHifu_isHifu);
        System.out.println("getAllLocExpressByLanLatRadWithHifu.result=" + _getAllLocExpressByLanLatRadWithHifu__return);


        }
        {
        System.out.println("Invoking pushAllGipnOrder3...");
        String _pushAllGipnOrder3_jsonAllGipnOrder = "";
        String _pushAllGipnOrder3__return = port.pushAllGipnOrder3(_pushAllGipnOrder3_jsonAllGipnOrder);
        System.out.println("pushAllGipnOrder3.result=" + _pushAllGipnOrder3__return);


        }
        {
        System.out.println("Invoking getAllGiPositionUserByLanLatRadApptagModulesRoles...");
        double _getAllGiPositionUserByLanLatRadApptagModulesRoles_longitude = 0.0;
        double _getAllGiPositionUserByLanLatRadApptagModulesRoles_latitude = 0.0;
        double _getAllGiPositionUserByLanLatRadApptagModulesRoles_radius = 0.0;
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles_appTag = "";
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles_moduleCode = "";
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles_csvRoleCode = "";
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles__return = port.getAllGiPositionUserByLanLatRadApptagModulesRoles(_getAllGiPositionUserByLanLatRadApptagModulesRoles_longitude, _getAllGiPositionUserByLanLatRadApptagModulesRoles_latitude, _getAllGiPositionUserByLanLatRadApptagModulesRoles_radius, _getAllGiPositionUserByLanLatRadApptagModulesRoles_appTag, _getAllGiPositionUserByLanLatRadApptagModulesRoles_moduleCode, _getAllGiPositionUserByLanLatRadApptagModulesRoles_csvRoleCode);
        System.out.println("getAllGiPositionUserByLanLatRadApptagModulesRoles.result=" + _getAllGiPositionUserByLanLatRadApptagModulesRoles__return);


        }
        {
        System.out.println("Invoking getAllGiBizOrderPaging...");
        double _getAllGiBizOrderPaging_lng = 0.0;
        double _getAllGiBizOrderPaging_lat = 0.0;
        String _getAllGiBizOrderPaging_sourceProvince = "";
        String _getAllGiBizOrderPaging_sourceCity = "";
        String _getAllGiBizOrderPaging_sourceDistrict = "";
        String _getAllGiBizOrderPaging_jsonAllRoleCode = "";
        int _getAllGiBizOrderPaging_pageNum = 0;
        int _getAllGiBizOrderPaging_pageSize = 0;
        String _getAllGiBizOrderPaging__return = port.getAllGiBizOrderPaging(_getAllGiBizOrderPaging_lng, _getAllGiBizOrderPaging_lat, _getAllGiBizOrderPaging_sourceProvince, _getAllGiBizOrderPaging_sourceCity, _getAllGiBizOrderPaging_sourceDistrict, _getAllGiBizOrderPaging_jsonAllRoleCode, _getAllGiBizOrderPaging_pageNum, _getAllGiBizOrderPaging_pageSize);
        System.out.println("getAllGiBizOrderPaging.result=" + _getAllGiBizOrderPaging__return);


        }
        {
        System.out.println("Invoking getAllRptOrderTraceWithTimeControlByDateFromTo...");
        String _getAllRptOrderTraceWithTimeControlByDateFromTo_cityName = "";
        String _getAllRptOrderTraceWithTimeControlByDateFromTo_districtName = "";
        String _getAllRptOrderTraceWithTimeControlByDateFromTo_gicbFenceName = "";
        java.util.Date _getAllRptOrderTraceWithTimeControlByDateFromTo_busiDateFrom = new java.util.Date();
        java.util.Date _getAllRptOrderTraceWithTimeControlByDateFromTo_busiDateTo = new java.util.Date();
        String _getAllRptOrderTraceWithTimeControlByDateFromTo_productType = "";
        try {
            java.util.List<RptOrderTrace> _getAllRptOrderTraceWithTimeControlByDateFromTo__return = port.getAllRptOrderTraceWithTimeControlByDateFromTo(_getAllRptOrderTraceWithTimeControlByDateFromTo_cityName, _getAllRptOrderTraceWithTimeControlByDateFromTo_districtName, _getAllRptOrderTraceWithTimeControlByDateFromTo_gicbFenceName, _getAllRptOrderTraceWithTimeControlByDateFromTo_busiDateFrom, _getAllRptOrderTraceWithTimeControlByDateFromTo_busiDateTo, _getAllRptOrderTraceWithTimeControlByDateFromTo_productType);
            System.out.println("getAllRptOrderTraceWithTimeControlByDateFromTo.result=" + _getAllRptOrderTraceWithTimeControlByDateFromTo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllGiBizOrderByAllDocNo...");
        String _getAllGiBizOrderByAllDocNo_jsonAllDocNo = "";
        String _getAllGiBizOrderByAllDocNo__return = port.getAllGiBizOrderByAllDocNo(_getAllGiBizOrderByAllDocNo_jsonAllDocNo);
        System.out.println("getAllGiBizOrderByAllDocNo.result=" + _getAllGiBizOrderByAllDocNo__return);


        }
        {
        System.out.println("Invoking getAllLocExpressByLanLatRad...");
        double _getAllLocExpressByLanLatRad_longitude = 0.0;
        double _getAllLocExpressByLanLatRad_latitude = 0.0;
        double _getAllLocExpressByLanLatRad_radius = 0.0;
        String _getAllLocExpressByLanLatRad__return = port.getAllLocExpressByLanLatRad(_getAllLocExpressByLanLatRad_longitude, _getAllLocExpressByLanLatRad_latitude, _getAllLocExpressByLanLatRad_radius);
        System.out.println("getAllLocExpressByLanLatRad.result=" + _getAllLocExpressByLanLatRad__return);


        }
        {
        System.out.println("Invoking getShortestMiStation...");
        String _getShortestMiStation_waStationCode = "";
        double _getShortestMiStation_lngOfAddress = 0.0;
        double _getShortestMiStation_latOfAddress = 0.0;
        String _getShortestMiStation__return = port.getShortestMiStation(_getShortestMiStation_waStationCode, _getShortestMiStation_lngOfAddress, _getShortestMiStation_latOfAddress);
        System.out.println("getShortestMiStation.result=" + _getShortestMiStation__return);


        }
        {
        System.out.println("Invoking getAllGiPositionStationMiniByWaStationCode...");
        String _getAllGiPositionStationMiniByWaStationCode_waStationCode = "";
        String _getAllGiPositionStationMiniByWaStationCode__return = port.getAllGiPositionStationMiniByWaStationCode(_getAllGiPositionStationMiniByWaStationCode_waStationCode);
        System.out.println("getAllGiPositionStationMiniByWaStationCode.result=" + _getAllGiPositionStationMiniByWaStationCode__return);


        }
        {
        System.out.println("Invoking resyncGiPositionStation...");
        String _resyncGiPositionStation_jsonGiPositionStation = "";
        String _resyncGiPositionStation_operation = "";
        String _resyncGiPositionStation__return = port.resyncGiPositionStation(_resyncGiPositionStation_jsonGiPositionStation, _resyncGiPositionStation_operation);
        System.out.println("resyncGiPositionStation.result=" + _resyncGiPositionStation__return);


        }
        {
        System.out.println("Invoking getGiLocationByUserCode...");
        String _getGiLocationByUserCode_userCode = "";
        String _getGiLocationByUserCode__return = port.getGiLocationByUserCode(_getGiLocationByUserCode_userCode);
        System.out.println("getGiLocationByUserCode.result=" + _getGiLocationByUserCode__return);


        }
        {
        System.out.println("Invoking getAllGiPositionStationByRouteAndUser...");
        String _getAllGiPositionStationByRouteAndUser_jsonAllStationCode = "";
        String _getAllGiPositionStationByRouteAndUser_userCode = "";
        String _getAllGiPositionStationByRouteAndUser_userRole = "";
        String _getAllGiPositionStationByRouteAndUser_appTag = "";
        String _getAllGiPositionStationByRouteAndUser__return = port.getAllGiPositionStationByRouteAndUser(_getAllGiPositionStationByRouteAndUser_jsonAllStationCode, _getAllGiPositionStationByRouteAndUser_userCode, _getAllGiPositionStationByRouteAndUser_userRole, _getAllGiPositionStationByRouteAndUser_appTag);
        System.out.println("getAllGiPositionStationByRouteAndUser.result=" + _getAllGiPositionStationByRouteAndUser__return);


        }
        {
        System.out.println("Invoking getDistanceRunedByTruck...");
        String _getDistanceRunedByTruck_truckCode = "";
        java.util.Date _getDistanceRunedByTruck_dateBegin = new java.util.Date();
        java.util.Date _getDistanceRunedByTruck_dateEnd = new java.util.Date();
        double _getDistanceRunedByTruck__return = port.getDistanceRunedByTruck(_getDistanceRunedByTruck_truckCode, _getDistanceRunedByTruck_dateBegin, _getDistanceRunedByTruck_dateEnd);
        System.out.println("getDistanceRunedByTruck.result=" + _getDistanceRunedByTruck__return);


        }
        {
        System.out.println("Invoking getAllRptOrderTraceWithTimeControl...");
        String _getAllRptOrderTraceWithTimeControl_cityName = "";
        String _getAllRptOrderTraceWithTimeControl_districtName = "";
        String _getAllRptOrderTraceWithTimeControl_gicbFenceName = "";
        java.util.Date _getAllRptOrderTraceWithTimeControl_busiDate = new java.util.Date();
        String _getAllRptOrderTraceWithTimeControl_productType = "";
        try {
            java.util.List<RptOrderTrace> _getAllRptOrderTraceWithTimeControl__return = port.getAllRptOrderTraceWithTimeControl(_getAllRptOrderTraceWithTimeControl_cityName, _getAllRptOrderTraceWithTimeControl_districtName, _getAllRptOrderTraceWithTimeControl_gicbFenceName, _getAllRptOrderTraceWithTimeControl_busiDate, _getAllRptOrderTraceWithTimeControl_productType);
            System.out.println("getAllRptOrderTraceWithTimeControl.result=" + _getAllRptOrderTraceWithTimeControl__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getGpsToken...");
        String _getGpsToken_code = "";
        String _getGpsToken__return = port.getGpsToken(_getGpsToken_code);
        System.out.println("getGpsToken.result=" + _getGpsToken__return);


        }
        {
        System.out.println("Invoking getAllGiPositionUserForSearch...");
        double _getAllGiPositionUserForSearch_lng = 0.0;
        double _getAllGiPositionUserForSearch_lat = 0.0;
        String _getAllGiPositionUserForSearch_searchTxt = "";
        String _getAllGiPositionUserForSearch_jsonAllRoleCode = "";
        String _getAllGiPositionUserForSearch__return = port.getAllGiPositionUserForSearch(_getAllGiPositionUserForSearch_lng, _getAllGiPositionUserForSearch_lat, _getAllGiPositionUserForSearch_searchTxt, _getAllGiPositionUserForSearch_jsonAllRoleCode);
        System.out.println("getAllGiPositionUserForSearch.result=" + _getAllGiPositionUserForSearch__return);


        }
        {
        System.out.println("Invoking getAllGiBizOrderBizModeCount...");
        double _getAllGiBizOrderBizModeCount_lng = 0.0;
        double _getAllGiBizOrderBizModeCount_lat = 0.0;
        String _getAllGiBizOrderBizModeCount_sourceProvince = "";
        String _getAllGiBizOrderBizModeCount_sourceCity = "";
        String _getAllGiBizOrderBizModeCount_sourceDistrict = "";
        String _getAllGiBizOrderBizModeCount_jsonAllRoleCode = "";
        int _getAllGiBizOrderBizModeCount_bizMode = 0;
        long _getAllGiBizOrderBizModeCount__return = port.getAllGiBizOrderBizModeCount(_getAllGiBizOrderBizModeCount_lng, _getAllGiBizOrderBizModeCount_lat, _getAllGiBizOrderBizModeCount_sourceProvince, _getAllGiBizOrderBizModeCount_sourceCity, _getAllGiBizOrderBizModeCount_sourceDistrict, _getAllGiBizOrderBizModeCount_jsonAllRoleCode, _getAllGiBizOrderBizModeCount_bizMode);
        System.out.println("getAllGiBizOrderBizModeCount.result=" + _getAllGiBizOrderBizModeCount__return);


        }
        {
        System.out.println("Invoking getAllGiPositionUserForSearch2...");
        double _getAllGiPositionUserForSearch2_lng = 0.0;
        double _getAllGiPositionUserForSearch2_lat = 0.0;
        String _getAllGiPositionUserForSearch2_province = "";
        String _getAllGiPositionUserForSearch2_city = "";
        String _getAllGiPositionUserForSearch2_district = "";
        String _getAllGiPositionUserForSearch2_searchTxt = "";
        String _getAllGiPositionUserForSearch2_jsonAllRoleCode = "";
        String _getAllGiPositionUserForSearch2__return = port.getAllGiPositionUserForSearch2(_getAllGiPositionUserForSearch2_lng, _getAllGiPositionUserForSearch2_lat, _getAllGiPositionUserForSearch2_province, _getAllGiPositionUserForSearch2_city, _getAllGiPositionUserForSearch2_district, _getAllGiPositionUserForSearch2_searchTxt, _getAllGiPositionUserForSearch2_jsonAllRoleCode);
        System.out.println("getAllGiPositionUserForSearch2.result=" + _getAllGiPositionUserForSearch2__return);


        }
        {
        System.out.println("Invoking getAllGiLocationByAllMapOfCodeApptagTime...");
        String _getAllGiLocationByAllMapOfCodeApptagTime_jsonAllMapOfCodeApptagTime = "";
        String _getAllGiLocationByAllMapOfCodeApptagTime__return = port.getAllGiLocationByAllMapOfCodeApptagTime(_getAllGiLocationByAllMapOfCodeApptagTime_jsonAllMapOfCodeApptagTime);
        System.out.println("getAllGiLocationByAllMapOfCodeApptagTime.result=" + _getAllGiLocationByAllMapOfCodeApptagTime__return);


        }
        {
        System.out.println("Invoking getAllGiLocationCurrentByUserCodes...");
        String _getAllGiLocationCurrentByUserCodes_userCodes = "";
        String _getAllGiLocationCurrentByUserCodes__return = port.getAllGiLocationCurrentByUserCodes(_getAllGiLocationCurrentByUserCodes_userCodes);
        System.out.println("getAllGiLocationCurrentByUserCodes.result=" + _getAllGiLocationCurrentByUserCodes__return);


        }
        {
        System.out.println("Invoking getAllWaMiStationByRouteAndExpressCode...");
        String _getAllWaMiStationByRouteAndExpressCode_jsonAllStationCode = "";
        String _getAllWaMiStationByRouteAndExpressCode_userCode = "";
        String _getAllWaMiStationByRouteAndExpressCode_appTag = "";
        String _getAllWaMiStationByRouteAndExpressCode__return = port.getAllWaMiStationByRouteAndExpressCode(_getAllWaMiStationByRouteAndExpressCode_jsonAllStationCode, _getAllWaMiStationByRouteAndExpressCode_userCode, _getAllWaMiStationByRouteAndExpressCode_appTag);
        System.out.println("getAllWaMiStationByRouteAndExpressCode.result=" + _getAllWaMiStationByRouteAndExpressCode__return);


        }
        {
        System.out.println("Invoking getMiStationWithMiRouteStopByCode...");
        String _getMiStationWithMiRouteStopByCode_userCode = "";
        String _getMiStationWithMiRouteStopByCode__return = port.getMiStationWithMiRouteStopByCode(_getMiStationWithMiRouteStopByCode_userCode);
        System.out.println("getMiStationWithMiRouteStopByCode.result=" + _getMiStationWithMiRouteStopByCode__return);


        }
        {
        System.out.println("Invoking getGicbFenceGeoByLngLat...");
        double _getGicbFenceGeoByLngLat_lng = 0.0;
        double _getGicbFenceGeoByLngLat_lat = 0.0;
        String _getGicbFenceGeoByLngLat__return = port.getGicbFenceGeoByLngLat(_getGicbFenceGeoByLngLat_lng, _getGicbFenceGeoByLngLat_lat);
        System.out.println("getGicbFenceGeoByLngLat.result=" + _getGicbFenceGeoByLngLat__return);


        }
        {
        System.out.println("Invoking getMiStationNearestInFence...");
        double _getMiStationNearestInFence_lng = 0.0;
        double _getMiStationNearestInFence_lat = 0.0;
        GiPositionAcct _getMiStationNearestInFence__return = port.getMiStationNearestInFence(_getMiStationNearestInFence_lng, _getMiStationNearestInFence_lat);
        System.out.println("getMiStationNearestInFence.result=" + _getMiStationNearestInFence__return);


        }
        {
        System.out.println("Invoking getAllGiPositionUserByLanLatRadApptagModulesRoles3...");
        double _getAllGiPositionUserByLanLatRadApptagModulesRoles3_longitude = 0.0;
        double _getAllGiPositionUserByLanLatRadApptagModulesRoles3_latitude = 0.0;
        double _getAllGiPositionUserByLanLatRadApptagModulesRoles3_radius = 0.0;
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles3_appTag = "";
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles3_csvModuleCode = "";
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles3_csvRoleCode = "";
        String _getAllGiPositionUserByLanLatRadApptagModulesRoles3__return = port.getAllGiPositionUserByLanLatRadApptagModulesRoles3(_getAllGiPositionUserByLanLatRadApptagModulesRoles3_longitude, _getAllGiPositionUserByLanLatRadApptagModulesRoles3_latitude, _getAllGiPositionUserByLanLatRadApptagModulesRoles3_radius, _getAllGiPositionUserByLanLatRadApptagModulesRoles3_appTag, _getAllGiPositionUserByLanLatRadApptagModulesRoles3_csvModuleCode, _getAllGiPositionUserByLanLatRadApptagModulesRoles3_csvRoleCode);
        System.out.println("getAllGiPositionUserByLanLatRadApptagModulesRoles3.result=" + _getAllGiPositionUserByLanLatRadApptagModulesRoles3__return);


        }
        {
        System.out.println("Invoking getShortestRoute...");
        double _getShortestRoute_lngFrom = 0.0;
        double _getShortestRoute_latFrom = 0.0;
        double _getShortestRoute_lngTo = 0.0;
        double _getShortestRoute_latTo = 0.0;
        String _getShortestRoute_jsonAllBizRoute = "";
        Integer _getShortestRoute__return = port.getShortestRoute(_getShortestRoute_lngFrom, _getShortestRoute_latFrom, _getShortestRoute_lngTo, _getShortestRoute_latTo, _getShortestRoute_jsonAllBizRoute);
        System.out.println("getShortestRoute.result=" + _getShortestRoute__return);


        }
        {
        System.out.println("Invoking getAllGiBizOrderForCluster...");
        double _getAllGiBizOrderForCluster_lng = 0.0;
        double _getAllGiBizOrderForCluster_lat = 0.0;
        String _getAllGiBizOrderForCluster_jsonAllRoleCode = "";
        boolean _getAllGiBizOrderForCluster_isOnlyMyFence = false;
        double _getAllGiBizOrderForCluster_radius = 0.0;
        String _getAllGiBizOrderForCluster__return = port.getAllGiBizOrderForCluster(_getAllGiBizOrderForCluster_lng, _getAllGiBizOrderForCluster_lat, _getAllGiBizOrderForCluster_jsonAllRoleCode, _getAllGiBizOrderForCluster_isOnlyMyFence, _getAllGiBizOrderForCluster_radius);
        System.out.println("getAllGiBizOrderForCluster.result=" + _getAllGiBizOrderForCluster__return);


        }
        {
        System.out.println("Invoking getGiRoutePlanById...");
        String _getGiRoutePlanById_routePlanId = "";
        String _getGiRoutePlanById__return = port.getGiRoutePlanById(_getGiRoutePlanById_routePlanId);
        System.out.println("getGiRoutePlanById.result=" + _getGiRoutePlanById__return);


        }
        {
        System.out.println("Invoking getGiPositionAcctByUserCode...");
        String _getGiPositionAcctByUserCode_userCode = "";
        String _getGiPositionAcctByUserCode__return = port.getGiPositionAcctByUserCode(_getGiPositionAcctByUserCode_userCode);
        System.out.println("getGiPositionAcctByUserCode.result=" + _getGiPositionAcctByUserCode__return);


        }
        {
        System.out.println("Invoking getAllExpressDriverByLanLatRad...");
        double _getAllExpressDriverByLanLatRad_longitude = 0.0;
        double _getAllExpressDriverByLanLatRad_latitude = 0.0;
        double _getAllExpressDriverByLanLatRad_radius = 0.0;
        boolean _getAllExpressDriverByLanLatRad_isHifu = false;
        String _getAllExpressDriverByLanLatRad_jsonAllRoleCode = "";
        String _getAllExpressDriverByLanLatRad__return = port.getAllExpressDriverByLanLatRad(_getAllExpressDriverByLanLatRad_longitude, _getAllExpressDriverByLanLatRad_latitude, _getAllExpressDriverByLanLatRad_radius, _getAllExpressDriverByLanLatRad_isHifu, _getAllExpressDriverByLanLatRad_jsonAllRoleCode);
        System.out.println("getAllExpressDriverByLanLatRad.result=" + _getAllExpressDriverByLanLatRad__return);


        }
        {
        System.out.println("Invoking getAllGiBizOrderAdhocPaging...");
        String _getAllGiBizOrderAdhocPaging_sourceProvince = "";
        String _getAllGiBizOrderAdhocPaging_sourceCity = "";
        String _getAllGiBizOrderAdhocPaging_sourceDistrict = "";
        String _getAllGiBizOrderAdhocPaging_destProvince = "";
        String _getAllGiBizOrderAdhocPaging_destCity = "";
        String _getAllGiBizOrderAdhocPaging_destDistrict = "";
        String _getAllGiBizOrderAdhocPaging_docNo = "";
        String _getAllGiBizOrderAdhocPaging_roleCode = "";
        java.util.Date _getAllGiBizOrderAdhocPaging_tsCreatedFrom = new java.util.Date();
        java.util.Date _getAllGiBizOrderAdhocPaging_tsCreatedTo = new java.util.Date();
        int _getAllGiBizOrderAdhocPaging_pageNum = 0;
        int _getAllGiBizOrderAdhocPaging_pageSize = 0;
        String _getAllGiBizOrderAdhocPaging__return = port.getAllGiBizOrderAdhocPaging(_getAllGiBizOrderAdhocPaging_sourceProvince, _getAllGiBizOrderAdhocPaging_sourceCity, _getAllGiBizOrderAdhocPaging_sourceDistrict, _getAllGiBizOrderAdhocPaging_destProvince, _getAllGiBizOrderAdhocPaging_destCity, _getAllGiBizOrderAdhocPaging_destDistrict, _getAllGiBizOrderAdhocPaging_docNo, _getAllGiBizOrderAdhocPaging_roleCode, _getAllGiBizOrderAdhocPaging_tsCreatedFrom, _getAllGiBizOrderAdhocPaging_tsCreatedTo, _getAllGiBizOrderAdhocPaging_pageNum, _getAllGiBizOrderAdhocPaging_pageSize);
        System.out.println("getAllGiBizOrderAdhocPaging.result=" + _getAllGiBizOrderAdhocPaging__return);


        }
        {
        System.out.println("Invoking greeting...");
        String _greeting_userName = "";
        String _greeting__return = port.greeting(_greeting_userName);
        System.out.println("greeting.result=" + _greeting__return);


        }
        {
        System.out.println("Invoking getAllMiStationByStopId...");
        String _getAllMiStationByStopId_idGiMiRoutePlan = "";
        String _getAllMiStationByStopId_miStopId = "";
        String _getAllMiStationByStopId__return = port.getAllMiStationByStopId(_getAllMiStationByStopId_idGiMiRoutePlan, _getAllMiStationByStopId_miStopId);
        System.out.println("getAllMiStationByStopId.result=" + _getAllMiStationByStopId__return);


        }
        {
        System.out.println("Invoking getAllGiBizOrderBizModePaging...");
        double _getAllGiBizOrderBizModePaging_lng = 0.0;
        double _getAllGiBizOrderBizModePaging_lat = 0.0;
        String _getAllGiBizOrderBizModePaging_sourceProvince = "";
        String _getAllGiBizOrderBizModePaging_sourceCity = "";
        String _getAllGiBizOrderBizModePaging_sourceDistrict = "";
        String _getAllGiBizOrderBizModePaging_jsonAllRoleCode = "";
        int _getAllGiBizOrderBizModePaging_bizMode = 0;
        int _getAllGiBizOrderBizModePaging_pageNum = 0;
        int _getAllGiBizOrderBizModePaging_pageSize = 0;
        String _getAllGiBizOrderBizModePaging__return = port.getAllGiBizOrderBizModePaging(_getAllGiBizOrderBizModePaging_lng, _getAllGiBizOrderBizModePaging_lat, _getAllGiBizOrderBizModePaging_sourceProvince, _getAllGiBizOrderBizModePaging_sourceCity, _getAllGiBizOrderBizModePaging_sourceDistrict, _getAllGiBizOrderBizModePaging_jsonAllRoleCode, _getAllGiBizOrderBizModePaging_bizMode, _getAllGiBizOrderBizModePaging_pageNum, _getAllGiBizOrderBizModePaging_pageSize);
        System.out.println("getAllGiBizOrderBizModePaging.result=" + _getAllGiBizOrderBizModePaging__return);


        }
        {
        System.out.println("Invoking getIsInSameFence...");
        double _getIsInSameFence_lng1 = 0.0;
        double _getIsInSameFence_lat1 = 0.0;
        double _getIsInSameFence_lng2 = 0.0;
        double _getIsInSameFence_lat2 = 0.0;
        boolean _getIsInSameFence__return = port.getIsInSameFence(_getIsInSameFence_lng1, _getIsInSameFence_lat1, _getIsInSameFence_lng2, _getIsInSameFence_lat2);
        System.out.println("getIsInSameFence.result=" + _getIsInSameFence__return);


        }
        {
        System.out.println("Invoking getGiPositionUserOfMovingWaByUserCode...");
        String _getGiPositionUserOfMovingWaByUserCode_userCode = "";
        String _getGiPositionUserOfMovingWaByUserCode__return = port.getGiPositionUserOfMovingWaByUserCode(_getGiPositionUserOfMovingWaByUserCode_userCode);
        System.out.println("getGiPositionUserOfMovingWaByUserCode.result=" + _getGiPositionUserOfMovingWaByUserCode__return);


        }
        {
        System.out.println("Invoking uploadSomethingTest...");
        String _uploadSomethingTest_text = "";
        String _uploadSomethingTest__return = port.uploadSomethingTest(_uploadSomethingTest_text);
        System.out.println("uploadSomethingTest.result=" + _uploadSomethingTest__return);


        }
        {
        System.out.println("Invoking getAllLocFixedMiByLanLatRadWithHifu...");
        double _getAllLocFixedMiByLanLatRadWithHifu_longitude = 0.0;
        double _getAllLocFixedMiByLanLatRadWithHifu_latitude = 0.0;
        double _getAllLocFixedMiByLanLatRadWithHifu_radius = 0.0;
        boolean _getAllLocFixedMiByLanLatRadWithHifu_isHifu = false;
        String _getAllLocFixedMiByLanLatRadWithHifu__return = port.getAllLocFixedMiByLanLatRadWithHifu(_getAllLocFixedMiByLanLatRadWithHifu_longitude, _getAllLocFixedMiByLanLatRadWithHifu_latitude, _getAllLocFixedMiByLanLatRadWithHifu_radius, _getAllLocFixedMiByLanLatRadWithHifu_isHifu);
        System.out.println("getAllLocFixedMiByLanLatRadWithHifu.result=" + _getAllLocFixedMiByLanLatRadWithHifu__return);


        }
        {
        System.out.println("Invoking getDicGiLocationByAllMapOfCodeApptagTime...");
        String _getDicGiLocationByAllMapOfCodeApptagTime_jsonAllMapOfCodeApptagTime = "";
        GetDicGiLocationByAllMapOfCodeApptagTimeResponse.GetDicGiLocationByAllMapOfCodeApptagTimeResult _getDicGiLocationByAllMapOfCodeApptagTime__return = port.getDicGiLocationByAllMapOfCodeApptagTime(_getDicGiLocationByAllMapOfCodeApptagTime_jsonAllMapOfCodeApptagTime);
        System.out.println("getDicGiLocationByAllMapOfCodeApptagTime.result=" + _getDicGiLocationByAllMapOfCodeApptagTime__return);


        }

        System.exit(0);
    }

}
