package com.gistandard.transport.system.webservice.client.gps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-09-06T14:28:33.321+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://webservice.manage.gps.com/", name = "PnWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PnWebService {

    @WebResult(name = "getAllGiBizOrderCountResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiBizOrderCount", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderCount")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiBizOrderCountResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderCountResponse")
    public long getAllGiBizOrderCount(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "sourceProvince", targetNamespace = "")
            String sourceProvince,
            @WebParam(name = "sourceCity", targetNamespace = "")
            String sourceCity,
            @WebParam(name = "sourceDistrict", targetNamespace = "")
            String sourceDistrict,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode
    );

    @WebResult(name = "getIsOnlineGpsByUserCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getIsOnlineGpsByUserCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetIsOnlineGpsByUserCode")
    @WebMethod
    @ResponseWrapper(localName = "getIsOnlineGpsByUserCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetIsOnlineGpsByUserCodeResponse")
    public String getIsOnlineGpsByUserCode(
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode,
            @WebParam(name = "appTag", targetNamespace = "")
            String appTag,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode
    );

    @WebResult(name = "getAllGiAdminConcernPcdByUserCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiAdminConcernPcdByUserCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiAdminConcernPcdByUserCode")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiAdminConcernPcdByUserCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiAdminConcernPcdByUserCodeResponse")
    public GiAdminResult getAllGiAdminConcernPcdByUserCode(
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode
    );

    @WebResult(name = "getAllGicbFenceGeoResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGicbFenceGeo", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGicbFenceGeo")
    @WebMethod
    @ResponseWrapper(localName = "getAllGicbFenceGeoResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGicbFenceGeoResponse")
    public String getAllGicbFenceGeo();

    @WebResult(name = "getLastMlOrderTraceByBusiNoResult", targetNamespace = "")
    @RequestWrapper(localName = "getLastMlOrderTraceByBusiNo", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetLastMlOrderTraceByBusiNo")
    @WebMethod
    @ResponseWrapper(localName = "getLastMlOrderTraceByBusiNoResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetLastMlOrderTraceByBusiNoResponse")
    public MlOrderTrace getLastMlOrderTraceByBusiNo(
            @WebParam(name = "busiNo", targetNamespace = "")
            String busiNo
    );

    @WebResult(name = "getAllGiPositionUserByAddressResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiPositionUserByAddress", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserByAddress")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiPositionUserByAddressResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserByAddressResponse")
    public String getAllGiPositionUserByAddress(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "appTag", targetNamespace = "")
            String appTag,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode,
            @WebParam(name = "jsonAllStationCandidate", targetNamespace = "")
            String jsonAllStationCandidate
    );

    @WebResult(name = "getAllGicbFenceGeoByCityNameResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGicbFenceGeoByCityName", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGicbFenceGeoByCityName")
    @WebMethod
    @ResponseWrapper(localName = "getAllGicbFenceGeoByCityNameResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGicbFenceGeoByCityNameResponse")
    public java.util.List<GicbFenceGeo> getAllGicbFenceGeoByCityName(
            @WebParam(name = "cityName", targetNamespace = "")
            String cityName,
            @WebParam(name = "districtName", targetNamespace = "")
            String districtName
    );

    @WebResult(name = "getAllLocExpressByLngLatRadWithHifuResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllLocExpressByLanLatRadWithHifu", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllLocExpressByLanLatRadWithHifu")
    @WebMethod
    @ResponseWrapper(localName = "getAllLocExpressByLanLatRadWithHifuResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllLocExpressByLanLatRadWithHifuResponse")
    public String getAllLocExpressByLanLatRadWithHifu(
            @WebParam(name = "longitude", targetNamespace = "")
            double longitude,
            @WebParam(name = "latitude", targetNamespace = "")
            double latitude,
            @WebParam(name = "radius", targetNamespace = "")
            double radius,
            @WebParam(name = "isHifu", targetNamespace = "")
            boolean isHifu
    );

    @WebResult(name = "pushAllGipnOrder3Result", targetNamespace = "")
    @RequestWrapper(localName = "pushAllGipnOrder3", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.PushAllGipnOrder3")
    @WebMethod
    @ResponseWrapper(localName = "pushAllGipnOrder3Response", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.PushAllGipnOrder3Response")
    public String pushAllGipnOrder3(
            @WebParam(name = "jsonAllGipnOrder", targetNamespace = "")
            String jsonAllGipnOrder
    );

    @WebResult(name = "getAllGiPositionUserByLanLatRadApptagModulesRolesResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiPositionUserByLanLatRadApptagModulesRoles", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserByLanLatRadApptagModulesRoles")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiPositionUserByLanLatRadApptagModulesRolesResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserByLanLatRadApptagModulesRolesResponse")
    public String getAllGiPositionUserByLanLatRadApptagModulesRoles(
            @WebParam(name = "longitude", targetNamespace = "")
            double longitude,
            @WebParam(name = "latitude", targetNamespace = "")
            double latitude,
            @WebParam(name = "radius", targetNamespace = "")
            double radius,
            @WebParam(name = "appTag", targetNamespace = "")
            String appTag,
            @WebParam(name = "moduleCode", targetNamespace = "")
            String moduleCode,
            @WebParam(name = "csvRoleCode", targetNamespace = "")
            String csvRoleCode
    );

    @WebResult(name = "getAllGiBizOrderPagingResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiBizOrderPaging", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiBizOrderPagingResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderPagingResponse")
    public String getAllGiBizOrderPaging(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "sourceProvince", targetNamespace = "")
            String sourceProvince,
            @WebParam(name = "sourceCity", targetNamespace = "")
            String sourceCity,
            @WebParam(name = "sourceDistrict", targetNamespace = "")
            String sourceDistrict,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode,
            @WebParam(name = "pageNum", targetNamespace = "")
            int pageNum,
            @WebParam(name = "pageSize", targetNamespace = "")
            int pageSize
    );

    @WebResult(name = "getAllRptOrderTraceWithTimeControlByDateFromToResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllRptOrderTraceWithTimeControlByDateFromTo", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllRptOrderTraceWithTimeControlByDateFromTo")
    @WebMethod
    @ResponseWrapper(localName = "getAllRptOrderTraceWithTimeControlByDateFromToResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllRptOrderTraceWithTimeControlByDateFromToResponse")
    public java.util.List<RptOrderTrace> getAllRptOrderTraceWithTimeControlByDateFromTo(
            @WebParam(name = "cityName", targetNamespace = "")
            String cityName,
            @WebParam(name = "districtName", targetNamespace = "")
            String districtName,
            @WebParam(name = "gicbFenceName", targetNamespace = "")
            String gicbFenceName,
            @WebParam(name = "busiDateFrom", targetNamespace = "")
            java.util.Date busiDateFrom,
            @WebParam(name = "busiDateTo", targetNamespace = "")
            java.util.Date busiDateTo,
            @WebParam(name = "productType", targetNamespace = "")
            String productType
    ) throws Exception_Exception;

    @WebResult(name = "getAllGiBizOrderByAllDocNoResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiBizOrderByAllDocNo", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderByAllDocNo")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiBizOrderByAllDocNoResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderByAllDocNoResponse")
    public String getAllGiBizOrderByAllDocNo(
            @WebParam(name = "jsonAllDocNo", targetNamespace = "")
            String jsonAllDocNo
    );

    @WebResult(name = "getAllLocExpressByLngLatRadResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllLocExpressByLanLatRad", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllLocExpressByLanLatRad")
    @WebMethod
    @ResponseWrapper(localName = "getAllLocExpressByLanLatRadResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllLocExpressByLanLatRadResponse")
    public String getAllLocExpressByLanLatRad(
            @WebParam(name = "longitude", targetNamespace = "")
            double longitude,
            @WebParam(name = "latitude", targetNamespace = "")
            double latitude,
            @WebParam(name = "radius", targetNamespace = "")
            double radius
    );

    @WebResult(name = "getShortestMiStationResult", targetNamespace = "")
    @RequestWrapper(localName = "getShortestMiStation", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetShortestMiStation")
    @WebMethod
    @ResponseWrapper(localName = "getShortestMiStationResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetShortestMiStationResponse")
    public String getShortestMiStation(
            @WebParam(name = "waStationCode", targetNamespace = "")
            String waStationCode,
            @WebParam(name = "lngOfAddress", targetNamespace = "")
            double lngOfAddress,
            @WebParam(name = "latOfAddress", targetNamespace = "")
            double latOfAddress
    );

    @WebResult(name = "getAllGiPositionStationMiniByWaStationCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiPositionStationMiniByWaStationCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionStationMiniByWaStationCode")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiPositionStationMiniByWaStationCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionStationMiniByWaStationCodeResponse")
    public String getAllGiPositionStationMiniByWaStationCode(
            @WebParam(name = "waStationCode", targetNamespace = "")
            String waStationCode
    );

    @WebResult(name = "resyncGiPositionStationResult", targetNamespace = "")
    @RequestWrapper(localName = "resyncGiPositionStation", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.ResyncGiPositionStation")
    @WebMethod
    @ResponseWrapper(localName = "resyncGiPositionStationResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.ResyncGiPositionStationResponse")
    public String resyncGiPositionStation(
            @WebParam(name = "jsonGiPositionStation", targetNamespace = "")
            String jsonGiPositionStation,
            @WebParam(name = "operation", targetNamespace = "")
            String operation
    );

    @WebResult(name = "getGiLocationByUserCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getGiLocationByUserCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiLocationByUserCode")
    @WebMethod
    @ResponseWrapper(localName = "getGiLocationByUserCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiLocationByUserCodeResponse")
    public String getGiLocationByUserCode(
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode
    );

    @WebResult(name = "getAllGiPositionStationByRouteAndUserResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiPositionStationByRouteAndUser", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionStationByRouteAndUser")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiPositionStationByRouteAndUserResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionStationByRouteAndUserResponse")
    public String getAllGiPositionStationByRouteAndUser(
            @WebParam(name = "jsonAllStationCode", targetNamespace = "")
            String jsonAllStationCode,
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode,
            @WebParam(name = "userRole", targetNamespace = "")
            String userRole,
            @WebParam(name = "appTag", targetNamespace = "")
            String appTag
    );

    @WebResult(name = "getDistanceRunedByTruckResult", targetNamespace = "")
    @RequestWrapper(localName = "getDistanceRunedByTruck", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetDistanceRunedByTruck")
    @WebMethod
    @ResponseWrapper(localName = "getDistanceRunedByTruckResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetDistanceRunedByTruckResponse")
    public double getDistanceRunedByTruck(
            @WebParam(name = "truckCode", targetNamespace = "")
            String truckCode,
            @WebParam(name = "dateBegin", targetNamespace = "")
            java.util.Date dateBegin,
            @WebParam(name = "dateEnd", targetNamespace = "")
            java.util.Date dateEnd
    );

    @WebResult(name = "getAllRptOrderTraceWithTimeControlResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllRptOrderTraceWithTimeControl", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllRptOrderTraceWithTimeControl")
    @WebMethod
    @ResponseWrapper(localName = "getAllRptOrderTraceWithTimeControlResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllRptOrderTraceWithTimeControlResponse")
    public java.util.List<RptOrderTrace> getAllRptOrderTraceWithTimeControl(
            @WebParam(name = "cityName", targetNamespace = "")
            String cityName,
            @WebParam(name = "districtName", targetNamespace = "")
            String districtName,
            @WebParam(name = "gicbFenceName", targetNamespace = "")
            String gicbFenceName,
            @WebParam(name = "busiDate", targetNamespace = "")
            java.util.Date busiDate,
            @WebParam(name = "productType", targetNamespace = "")
            String productType
    ) throws Exception_Exception;

    @WebResult(name = "getGpsTokenResult", targetNamespace = "")
    @RequestWrapper(localName = "getGpsToken", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGpsToken")
    @WebMethod
    @ResponseWrapper(localName = "getGpsTokenResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGpsTokenResponse")
    public String getGpsToken(
            @WebParam(name = "code", targetNamespace = "")
            String code
    );

    @WebResult(name = "getAllGiPositionUserForSearchResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiPositionUserForSearch", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserForSearch")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiPositionUserForSearchResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserForSearchResponse")
    public String getAllGiPositionUserForSearch(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "searchTxt", targetNamespace = "")
            String searchTxt,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode
    );

    @WebResult(name = "getAllGiBizOrderBizModeCountResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiBizOrderBizModeCount", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderBizModeCount")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiBizOrderBizModeCountResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderBizModeCountResponse")
    public long getAllGiBizOrderBizModeCount(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "sourceProvince", targetNamespace = "")
            String sourceProvince,
            @WebParam(name = "sourceCity", targetNamespace = "")
            String sourceCity,
            @WebParam(name = "sourceDistrict", targetNamespace = "")
            String sourceDistrict,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode,
            @WebParam(name = "bizMode", targetNamespace = "")
            int bizMode
    );

    @WebResult(name = "getAllGiPositionUserForSearch2Result", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiPositionUserForSearch2", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserForSearch2")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiPositionUserForSearch2Response", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserForSearch2Response")
    public String getAllGiPositionUserForSearch2(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "province", targetNamespace = "")
            String province,
            @WebParam(name = "city", targetNamespace = "")
            String city,
            @WebParam(name = "district", targetNamespace = "")
            String district,
            @WebParam(name = "searchTxt", targetNamespace = "")
            String searchTxt,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode
    );

    @WebResult(name = "getAllGiLocationByAllMapOfCodeApptagTimeResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiLocationByAllMapOfCodeApptagTime", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiLocationByAllMapOfCodeApptagTime")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiLocationByAllMapOfCodeApptagTimeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiLocationByAllMapOfCodeApptagTimeResponse")
    public String getAllGiLocationByAllMapOfCodeApptagTime(
            @WebParam(name = "jsonAllMapOfCodeApptagTime", targetNamespace = "")
            String jsonAllMapOfCodeApptagTime
    );

    @WebResult(name = "getAllGiLocationCurrentByUserCodesResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiLocationCurrentByUserCodes", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiLocationCurrentByUserCodes")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiLocationCurrentByUserCodesResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiLocationCurrentByUserCodesResponse")
    public String getAllGiLocationCurrentByUserCodes(
            @WebParam(name = "userCodes", targetNamespace = "")
            String userCodes
    );

    @WebResult(name = "getAllWaMiStationByRouteAndExpressCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllWaMiStationByRouteAndExpressCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllWaMiStationByRouteAndExpressCode")
    @WebMethod
    @ResponseWrapper(localName = "getAllWaMiStationByRouteAndExpressCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllWaMiStationByRouteAndExpressCodeResponse")
    public String getAllWaMiStationByRouteAndExpressCode(
            @WebParam(name = "jsonAllStationCode", targetNamespace = "")
            String jsonAllStationCode,
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode,
            @WebParam(name = "appTag", targetNamespace = "")
            String appTag
    );

    @WebResult(name = "getMiStationWithMiRouteStopByCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getMiStationWithMiRouteStopByCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetMiStationWithMiRouteStopByCode")
    @WebMethod
    @ResponseWrapper(localName = "getMiStationWithMiRouteStopByCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetMiStationWithMiRouteStopByCodeResponse")
    public String getMiStationWithMiRouteStopByCode(
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode
    );

    @WebResult(name = "getGicbFenceGeoByLngLatResult", targetNamespace = "")
    @RequestWrapper(localName = "getGicbFenceGeoByLngLat", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGicbFenceGeoByLngLat")
    @WebMethod
    @ResponseWrapper(localName = "getGicbFenceGeoByLngLatResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGicbFenceGeoByLngLatResponse")
    public String getGicbFenceGeoByLngLat(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat
    );

    @WebResult(name = "getMiStationNearestInFenceResult", targetNamespace = "")
    @RequestWrapper(localName = "getMiStationNearestInFence", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetMiStationNearestInFence")
    @WebMethod
    @ResponseWrapper(localName = "getMiStationNearestInFenceResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetMiStationNearestInFenceResponse")
    public GiPositionAcct getMiStationNearestInFence(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat
    );

    @WebResult(name = "getAllGiPositionUserByLanLatRadApptagModulesRoles3Result", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiPositionUserByLanLatRadApptagModulesRoles3", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserByLanLatRadApptagModulesRoles3")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiPositionUserByLanLatRadApptagModulesRoles3Response", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiPositionUserByLanLatRadApptagModulesRoles3Response")
    public String getAllGiPositionUserByLanLatRadApptagModulesRoles3(
            @WebParam(name = "longitude", targetNamespace = "")
            double longitude,
            @WebParam(name = "latitude", targetNamespace = "")
            double latitude,
            @WebParam(name = "radius", targetNamespace = "")
            double radius,
            @WebParam(name = "appTag", targetNamespace = "")
            String appTag,
            @WebParam(name = "csvModuleCode", targetNamespace = "")
            String csvModuleCode,
            @WebParam(name = "csvRoleCode", targetNamespace = "")
            String csvRoleCode
    );

    @WebResult(name = "getShortestRouteResult", targetNamespace = "")
    @RequestWrapper(localName = "getShortestRoute", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetShortestRoute")
    @WebMethod
    @ResponseWrapper(localName = "getShortestRouteResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetShortestRouteResponse")
    public Integer getShortestRoute(
            @WebParam(name = "lngFrom", targetNamespace = "")
            double lngFrom,
            @WebParam(name = "latFrom", targetNamespace = "")
            double latFrom,
            @WebParam(name = "lngTo", targetNamespace = "")
            double lngTo,
            @WebParam(name = "latTo", targetNamespace = "")
            double latTo,
            @WebParam(name = "jsonAllBizRoute", targetNamespace = "")
            String jsonAllBizRoute
    );

    @WebResult(name = "getAllGiBizOrderForClusterResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiBizOrderForCluster", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderForCluster")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiBizOrderForClusterResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderForClusterResponse")
    public String getAllGiBizOrderForCluster(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode,
            @WebParam(name = "isOnlyMyFence", targetNamespace = "")
            boolean isOnlyMyFence,
            @WebParam(name = "radius", targetNamespace = "")
            double radius
    );

    @WebResult(name = "getGiRoutePlanByIdResult", targetNamespace = "")
    @RequestWrapper(localName = "getGiRoutePlanById", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiRoutePlanById")
    @WebMethod
    @ResponseWrapper(localName = "getGiRoutePlanByIdResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiRoutePlanByIdResponse")
    public String getGiRoutePlanById(
            @WebParam(name = "routePlanId", targetNamespace = "")
            String routePlanId
    );

    @WebResult(name = "getGiPositionAcctByUserCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getGiPositionAcctByUserCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiPositionAcctByUserCode")
    @WebMethod
    @ResponseWrapper(localName = "getGiPositionAcctByUserCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiPositionAcctByUserCodeResponse")
    public String getGiPositionAcctByUserCode(
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode
    );

    @WebResult(name = "getAllExpressDriverByLanLatRadResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllExpressDriverByLanLatRad", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllExpressDriverByLanLatRad")
    @WebMethod
    @ResponseWrapper(localName = "getAllExpressDriverByLanLatRadResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllExpressDriverByLanLatRadResponse")
    public String getAllExpressDriverByLanLatRad(
            @WebParam(name = "longitude", targetNamespace = "")
            double longitude,
            @WebParam(name = "latitude", targetNamespace = "")
            double latitude,
            @WebParam(name = "radius", targetNamespace = "")
            double radius,
            @WebParam(name = "isHifu", targetNamespace = "")
            boolean isHifu,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode
    );

    @WebResult(name = "getAllGiBizOrderAdhocPagingResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiBizOrderAdhocPaging", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderAdhocPaging")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiBizOrderAdhocPagingResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderAdhocPagingResponse")
    public String getAllGiBizOrderAdhocPaging(
            @WebParam(name = "sourceProvince", targetNamespace = "")
            String sourceProvince,
            @WebParam(name = "sourceCity", targetNamespace = "")
            String sourceCity,
            @WebParam(name = "sourceDistrict", targetNamespace = "")
            String sourceDistrict,
            @WebParam(name = "destProvince", targetNamespace = "")
            String destProvince,
            @WebParam(name = "destCity", targetNamespace = "")
            String destCity,
            @WebParam(name = "destDistrict", targetNamespace = "")
            String destDistrict,
            @WebParam(name = "docNo", targetNamespace = "")
            String docNo,
            @WebParam(name = "roleCode", targetNamespace = "")
            String roleCode,
            @WebParam(name = "tsCreatedFrom", targetNamespace = "")
            java.util.Date tsCreatedFrom,
            @WebParam(name = "tsCreatedTo", targetNamespace = "")
            java.util.Date tsCreatedTo,
            @WebParam(name = "pageNum", targetNamespace = "")
            int pageNum,
            @WebParam(name = "pageSize", targetNamespace = "")
            int pageSize
    );

    @WebResult(name = "greetingResult", targetNamespace = "")
    @RequestWrapper(localName = "greeting", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.Greeting")
    @WebMethod
    @ResponseWrapper(localName = "greetingResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GreetingResponse")
    public String greeting(
            @WebParam(name = "userName", targetNamespace = "")
            String userName
    );

    @WebResult(name = "getAllMiStationByStopIdResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllMiStationByStopId", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllMiStationByStopId")
    @WebMethod
    @ResponseWrapper(localName = "getAllMiStationByStopIdResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllMiStationByStopIdResponse")
    public String getAllMiStationByStopId(
            @WebParam(name = "idGiMiRoutePlan", targetNamespace = "")
            String idGiMiRoutePlan,
            @WebParam(name = "miStopId", targetNamespace = "")
            String miStopId
    );

    @WebResult(name = "getAllGiBizOrderBizModePagingResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllGiBizOrderBizModePaging", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderBizModePaging")
    @WebMethod
    @ResponseWrapper(localName = "getAllGiBizOrderBizModePagingResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllGiBizOrderBizModePagingResponse")
    public String getAllGiBizOrderBizModePaging(
            @WebParam(name = "lng", targetNamespace = "")
            double lng,
            @WebParam(name = "lat", targetNamespace = "")
            double lat,
            @WebParam(name = "sourceProvince", targetNamespace = "")
            String sourceProvince,
            @WebParam(name = "sourceCity", targetNamespace = "")
            String sourceCity,
            @WebParam(name = "sourceDistrict", targetNamespace = "")
            String sourceDistrict,
            @WebParam(name = "jsonAllRoleCode", targetNamespace = "")
            String jsonAllRoleCode,
            @WebParam(name = "bizMode", targetNamespace = "")
            int bizMode,
            @WebParam(name = "pageNum", targetNamespace = "")
            int pageNum,
            @WebParam(name = "pageSize", targetNamespace = "")
            int pageSize
    );

    @WebResult(name = "getIsInSameFenceResult", targetNamespace = "")
    @RequestWrapper(localName = "getIsInSameFence", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetIsInSameFence")
    @WebMethod
    @ResponseWrapper(localName = "getIsInSameFenceResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetIsInSameFenceResponse")
    public boolean getIsInSameFence(
            @WebParam(name = "lng1", targetNamespace = "")
            double lng1,
            @WebParam(name = "lat1", targetNamespace = "")
            double lat1,
            @WebParam(name = "lng2", targetNamespace = "")
            double lng2,
            @WebParam(name = "lat2", targetNamespace = "")
            double lat2
    );

    @WebResult(name = "getGiPositionUserOfMovingWaByUserCodeResult", targetNamespace = "")
    @RequestWrapper(localName = "getGiPositionUserOfMovingWaByUserCode", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiPositionUserOfMovingWaByUserCode")
    @WebMethod
    @ResponseWrapper(localName = "getGiPositionUserOfMovingWaByUserCodeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetGiPositionUserOfMovingWaByUserCodeResponse")
    public String getGiPositionUserOfMovingWaByUserCode(
            @WebParam(name = "userCode", targetNamespace = "")
            String userCode
    );

    @WebResult(name = "uploadSomethingTestResult", targetNamespace = "")
    @RequestWrapper(localName = "uploadSomethingTest", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.UploadSomethingTest")
    @WebMethod
    @ResponseWrapper(localName = "uploadSomethingTestResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.UploadSomethingTestResponse")
    public String uploadSomethingTest(
            @WebParam(name = "text", targetNamespace = "")
            String text
    );

    @WebResult(name = "getAllLocMiStationByLngLatRadWithHifuResult", targetNamespace = "")
    @RequestWrapper(localName = "getAllLocFixedMiByLanLatRadWithHifu", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllLocFixedMiByLanLatRadWithHifu")
    @WebMethod
    @ResponseWrapper(localName = "getAllLocFixedMiByLanLatRadWithHifuResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetAllLocFixedMiByLanLatRadWithHifuResponse")
    public String getAllLocFixedMiByLanLatRadWithHifu(
            @WebParam(name = "longitude", targetNamespace = "")
            double longitude,
            @WebParam(name = "latitude", targetNamespace = "")
            double latitude,
            @WebParam(name = "radius", targetNamespace = "")
            double radius,
            @WebParam(name = "isHifu", targetNamespace = "")
            boolean isHifu
    );

    @WebResult(name = "getDicGiLocationByAllMapOfCodeApptagTimeResult", targetNamespace = "")
    @RequestWrapper(localName = "getDicGiLocationByAllMapOfCodeApptagTime", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetDicGiLocationByAllMapOfCodeApptagTime")
    @WebMethod
    @ResponseWrapper(localName = "getDicGiLocationByAllMapOfCodeApptagTimeResponse", targetNamespace = "http://webservice.manage.gps.com/", className = "com.gistandard.transport.system.webservice.client.gps.GetDicGiLocationByAllMapOfCodeApptagTimeResponse")
    public GetDicGiLocationByAllMapOfCodeApptagTimeResponse.GetDicGiLocationByAllMapOfCodeApptagTimeResult getDicGiLocationByAllMapOfCodeApptagTime(
            @WebParam(name = "jsonAllMapOfCodeApptagTime", targetNamespace = "")
            String jsonAllMapOfCodeApptagTime
    );
}
