package com.gistandard.transport.system.webservice.client.gps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-09-06T14:28:33.342+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "PnWebServiceService", 
                  wsdlLocation = "http://172.16.2.125:8080/gpsWebService/pushNotification?wsdl",
                  targetNamespace = "http://webservice.manage.gps.com/") 
public class PnWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.manage.gps.com/", "PnWebServiceService");
    public final static QName PnWebServicePort = new QName("http://webservice.manage.gps.com/", "PnWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.2.125:8080/gpsWebService/pushNotification?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PnWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.16.2.125:8080/gpsWebService/pushNotification?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PnWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PnWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PnWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PnWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PnWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PnWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PnWebService
     */
    @WebEndpoint(name = "PnWebServicePort")
    public PnWebService getPnWebServicePort() {
        return super.getPort(PnWebServicePort, PnWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PnWebService
     */
    @WebEndpoint(name = "PnWebServicePort")
    public PnWebService getPnWebServicePort(WebServiceFeature... features) {
        return super.getPort(PnWebServicePort, PnWebService.class, features);
    }

}
