USE giifi;

/*Table structure for table COM_ACCOUNT */

DROP TABLE IF EXISTS COM_ACCOUNT;

CREATE TABLE COM_ACCOUNT (
  ID int(10) NOT NULL AUTO_INCREMENT,
  GISTANDARD_NO varchar(50) DEFAULT NULL,
  ACCT_USERNAME varchar(100) DEFAULT NULL,
  REAL_NAME varchar(200) DEFAULT NULL,
  NICK_NAME varchar(50) DEFAULT NULL,
  ACCT_STATUS int(2) DEFAULT NULL COMMENT '1、可用，2、禁用，3、已删除，4、待审核，5、待授权，6、审核未通过，7、已冻结，8、已注册未完成信息',
  ACCT_AUDIT_USER varchar(50) DEFAULT NULL,
  ACCT_AUDIT_DATE datetime DEFAULT NULL,
  REMARK varchar(100) DEFAULT NULL,
  FLAG varchar(20) DEFAULT NULL,
  TEL_PREFIX varchar(5) DEFAULT NULL COMMENT '手机号前缀',
  TELEPHONE varchar(20) DEFAULT NULL COMMENT '手机号码',
  EMAIL varchar(100) DEFAULT NULL COMMENT '邮箱',
  USER_IMG varchar(200) DEFAULT NULL,
  AUTHORIZE_SYS_CODES varchar(300) DEFAULT NULL COMMENT '授权系统代码，保存授权系统代码的List类型的JSON字符串，在人员创建和解除授权或禁用时，需要同步修改此字段',
  CREATE_TIME datetime DEFAULT NULL,
  FROM_SYS_ID int(10) DEFAULT NULL,
  ACCOUNT_TYPES varchar(200) DEFAULT NULL COMMENT '账号拥有的角色信息（字典中配置），角色代码List类型的JSON字符串，一个账号存在多个角色信息',
  ACCT_TYPE varchar(32) DEFAULT NULL COMMENT '帐号类型  1个人 2企业',
  REGISTER_TYPE varchar(32) DEFAULT NULL COMMENT '注册类型  1用户 2商户',
  COUNTRY_ID int(10) DEFAULT NULL,
  PROVINCE_ID int(10) DEFAULT NULL,
  CITY_ID int(10) DEFAULT NULL,
  COUNTY_ID int(10) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ACCT_USERNAME (ACCT_USERNAME),
  UNIQUE KEY GISTANDARD_NO (GISTANDARD_NO)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_ACCOUNT_AUTHORIZE */

DROP TABLE IF EXISTS COM_ACCOUNT_AUTHORIZE;

CREATE TABLE COM_ACCOUNT_AUTHORIZE (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID int(10) DEFAULT NULL,
  SYS_ID int(10) DEFAULT NULL,
  STATUS int(2) DEFAULT NULL COMMENT '授权状态(1、已授权，2、已解除授权，3、未授权)',
  REQ_AUTH_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '申请授权的管理员ID',
  AUTHORIZE_TIME datetime DEFAULT NULL,
  UN_AUTHORIZE_TIME datetime DEFAULT NULL,
  AUTH_USER varchar(50) DEFAULT NULL,
  UN_AUTH_USER varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY idx_ACCOUNT_ID (ACCOUNT_ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_ACCOUNT_BUSINESS_REL */

DROP TABLE IF EXISTS COM_ACCOUNT_BUSINESS_REL;

CREATE TABLE COM_ACCOUNT_BUSINESS_REL (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '商户帐号ID（COM_ACCOUNT）',
  BIZ_USER_ID int(10) DEFAULT NULL COMMENT '商务人员ID（SYS_USER）',
  SYS_ID int(10) DEFAULT NULL COMMENT '商务人员管理的商户人员帐号所对应的系统',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  STATUS int(2) DEFAULT NULL COMMENT '通用状态',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_ACCOUNT_EXCEPTION_RECORD */

DROP TABLE IF EXISTS COM_ACCOUNT_EXCEPTION_RECORD;

CREATE TABLE COM_ACCOUNT_EXCEPTION_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '帐号ID',
  EXCEPTION_TYPE int(4) DEFAULT NULL COMMENT '异常类型',
  EXCEPTION_STATUS int(2) DEFAULT NULL COMMENT '异常状态',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_ACCOUNT_MODULE_AUTH */

DROP TABLE IF EXISTS COM_ACCOUNT_MODULE_AUTH;

CREATE TABLE COM_ACCOUNT_MODULE_AUTH (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '帐号ID',
  MODULE_ID int(10) DEFAULT NULL COMMENT '模块表的ID',
  AUTHORIZE_TIME datetime DEFAULT NULL COMMENT '授权时间',
  AUTH_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '授权人员ID',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_ACCOUNT_OPERATE_AUTH */

DROP TABLE IF EXISTS COM_ACCOUNT_OPERATE_AUTH;

CREATE TABLE COM_ACCOUNT_OPERATE_AUTH (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '帐号ID',
  OPERATE_ID int(10) DEFAULT NULL COMMENT '操作ID',
  AUTHORIZE_TIME datetime DEFAULT NULL COMMENT '授权时间',
  AUTH_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '授权人员',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_PARTITION */

DROP TABLE IF EXISTS COM_ACCOUNT_PARTITION;

CREATE TABLE COM_ACCOUNT_PARTITION (
  ID int(10) NOT NULL AUTO_INCREMENT,
  CITY_ID int(10) DEFAULT NULL,
  TEL_CODE varchar(10) DEFAULT NULL,
  PARTITION_NO int(8) DEFAULT NULL,
  NEXT_SEQ int(10) DEFAULT NULL,
  ACCOUNT_SEQUENCE varchar(1000) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY idx_PARTITION_NO_TEL_CODE (PARTITION_NO,TEL_CODE)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_PASSWORD */

DROP TABLE IF EXISTS COM_ACCOUNT_PASSWORD;

CREATE TABLE COM_ACCOUNT_PASSWORD (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '所属帐号ID',
  LOGIN_PASSWORD varchar(100) DEFAULT NULL,
  SALT varchar(50) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_REL */

DROP TABLE IF EXISTS COM_ACCOUNT_REL;

CREATE TABLE COM_ACCOUNT_REL (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '帐号ID',
  REL_ID int(10) DEFAULT NULL COMMENT '关联数据ID',
  REL_TYPE int(2) DEFAULT NULL COMMENT '关联类型（1、帐号关联人员信息COM_USER，2、帐号关联企业COM_COMPANY，3、帐号关联设备COM_DEVICE_INFO）',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  RECORD_SYS_ID int(10) DEFAULT NULL COMMENT '备案系统ID',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_ROLE_LIST */

DROP TABLE IF EXISTS COM_ACCOUNT_ROLE_LIST;

CREATE TABLE COM_ACCOUNT_ROLE_LIST (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '帐号',
  ROLE_ID int(10) DEFAULT NULL COMMENT '帐号角色ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  STATUS int(2) DEFAULT NULL COMMENT '1、可用，2、禁用，3、待审核',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_TYPE */

DROP TABLE IF EXISTS COM_ACCOUNT_TYPE;

CREATE TABLE COM_ACCOUNT_TYPE (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCT_TYPE_NAME varchar(100) DEFAULT NULL COMMENT '类型名称',
  ACCT_TYPE_CODE varchar(100) DEFAULT NULL COMMENT '类型代码',
  ACCT_CATEGORY varchar(100) DEFAULT NULL COMMENT '账号类别，在字典中定义账号类别字典，值包括（用户，商户），多个值以逗号分割',
  AUDIT_FLAG tinyint(1) DEFAULT NULL COMMENT '是否需要审核（这个系统注册的账户是否需要审核） 是，审核，否，不审核',
  DEFAULT_AUTH tinyint(1) DEFAULT NULL COMMENT '是否默认授权',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  BELONG_PLATFORM int(2) DEFAULT NULL COMMENT '所属平台（1、物流开放平台，2、工作任务管理平台，3、嘀讯平台，4、通用账户）',
  TYPE_CLASS int(2) DEFAULT NULL COMMENT '角色类型（1、人员角色，2、企业角色）',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_ACCOUNT_TYPE_MODULE_REL */

DROP TABLE IF EXISTS COM_ACCOUNT_TYPE_MODULE_REL;

CREATE TABLE COM_ACCOUNT_TYPE_MODULE_REL (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_TYPE_ID int(10) DEFAULT NULL COMMENT '帐号类型ID',
  MODULE_ID int(10) DEFAULT NULL COMMENT '模块ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_TYPE_OPERATE_REL */

DROP TABLE IF EXISTS COM_ACCOUNT_TYPE_OPERATE_REL;

CREATE TABLE COM_ACCOUNT_TYPE_OPERATE_REL (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_TYPE_ID int(10) DEFAULT NULL COMMENT '帐号类型ID',
  OPERATE_ID int(10) DEFAULT NULL COMMENT '操作类型ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_TYPE_REL */

DROP TABLE IF EXISTS COM_ACCOUNT_TYPE_REL;

CREATE TABLE COM_ACCOUNT_TYPE_REL (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  AUTHORIZE_ID int(10) DEFAULT NULL COMMENT '账号ID',
  ACCT_TYPE varchar(100) DEFAULT NULL COMMENT '账号类型（普通用户，普通企业，车主，车队，HUB，站点工作人员等等）',
  ACCT_CATEGORY varchar(20) DEFAULT NULL COMMENT '账号类别（用户，商户），多个值以逗号分隔',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ACCOUNT_TYPE_SYSTEM_REL */

DROP TABLE IF EXISTS COM_ACCOUNT_TYPE_SYSTEM_REL;

CREATE TABLE COM_ACCOUNT_TYPE_SYSTEM_REL (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_TYPE_ID int(10) DEFAULT NULL COMMENT '帐号类型表ID',
  SYS_ID int(10) DEFAULT NULL COMMENT '关联系统ID',
  REL_STATUS int(2) DEFAULT NULL COMMENT '关联状态',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ALL_TYPE */

DROP TABLE IF EXISTS COM_ALL_TYPE;

CREATE TABLE COM_ALL_TYPE (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '序号',
  T_TYPE varchar(30) DEFAULT NULL,
  T_CODE varchar(30) DEFAULT NULL,
  T_NAME varchar(30) DEFAULT NULL,
  T_REMARK varchar(30) DEFAULT NULL,
  T_FLAG int(2) DEFAULT NULL,
  T_SORT int(4) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ATTACHMENT */

DROP TABLE IF EXISTS COM_ATTACHMENT;

CREATE TABLE COM_ATTACHMENT (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  ATTACHMENT_NAME varchar(256) DEFAULT NULL COMMENT '附件名称',
  ATTACHMENT_OLD_NAME varchar(256) DEFAULT NULL COMMENT '附件原名称',
  ATTACHMENT_MIME varchar(256) DEFAULT NULL COMMENT '附件MIME类型',
  UPLOAD_DOMAIN varchar(50) DEFAULT NULL COMMENT '附件来源系统域名',
  SAVE_PATH varchar(256) DEFAULT NULL COMMENT '附件存放路径',
  PROJECT_PATH varchar(256) DEFAULT NULL COMMENT '系统路径',
  ATTACHMENT_SIZE varchar(100) DEFAULT NULL COMMENT '附件大小',
  ATTACHMENT_STATUS int(2) DEFAULT NULL COMMENT '附件状态( 可用：1  禁用： 2 已删除： 3)',
  ATTACHMENT_CREATE_TIME datetime DEFAULT NULL COMMENT '附件上传时间',
  ATTACHMENT_MODIFY_TIME datetime DEFAULT NULL COMMENT '附件更新时间',
  SERVER_IP varchar(50) DEFAULT NULL COMMENT '附件上传的服务器IP',
  ACCOUNT varchar(50) DEFAULT NULL COMMENT '上传用户账号',
  ATTACHMENT_TYPE_ID int(10) DEFAULT NULL COMMENT '附件类型ID(附件类型表主键)',
  FROM_SYS_ID int(10) DEFAULT NULL COMMENT '备案系统ID',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ATTACHMENT_RECORD */

DROP TABLE IF EXISTS COM_ATTACHMENT_RECORD;

CREATE TABLE COM_ATTACHMENT_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  ATTACHMENT_NAME varchar(256) DEFAULT NULL COMMENT '附件名称',
  ATTACHMENT_OLD_NAME varchar(256) DEFAULT NULL COMMENT '附件原名称',
  ATTACHMENT_MIME varchar(256) DEFAULT NULL COMMENT '附件MIME类型',
  SAVE_PATH varchar(256) DEFAULT NULL COMMENT '附件存放路径',
  PROJECT_PATH varchar(256) DEFAULT NULL COMMENT '系统路径',
  ATTACHMENT_SIZE varchar(100) DEFAULT NULL COMMENT '附件大小',
  ATTACHMENT_STATUS int(2) DEFAULT NULL COMMENT '附件状态( 可用：1  禁用： 2 已删除： 3)',
  ATTACHMENT_CREATE_TIME datetime DEFAULT NULL COMMENT '附件上传时间',
  ATTACHMENT_MODIFY_TIME datetime DEFAULT NULL COMMENT '附件更新时间',
  SERVER_IP varchar(50) DEFAULT NULL COMMENT '附件上传的服务器IP',
  ACCOUNT varchar(50) DEFAULT NULL COMMENT '上传用户账号',
  ATTACHMENT_TYPE_ID int(10) DEFAULT NULL COMMENT '附件类型ID(附件类型表主键)',
  FROM_SYS_ID int(10) DEFAULT NULL COMMENT '备案系统ID',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ATTACHMENT_REL */

DROP TABLE IF EXISTS COM_ATTACHMENT_REL;

CREATE TABLE COM_ATTACHMENT_REL (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ATTACH_ID int(10) DEFAULT NULL COMMENT '附件表ID',
  REL_ID int(10) DEFAULT NULL COMMENT '关联表ID',
  REL_TABLE varchar(30) DEFAULT NULL COMMENT '管理表名称',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_ATTACHMENT_TYPE */

DROP TABLE IF EXISTS COM_ATTACHMENT_TYPE;

CREATE TABLE COM_ATTACHMENT_TYPE (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '附件类型ID',
  TYPE_CODE varchar(100) DEFAULT NULL COMMENT '附件类型编码',
  TYPE_NAME varchar(100) DEFAULT NULL COMMENT '附件类型名称',
  TYPE_STATUS int(2) DEFAULT NULL COMMENT '附件类型状态( 可用：1  禁用： 2 已删除： 3)',
  TYPE_CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  TYPE_MODIFY_TIME datetime DEFAULT NULL COMMENT '更新时间',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统',
  DEFAULT_SAVE_PATH varchar(256) DEFAULT NULL,
  IS_PROTECTED int(2) DEFAULT NULL COMMENT '附件类型是否受保护( 可用：1  禁用： 2)',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_AUDIT_INFO */

DROP TABLE IF EXISTS COM_AUDIT_INFO;

CREATE TABLE COM_AUDIT_INFO (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ACCOUNT varchar(100) DEFAULT NULL COMMENT '账号',
  ACCT_NAME varchar(200) DEFAULT NULL COMMENT '名称（如果注册个人用户，就是人员姓名，如果是企业，就是企业名称）',
  IDENTITY_NO varchar(50) DEFAULT NULL COMMENT '身份证号',
  OPERATE_PERMIT_NO varchar(100) DEFAULT NULL COMMENT '企业经营许可证号',
  SYS_ID int(10) DEFAULT NULL COMMENT '提交系统',
  ACCT_TYPE varchar(100) DEFAULT NULL COMMENT '账号类型（关联的COM_ACCOUNT_TYPE表中的类型）',
  AUDIT_STATUS int(2) DEFAULT NULL COMMENT '审核状态（用SysAccountState）',
  AUDIT_TIME datetime DEFAULT NULL COMMENT '审核时间',
  AUDIT_SUGGEST varchar(400) DEFAULT NULL COMMENT '审核意见',
  AUDIT_USER varchar(100) DEFAULT NULL COMMENT '审核人员（保存审核人员账号）',
  CREATE_TIME datetime DEFAULT NULL COMMENT '审核提交时间',
  AUDIT_TYPE int(2) DEFAULT NULL COMMENT '审核类型（1、注册审核，2、信息修改审核）',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_CITY */

DROP TABLE IF EXISTS COM_CITY;

CREATE TABLE COM_CITY (
  ID int(10) NOT NULL,
  NAME varchar(50) DEFAULT NULL,
  SHORT_NAME varchar(20) DEFAULT NULL,
  CITY_PINYIN varchar(50) DEFAULT NULL,
  CITY_SHORT_P_Y varchar(50) DEFAULT NULL,
  HOT_CITY tinyint(1) DEFAULT NULL,
  LAST_MODIFY_TIME datetime DEFAULT NULL,
  SORT_NO int(5) DEFAULT NULL,
  PROVINCE_ID int(10) DEFAULT NULL,
  TEL_CODE varchar(20) DEFAULT NULL COMMENT '固话区号',
  COUNTRY_TTL varchar(10) DEFAULT NULL,
  LONGITUDE decimal(11,8) DEFAULT NULL COMMENT '经度',
  LATITUDE decimal(11,8) DEFAULT NULL COMMENT '纬度',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COMPANY */

DROP TABLE IF EXISTS COM_COMPANY;

CREATE TABLE COM_COMPANY (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  COMPANY_NAME varchar(100) DEFAULT NULL COMMENT '企业名称',
  COMPANY_CODE varchar(50) DEFAULT NULL COMMENT '企业代码',
  COMPANY_SHORT_NAME varchar(50) DEFAULT NULL COMMENT '企业简称',
  COMPANY_NO varchar(50) DEFAULT NULL COMMENT '企业编号',
  COMPANY_BIZ_NO varchar(50) DEFAULT NULL COMMENT '企业营业证号',
  STATUS int(2) DEFAULT NULL COMMENT '1、可用，2、禁用，3、待审核',
  FROM_SYS_ID int(10) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COMPANY_CONTACTS */

DROP TABLE IF EXISTS COM_COMPANY_CONTACTS;

CREATE TABLE COM_COMPANY_CONTACTS (
  ID int(10) NOT NULL AUTO_INCREMENT,
  COMPANY_ID int(10) DEFAULT NULL COMMENT '所属企业',
  LINK_MAN_NAME varchar(40) DEFAULT NULL COMMENT '联系人名称',
  WORK_TEL varchar(50) DEFAULT NULL COMMENT '办公固定电话',
  WORK_FAX varchar(50) DEFAULT NULL COMMENT '办公传真',
  MOBILE_TEL varchar(50) DEFAULT NULL COMMENT '移动电话',
  POSITION varchar(50) DEFAULT NULL COMMENT '职位',
  HOME_TEL varchar(50) DEFAULT NULL COMMENT '家庭电话',
  HOME_ADDRESS varchar(100) DEFAULT NULL COMMENT '家庭住址',
  EMAIL varchar(100) DEFAULT NULL,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COMPANY_CONTACTS_RECORD */

DROP TABLE IF EXISTS COM_COMPANY_CONTACTS_RECORD;

CREATE TABLE COM_COMPANY_CONTACTS_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT,
  COMPANY_ID int(10) DEFAULT NULL COMMENT '所属企业',
  LINK_MAN_NAME varchar(40) DEFAULT NULL COMMENT '联系人名称',
  WORK_TEL varchar(50) DEFAULT NULL COMMENT '办公固定电话',
  WORK_FAX varchar(50) DEFAULT NULL COMMENT '办公传真',
  MOBILE_TEL varchar(50) DEFAULT NULL COMMENT '移动电话',
  POSITION varchar(50) DEFAULT NULL COMMENT '职位',
  HOME_TEL varchar(50) DEFAULT NULL COMMENT '家庭电话',
  HOME_ADDRESS varchar(100) DEFAULT NULL COMMENT '家庭住址',
  EMAIL varchar(100) DEFAULT NULL COMMENT '联系人邮箱',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COMPANY_PROPERTY */

DROP TABLE IF EXISTS COM_COMPANY_PROPERTY;

CREATE TABLE COM_COMPANY_PROPERTY (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  COMPANY_ID int(10) DEFAULT NULL COMMENT '企业信息表ID',
  PROPERTY_ID int(10) DEFAULT NULL COMMENT '属性ID',
  PROPERTY_VALUE varchar(600) DEFAULT NULL,
  PROPERTY_STATUS int(2) DEFAULT NULL COMMENT '属性状态（1、在用，2、已过时）',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统',
  ACCOUNT_ID int(10) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COMPANY_RECORD */

DROP TABLE IF EXISTS COM_COMPANY_RECORD;

CREATE TABLE COM_COMPANY_RECORD (
  ID int(10) NOT NULL COMMENT '主键',
  COMPANY_NAME varchar(100) DEFAULT NULL COMMENT '企业名称',
  COMPANY_CODE varchar(50) DEFAULT NULL COMMENT '企业代码',
  COMPANY_SHORT_NAME varchar(50) DEFAULT NULL COMMENT '企业简称',
  COMPANY_NO varchar(50) DEFAULT NULL COMMENT '企业编号',
  COMPANY_BIZ_NO varchar(50) DEFAULT NULL COMMENT '企业营业证号',
  CUST_NAME varchar(200) DEFAULT NULL,
  CUST_TTL varchar(20) DEFAULT NULL,
  CUSTOM_NO varchar(40) DEFAULT NULL,
  CUST_COMNO varchar(50) DEFAULT NULL,
  ACCOUNT_ID int(10) DEFAULT NULL,
  CUST_CLAS varchar(20) DEFAULT NULL,
  CUST_RANC varchar(20) DEFAULT NULL,
  CUST_ENG varchar(150) DEFAULT NULL,
  CUST_ROOT varchar(20) DEFAULT NULL,
  CUST_AREA varchar(20) DEFAULT NULL,
  CUST_GILD varchar(20) DEFAULT NULL,
  COMSKIND varchar(20) DEFAULT NULL,
  CUST_MAN varchar(20) DEFAULT NULL,
  CUST_MANTEL varchar(40) DEFAULT NULL,
  CUST_ADD varchar(100) DEFAULT NULL,
  CUST_POST varchar(8) DEFAULT NULL,
  CUST_EN_ADD varchar(150) DEFAULT NULL,
  CUST_EN_POST varchar(50) DEFAULT NULL,
  CUST_TEL varchar(100) DEFAULT NULL,
  CUST_FAX varchar(50) DEFAULT NULL,
  CUST_MAIL varchar(50) DEFAULT NULL,
  CUST_WEB varchar(100) DEFAULT NULL,
  CUST_TAXNO varchar(50) DEFAULT NULL,
  CURR_CODE varchar(20) DEFAULT NULL,
  CUST_BANK varchar(100) DEFAULT NULL,
  CUST_BANKNO varchar(50) DEFAULT NULL,
  RECEIKIND varchar(20) DEFAULT NULL,
  PROMPTDAYS decimal(10,4) DEFAULT NULL,
  SETTLEKIND varchar(16) DEFAULT NULL,
  SETTLEDAYS decimal(10,4) DEFAULT NULL,
  CREDITRANC varchar(16) DEFAULT NULL,
  CREDITMAX decimal(18,4) DEFAULT NULL,
  STA_LONGITUDE decimal(11,8) DEFAULT NULL,
  STA_LATITUDE decimal(11,8) DEFAULT NULL,
  PREFIX_CODE varchar(8) DEFAULT NULL,
  CUSTOMS_CO varchar(5) DEFAULT NULL COMMENT '关区代码',
  SERVICE_SCOPE varchar(100) DEFAULT NULL COMMENT '服务范围',
  REGISTER_FUND int(10) DEFAULT NULL,
  REGISTER_FUND_CURR_CODE varchar(4) DEFAULT NULL COMMENT '注册资金币种',
  FOUNDED_YEARS datetime DEFAULT NULL COMMENT '成立年限',
  STAFF_NUM varchar(50) DEFAULT NULL,
  AREA_NUM decimal(12,2) DEFAULT NULL COMMENT '面积',
  MAIN_LINE_CAR_NUM int(6) DEFAULT NULL COMMENT '干线运输车辆数',
  SELF_OWNER_CAR_NUM int(6) DEFAULT NULL COMMENT '自有提货车辆数',
  ROAD_TRAN_PERMIT_NO varchar(50) DEFAULT NULL COMMENT '道路运输许可证号',
  ORG_CODE_LICENSE_NO varchar(50) DEFAULT '' COMMENT '组织结构代码证号',
  SERVICE_TYPE int(2) DEFAULT NULL COMMENT '服务类型',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COMPANY_STAFF */

DROP TABLE IF EXISTS COM_COMPANY_STAFF;

CREATE TABLE COM_COMPANY_STAFF (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  COMPANY_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '企业帐号ID',
  STAFF_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '员工帐号ID',
  STATUS int(2) DEFAULT NULL COMMENT '通用状态码',
  ROLE_TYPE int(2) DEFAULT NULL COMMENT '人员在企业中所属角色（1、企业管理员）',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '修改人帐号ID',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COMPANY_STAFF_RECORD */

DROP TABLE IF EXISTS COM_COMPANY_STAFF_RECORD;

CREATE TABLE COM_COMPANY_STAFF_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  COMPANY_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '企业帐号ID',
  STAFF_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '员工帐号ID',
  STATUS int(2) DEFAULT NULL COMMENT '通用状态码',
  ROLE_TYPE int(2) DEFAULT NULL COMMENT '人员在企业中所属角色（1、企业管理员）',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '修改人帐号ID',
  PRIMARY KEY (ID)
)   ;

/*Table structure for table COM_COUNTRY */

DROP TABLE IF EXISTS COM_COUNTRY;

CREATE TABLE COM_COUNTRY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  COUNTRY_CODE varchar(10) DEFAULT NULL COMMENT '国家代码',
  COUNTRY_NAME_EN varchar(100) DEFAULT NULL COMMENT '国家英文名称',
  COUNTRY_NAME_CH varchar(100) DEFAULT NULL COMMENT '国家中文名称',
  COUNTRY_TTL varchar(20) DEFAULT NULL COMMENT '国家简称',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_COUNTY */

DROP TABLE IF EXISTS COM_COUNTY;

CREATE TABLE COM_COUNTY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  AREA_NAME varchar(50) DEFAULT NULL,
  CITY_ID int(10) DEFAULT NULL,
  PIN_YIN varchar(50) DEFAULT NULL,
  PIN_YIN_CHAR varchar(50) DEFAULT NULL,
  IS_SHOW_WITH_CITY int(1) DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  SORT_NO int(5) DEFAULT NULL,
  PROVINCE_ID int(10) DEFAULT NULL,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_CREDIT_REPORT */

DROP TABLE IF EXISTS COM_CREDIT_REPORT;

CREATE TABLE COM_CREDIT_REPORT (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  CREDIT_NAME varchar(200) DEFAULT NULL COMMENT '征信对象名称（人员姓名或者企业名称）',
  CREDIT_OBJECT_TYPE int(2) DEFAULT NULL COMMENT '征信对象类型（1、人员，2、企业）',
  CERTIFICATE_NO varchar(100) DEFAULT NULL COMMENT '征信对象证件号',
  CERTIFICATE_TYPE int(10) DEFAULT NULL COMMENT '证件类型(字典表中数据，身份证，企业经营执照等等)',
  CREDIT_INFO_FROM int(2) DEFAULT NULL COMMENT '征信数据来源（1、人工录入，2、PSC中冻结帐号时录入，3、第三方系统）',
  CREDIT_STATUS int(2) DEFAULT NULL COMMENT '征信状态（1、有限冻结，2、永久冻结）',
  CREDIT_DESC varchar(500) DEFAULT NULL COMMENT '征信原因描述',
  FREEZE_START_TIME datetime DEFAULT NULL COMMENT '冻结起始时间',
  FREEZE_END_TIME datetime DEFAULT NULL COMMENT '冻结结束时间',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  CREATE_USER varchar(50) DEFAULT NULL COMMENT '创建人员',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_CURRENCY */

DROP TABLE IF EXISTS COM_CURRENCY;

CREATE TABLE COM_CURRENCY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  CURRENCY_CODE varchar(20) DEFAULT NULL,
  CURRENCY_EN varchar(20) DEFAULT NULL,
  CURRENCY_CH varchar(20) DEFAULT NULL,
  SORTID int(5) DEFAULT '0',
  ISUSE int(2) DEFAULT '1',
  INSURANCE_CODE varchar(10) DEFAULT NULL COMMENT '保险接口中币制代码',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_CUSTOM_ACCOUNT_ROLE */

DROP TABLE IF EXISTS COM_CUSTOM_ACCOUNT_ROLE;

CREATE TABLE COM_CUSTOM_ACCOUNT_ROLE (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '人员帐号ID',
  CUSTOM_ROLE_ID int(10) DEFAULT NULL COMMENT '自定义角色ID',
  AUTH_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '授权人员ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '授权时间',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_CUSTOM_ROLE */

DROP TABLE IF EXISTS COM_CUSTOM_ROLE;

CREATE TABLE COM_CUSTOM_ROLE (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  ROLE_NAME varchar(100) DEFAULT NULL COMMENT '角色名称',
  CREATE_USER int(10) DEFAULT NULL COMMENT '创建人帐号',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  BELONG_COMPANY_ACCOUNT_ID int(10) DEFAULT NULL COMMENT '归属企业帐号ID',
  ROLE_STATUS int(2) DEFAULT NULL COMMENT '状态',
  ROLE_DESC varchar(100) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8   COMMENT='企业管理员自定义角色';

/*Table structure for table COM_CUSTOM_ROLE_SYSTEM_REL */

DROP TABLE IF EXISTS COM_CUSTOM_ROLE_SYSTEM_REL;

CREATE TABLE COM_CUSTOM_ROLE_SYSTEM_REL (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  CUSTOM_ROLE_ID int(10) DEFAULT NULL COMMENT 'COM_CUSTOM_ROLE表的主键',
  SYS_ID int(10) DEFAULT NULL COMMENT 'COM_SYSTEM_INFO表主键',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  CREATE_USER int(10) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8   COMMENT='用户自定义角色与系统关联关系表';

/*Table structure for table COM_DEVICE_DETAIL_INFO */

DROP TABLE IF EXISTS COM_DEVICE_DETAIL_INFO;

CREATE TABLE COM_DEVICE_DETAIL_INFO (
  ID int(10) NOT NULL AUTO_INCREMENT,
  DEVICE_ID int(10) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  DETAIL_TYPE int(10) DEFAULT NULL COMMENT '明细设备类别，1是车厢类别，2是车架类别',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8  COMMENT='此表和设备表属于一对多的关系，一个设备对应多个明细';

/*Table structure for table COM_DEVICE_DETAIL_PROPERTY */

DROP TABLE IF EXISTS COM_DEVICE_DETAIL_PROPERTY;

CREATE TABLE COM_DEVICE_DETAIL_PROPERTY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  DETAIL_ID int(10) DEFAULT NULL COMMENT '设备明细表ID',
  PROPERTY_ID int(10) DEFAULT NULL COMMENT '属性表ID',
  PROPERTY_VALUE varchar(200) DEFAULT NULL COMMENT '属性值',
  PROPERTY_STATUS char(10) DEFAULT NULL COMMENT '属性状态（1、在用，2、已过时）',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_DEVICE_INFO */

DROP TABLE IF EXISTS COM_DEVICE_INFO;

CREATE TABLE COM_DEVICE_INFO (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  DEVICE_NAME varchar(200) DEFAULT NULL COMMENT '设备名称',
  DEVICE_CATEGORY int(10) DEFAULT NULL COMMENT '设备类别字典值（汽车，手机，电脑等等）',
  DEVICE_MODEL varchar(100) DEFAULT NULL COMMENT '型号',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_DEVICE_PROPERTY */

DROP TABLE IF EXISTS COM_DEVICE_PROPERTY;

CREATE TABLE COM_DEVICE_PROPERTY (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  DEVICE_ID int(10) DEFAULT NULL COMMENT '设备表ID',
  PROPERTY_ID int(10) DEFAULT NULL COMMENT '属性表ID',
  PROPERTY_VALUE varchar(200) DEFAULT NULL COMMENT '属性值',
  SYS_ID int(10) DEFAULT NULL,
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '创建的账号ID',
  PROPERTY_STATUS int(2) DEFAULT NULL COMMENT '属性状态',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_DICT */

DROP TABLE IF EXISTS COM_DICT;

CREATE TABLE COM_DICT (
  DICT_ID int(10) NOT NULL AUTO_INCREMENT COMMENT '字典ID',
  DICT_NAME varchar(100) DEFAULT NULL COMMENT '字典名称',
  DICT_CODE varchar(100) DEFAULT NULL COMMENT '字典代码（字母数字下划线）',
  DICT_DESC varchar(200) DEFAULT NULL COMMENT '字典描述',
  DICT_STATUS int(2) DEFAULT NULL COMMENT '字典状态',
  PRIMARY KEY (DICT_ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_DICT_VALUE */

DROP TABLE IF EXISTS COM_DICT_VALUE;

CREATE TABLE COM_DICT_VALUE (
  DICT_VALUE_ID int(10) NOT NULL AUTO_INCREMENT,
  DICT_VALUE varchar(100) DEFAULT NULL COMMENT '字典数值',
  DICT_VALUE_CODE varchar(50) DEFAULT NULL COMMENT '数值代码',
  DICT_VALUE_STATUS int(2) DEFAULT NULL COMMENT '状态',
  DICT_VALUE_SORT int(5) DEFAULT NULL COMMENT '排序号',
  DICT_ID int(10) DEFAULT NULL COMMENT '所属字典',
  DICT_VALUE_DESC varchar(100) DEFAULT NULL COMMENT '值说明',
  I18N_ID int(10) DEFAULT NULL COMMENT '国际化ID',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统ID',
  DICT_ALIAS varchar(100) DEFAULT NULL COMMENT '参数别名',
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (DICT_VALUE_ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_DRIVER_INFO */

DROP TABLE IF EXISTS COM_DRIVER_INFO;

CREATE TABLE COM_DRIVER_INFO (
  ID int(10) NOT NULL AUTO_INCREMENT,
  VEHICLE_ID int(10) DEFAULT NULL,
  DRIVER varchar(20) DEFAULT NULL,
  NATIVE_PLACE varchar(50) DEFAULT NULL,
  TELEPHONE varchar(20) DEFAULT NULL,
  BIRTHDAY datetime DEFAULT NULL,
  IDCARDNO varchar(30) DEFAULT NULL,
  DRIVING_CARD varchar(50) DEFAULT NULL,
  DRIVING_MODEL varchar(50) DEFAULT NULL,
  CATTINO varchar(50) DEFAULT NULL,
  DESC_NO int(2) DEFAULT '0',
  DRIVER_CUSTOMS_CODE varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_DRIVER_INFO_RECORD */

DROP TABLE IF EXISTS COM_DRIVER_INFO_RECORD;

CREATE TABLE COM_DRIVER_INFO_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT,
  VEHICLE_ID int(10) DEFAULT NULL,
  DRIVER varchar(20) DEFAULT NULL,
  NATIVE_PLACE varchar(50) DEFAULT NULL,
  TELEPHONE varchar(20) DEFAULT NULL,
  BIRTHDAY datetime DEFAULT NULL,
  IDCARDNO varchar(30) DEFAULT NULL,
  DRIVING_CARD varchar(50) DEFAULT NULL,
  DRIVING_MODEL varchar(50) DEFAULT NULL,
  CATTINO varchar(50) DEFAULT NULL,
  DESC_NO int(1) DEFAULT '0',
  DRIVER_CUSTOMS_CODE varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_INTERFACE_OBJECT */

DROP TABLE IF EXISTS COM_INTERFACE_OBJECT;

CREATE TABLE COM_INTERFACE_OBJECT (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  OBJ_PATH varchar(200) DEFAULT NULL COMMENT '对象package路径,唯一键',
  CLASS_NAME varchar(100) DEFAULT NULL COMMENT '类名称',
  CLASS_DESC varchar(300) DEFAULT NULL COMMENT '类描述',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_INTERFACE_OBJECT_PROPERTY */

DROP TABLE IF EXISTS COM_INTERFACE_OBJECT_PROPERTY;

CREATE TABLE COM_INTERFACE_OBJECT_PROPERTY (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  OBJ_ID int(10) DEFAULT NULL COMMENT '属性所属对象ID',
  PROPERTY_NAME varchar(20) DEFAULT NULL COMMENT '属性名称',
  PROPERTY_CLASS_PATH varchar(200) DEFAULT NULL COMMENT '属性类路径',
  PROPERTY_DATA_TYPE varchar(50) DEFAULT NULL COMMENT '属性数据类型（int,double,String等等）',
  PROPERTY_DESC varchar(200) DEFAULT NULL COMMENT '属性描述',
  CUSTOM_FLAG tinyint(1) DEFAULT NULL COMMENT '是否自定义属性',
  REQUIRED_FLAG tinyint(1) DEFAULT NULL COMMENT '是否必填（true必填，flase不必填）',
  NULL_FLAG tinyint(1) DEFAULT NULL COMMENT '是否允许为空（true允许，false不允许）',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_MODULE */

DROP TABLE IF EXISTS COM_MODULE;

CREATE TABLE COM_MODULE (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '模块ID',
  MODULE_NAME varchar(100) DEFAULT NULL COMMENT '模块名称',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统ID',
  P_MODULE_ID int(10) DEFAULT NULL COMMENT '父模块ID',
  MODULE_STATUS int(2) DEFAULT NULL COMMENT '模块状态',
  MODULE_CODE varchar(100) DEFAULT NULL COMMENT '模块代码(同一系统内，模块代码唯一)',
  MODULE_ICON varchar(100) DEFAULT NULL COMMENT '模块图标',
  MODULE_URL varchar(200) DEFAULT NULL COMMENT '模块请求CONTROLLER地址',
  MODULE_SORT int(4) DEFAULT NULL COMMENT '模块排列序号，升序排列',
  MODULE_LEVEL int(2) DEFAULT NULL COMMENT '模块级别',
  PRIMARY KEY (ID),
  KEY ID (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_OPERATE_TYPE */

DROP TABLE IF EXISTS COM_OPERATE_TYPE;

CREATE TABLE COM_OPERATE_TYPE (
  ID int(10) NOT NULL AUTO_INCREMENT,
  OPER_TYPE_NAME varchar(200) DEFAULT NULL COMMENT '操作类型名称',
  OPER_TYPE_CODE varchar(200) DEFAULT NULL COMMENT '操作类型代码',
  OPER_TYPE_VALUE int(10) DEFAULT NULL,
  OPER_TYPE_CATEGORY int(2) DEFAULT NULL COMMENT '操作类型类别(1:普通操作日志,2:商家发布信息日志)',
  OPER_TYPE_STATUS int(2) DEFAULT NULL COMMENT '操作类型状态',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统',
  MODULE_ID int(10) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_PROPERTY */

DROP TABLE IF EXISTS COM_PROPERTY;

CREATE TABLE COM_PROPERTY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  PROPERTY_NAME varchar(300) DEFAULT NULL COMMENT '属性名称',
  PROPERTY_CODE varchar(50) DEFAULT NULL COMMENT '属性代码',
  OBJECT_TYPE varchar(50) DEFAULT NULL COMMENT '对象类型（1、人员，2、企业）',
  PROPERTY_TYPE int(10) DEFAULT NULL COMMENT '属性类型，在字典表中定义一个属性类型字典，这个字段保存属性值',
  COMMON_FLAG int(1) DEFAULT NULL COMMENT '是否为某个系统的定制属性',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统的Id',
  PROPERTY_STATUS int(2) DEFAULT NULL COMMENT '系统标准状态定义',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_PROVINCE */

DROP TABLE IF EXISTS COM_PROVINCE;

CREATE TABLE COM_PROVINCE (
  ID int(10) NOT NULL AUTO_INCREMENT,
  PROVINCE_NAME varchar(50) DEFAULT NULL,
  SHORT_NAME varchar(20) DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  PROVINCE_PINYIN varchar(50) DEFAULT NULL,
  PROVINCE_PY varchar(20) DEFAULT NULL,
  COUNTRY_ID int(10) DEFAULT NULL,
  SORT_NO int(5) DEFAULT NULL,
  CITY_ID int(10) DEFAULT NULL COMMENT '城市ID，如果是直辖市，就保存城市ID',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_REGION */

DROP TABLE IF EXISTS COM_REGION;

CREATE TABLE COM_REGION (
  ID int(10) NOT NULL AUTO_INCREMENT,
  COUNTRY_ID int(10) DEFAULT NULL,
  PROVINCE_ID int(10) DEFAULT NULL,
  CITY_ID int(10) DEFAULT NULL,
  COUNTY_ID int(10) DEFAULT NULL,
  TOWN_ID int(10) DEFAULT NULL,
  REGION_TYPE int(2) DEFAULT NULL,
  STATUS int(2) DEFAULT NULL,
  REGION_NAME varchar(80) DEFAULT NULL,
  REGION_SHORT_NAME varchar(50) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
)  ;

/*Table structure for table COM_SERVICE_AUTH */

DROP TABLE IF EXISTS COM_SERVICE_AUTH;

CREATE TABLE COM_SERVICE_AUTH (
  ID int(10) NOT NULL AUTO_INCREMENT,
  SERVICE_ID int(10) DEFAULT NULL,
  SYS_ID int(10) DEFAULT NULL,
  AUTH_TYPE int(2) DEFAULT NULL COMMENT '1、授权系统才可以访问，2、用户名密码访问',
  AUTH_FLAG tinyint(1) DEFAULT NULL,
  PRIMARY KEY (ID)
) ;

/*Table structure for table COM_SERVICE_INFO */

DROP TABLE IF EXISTS COM_SERVICE_INFO;

CREATE TABLE COM_SERVICE_INFO (
  ID int(10) NOT NULL AUTO_INCREMENT,
  INTERFACE_CLASS varchar(200) DEFAULT NULL,
  IMPLEMENT_CLASS varchar(200) DEFAULT NULL,
  SERVICE_BEAN_ID varchar(100) DEFAULT NULL,
  SERVICE_NAME varchar(50) DEFAULT NULL COMMENT '服务名称，简述服务',
  SERVICE_METHOD varchar(100) DEFAULT NULL,
  SERVICE_STATUS int(2) DEFAULT NULL,
  SERVICE_TYPE int(2) DEFAULT NULL COMMENT '1、普通java类（dubbo）2、webservice 3、http',
  SERVICE_URL varchar(300) DEFAULT NULL COMMENT '服务调用地址',
  SERVICE_DESC varchar(400) DEFAULT NULL COMMENT '服务详细描述',
  REQ_TYPE varchar(100) DEFAULT NULL COMMENT '请求方式，对于http请求',
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_SERVICE_PARAM */

DROP TABLE IF EXISTS COM_SERVICE_PARAM;

CREATE TABLE COM_SERVICE_PARAM (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  SERVICE_ID int(10) DEFAULT NULL COMMENT 'COM_SERVICE_INFO表主键',
  PARAM_TYPE int(2) DEFAULT NULL COMMENT '参数类型，1、输入参数，2、输入输出参数，3、输出参数，4、返回结果',
  PARAM_SORT int(2) DEFAULT NULL COMMENT '标明是第几个参数',
  PARAM_NAME varchar(50) DEFAULT NULL COMMENT '参数名称，英文名称',
  PARAM_DESC varchar(200) DEFAULT NULL COMMENT '参数描述',
  PARAM_DATA_TYPE varchar(100) DEFAULT NULL COMMENT '参数数据类型（int,double等等）',
  PARAM_PATH varchar(200) DEFAULT NULL COMMENT '参数路径',
  CUSTOM_FLAG tinyint(1) DEFAULT NULL COMMENT '是否自定义参数',
  REQUIRED_FLAG tinyint(1) DEFAULT NULL COMMENT '是否必填（true必填，flase不必填）',
  NULL_FLAG tinyint(1) DEFAULT NULL COMMENT '是否允许为空（true允许，false不允许）',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_SYSTEM_INFO */

DROP TABLE IF EXISTS COM_SYSTEM_INFO;

CREATE TABLE COM_SYSTEM_INFO (
  SYS_ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  SYS_CODE varchar(30) DEFAULT NULL COMMENT '系统代码',
  SYS_FLAG varchar(200) DEFAULT NULL COMMENT '系统标识，用于识别系统，定期更换，可用于webservice请求验证标识',
  SYS_NAME varchar(100) DEFAULT NULL COMMENT '系统名称',
  SYS_DESC varchar(200) DEFAULT NULL COMMENT '系统描述',
  SYS_STATUS int(2) DEFAULT NULL COMMENT '系统状态',
  SYS_AUTH_USER varchar(50) DEFAULT NULL COMMENT '系统授权用户（用于webservice请求验证）',
  SYS_AUTH_PWD varchar(200) DEFAULT NULL COMMENT '授权用户密码（用于webservice验证）',
  SORT_NO int(4) DEFAULT NULL COMMENT '系统排序号',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  CREATE_USER varchar(50) DEFAULT NULL COMMENT '创建人',
  AUTH_LOGIN tinyint(1) DEFAULT NULL COMMENT 'true只有授权后才能登录，false不用授权也可以登录，默认false',
  SYS_URL varchar(200) DEFAULT NULL COMMENT '系统访问的URL',
  REG_FLAG tinyint(1) DEFAULT NULL COMMENT '是否注册备案',
  DEFAULT_ROLE_ID int(10) DEFAULT NULL COMMENT '默认授权角色ID',
  BELONG_PLATFORM int(2) DEFAULT NULL COMMENT '所属平台（1、物流开放平台，2、工作任务管理平台，3、嘀讯平台，4、通用账户）',
  PRIMARY KEY (SYS_ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_TOWN */

DROP TABLE IF EXISTS COM_TOWN;

CREATE TABLE COM_TOWN (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  TOWN_NAME varchar(50) DEFAULT NULL COMMENT '乡镇街道名称',
  SHORT_NAME varchar(50) DEFAULT NULL COMMENT '简称',
  COUNTY_ID int(10) DEFAULT NULL COMMENT '所属区县ID',
  STATUS int(2) DEFAULT NULL COMMENT '状态',
  LONGITUDE decimal(11,8) DEFAULT NULL COMMENT '经度',
  LATITUDE decimal(11,8) DEFAULT NULL COMMENT '纬度',
  SORT_NO int(5) DEFAULT NULL COMMENT '排序号',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_UNIT */

DROP TABLE IF EXISTS COM_UNIT;

CREATE TABLE COM_UNIT (
  ID int(10) NOT NULL AUTO_INCREMENT,
  UNIT_CODE varchar(20) DEFAULT NULL,
  UNIT_EN varchar(20) DEFAULT NULL,
  UNIT_CH varchar(20) DEFAULT NULL,
  FLAG int(2) DEFAULT NULL,
  UNIT_TYPE int(2) DEFAULT NULL,
  SORT_NO int(5) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  INSURANCE_CODE varchar(10) DEFAULT NULL COMMENT '保险接口单位代码',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8  ;

/*Table structure for table COM_USER */

DROP TABLE IF EXISTS COM_USER;

CREATE TABLE COM_USER (
  ID int(10) NOT NULL AUTO_INCREMENT,
  USER_CODE varchar(50) DEFAULT NULL,
  REAL_NAME varchar(50) DEFAULT NULL,
  SEX int(10) DEFAULT NULL COMMENT '字典表备案',
  IDENTITY_NO varchar(50) DEFAULT NULL,
  TELEPHONE varchar(20) DEFAULT NULL,
  COUNTRY_CODE varchar(10) DEFAULT NULL,
  BIRTHDAY datetime DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  FROM_SYS_ID int(10) DEFAULT NULL COMMENT '从哪个系统备案过来的',
  STATUS int(2) DEFAULT NULL COMMENT '1、可用，2、禁用，3、待审核',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_USER_PROPERTY */

DROP TABLE IF EXISTS COM_USER_PROPERTY;

CREATE TABLE COM_USER_PROPERTY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  USER_ID int(10) DEFAULT NULL COMMENT 'COM_USER表ID',
  PROPERTY_ID int(10) DEFAULT NULL COMMENT '属性表ID',
  PROPERTY_VALUE varchar(200) DEFAULT NULL COMMENT '属性值',
  PROPERTY_STATUS int(2) DEFAULT NULL COMMENT '属性状态（1、在用，2、已过时）',
  SYS_ID int(10) DEFAULT NULL COMMENT '所属系统',
  ACCOUNT_ID int(10) DEFAULT NULL COMMENT '从哪个账号备案过来的，COM_ACCOUNT表ID，从这个字段也能推出从哪个系统备案过来的数据',
  CREATE_TIME datetime DEFAULT NULL COMMENT '属性创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_USER_RECORD */

DROP TABLE IF EXISTS COM_USER_RECORD;

CREATE TABLE COM_USER_RECORD (
  ID int(10) NOT NULL,
  REAL_NAME varchar(50) DEFAULT NULL,
  SEX int(10) DEFAULT NULL COMMENT '字典表备案',
  IDENTITY_NO varchar(50) DEFAULT NULL,
  BIRTHDAY datetime DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  ADDRESS varchar(50) DEFAULT NULL COMMENT '家庭住址',
  ZIPCODE varchar(20) DEFAULT NULL COMMENT '邮编',
  ACCOUNT_ID int(10) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_VEHICLE_CARRIAGE */

DROP TABLE IF EXISTS COM_VEHICLE_CARRIAGE;

CREATE TABLE COM_VEHICLE_CARRIAGE (
  ID int(10) NOT NULL AUTO_INCREMENT,
  CARRIAGE_TYPE varchar(30) DEFAULT NULL COMMENT '集装箱类型代码COM_ALL_TYPE',
  CARRIAGE_NO varchar(50) DEFAULT NULL COMMENT '集装箱编号',
  CARRIAGE_LENGTH int(6) DEFAULT NULL COMMENT '集装箱长，单位毫米',
  CARRIAGE_WIDTH int(6) DEFAULT NULL COMMENT '集装箱宽，单位毫米',
  CARRIAGE_HEIGHT int(6) DEFAULT NULL COMMENT '集装箱高，单位毫米',
  CARRIAGE_WEIGHT int(6) DEFAULT NULL COMMENT '集装自重，单位千克',
  EMPTY_WEIGHT_FLAG varchar(30) DEFAULT NULL COMMENT '空重标识COM_ALL_TYPE',
  SOURCE_CODE varchar(30) DEFAULT NULL COMMENT '来源代码,字典，COM_ALL_TYPE',
  VEHICLE_ID int(10) DEFAULT NULL COMMENT '车辆信息表ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_VEHICLE_CARRIAGE_RECORD */

DROP TABLE IF EXISTS COM_VEHICLE_CARRIAGE_RECORD;

CREATE TABLE COM_VEHICLE_CARRIAGE_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT,
  CARRIAGE_TYPE varchar(30) DEFAULT NULL COMMENT '集装箱类型代码COM_ALL_TYPE',
  CARRIAGE_NO varchar(50) DEFAULT NULL COMMENT '集装箱编号',
  CARRIAGE_LENGTH int(6) DEFAULT NULL COMMENT '集装箱长，单位毫米',
  CARRIAGE_WIDTH int(6) DEFAULT NULL COMMENT '集装箱宽，单位毫米',
  CARRIAGE_HEIGHT int(6) DEFAULT NULL COMMENT '集装箱高，单位毫米',
  CARRIAGE_WEIGHT int(6) DEFAULT NULL COMMENT '集装自重，单位千克',
  EMPTY_WEIGHT_FLAG varchar(30) DEFAULT NULL COMMENT '空重标识COM_ALL_TYPE',
  SOURCE_CODE varchar(30) DEFAULT NULL COMMENT '来源代码,字典，COM_ALL_TYPE',
  VEHICLE_ID int(10) DEFAULT NULL COMMENT '车辆信息表ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_VEHICLE_INFO */

DROP TABLE IF EXISTS COM_VEHICLE_INFO;

CREATE TABLE COM_VEHICLE_INFO (
  ID int(10) NOT NULL AUTO_INCREMENT,
  TRUCKCODE varchar(20) DEFAULT NULL,
  TRUCKTYPE varchar(20) DEFAULT NULL,
  TYPEDESC varchar(50) DEFAULT NULL,
  TRUCKMODELCODE varchar(50) DEFAULT NULL,
  TRANSPORTTYPE varchar(10) DEFAULT NULL,
  ENGINECODE varchar(50) DEFAULT NULL,
  OWNERS varchar(20) DEFAULT NULL,
  TRUCKCODEII varchar(20) DEFAULT NULL,
  COMPANYCODE varchar(8) DEFAULT NULL,
  ICCARDNO varchar(50) DEFAULT NULL,
  LENGTH decimal(7,2) DEFAULT NULL,
  WIDTH decimal(7,2) DEFAULT NULL,
  HEIGHT decimal(7,2) DEFAULT NULL,
  BOXLENGTH decimal(7,2) DEFAULT NULL,
  BOXWIDTH decimal(7,2) DEFAULT NULL,
  BOXHEIGHT decimal(7,2) DEFAULT NULL,
  TRANSCODE varchar(50) DEFAULT NULL,
  BRACKETCODE varchar(20) DEFAULT NULL,
  BRACKETTYPE varchar(50) DEFAULT NULL,
  BRACKETDATE datetime DEFAULT NULL,
  BTREGISTERCODE varchar(50) DEFAULT NULL,
  BTTAXCODE varchar(50) DEFAULT NULL,
  LOCKED tinyint(1) DEFAULT NULL,
  VEHICLEDATE datetime DEFAULT NULL,
  BTBOXCODE varchar(50) DEFAULT NULL,
  REMARK varchar(50) DEFAULT NULL,
  TRUCKBU varchar(50) DEFAULT NULL,
  TRUCKCARBU varchar(50) DEFAULT NULL,
  HASGPS tinyint(1) DEFAULT NULL,
  MAX_WEIGHT decimal(7,2) DEFAULT NULL,
  VEHICLE_TYPE varchar(30) DEFAULT NULL COMMENT '平板车 ',
  COMPANY_ID int(10) DEFAULT NULL,
  ACCOUNT_ID int(10) DEFAULT NULL,
  VIN varchar(50) DEFAULT NULL,
  HSCODE varchar(10) DEFAULT NULL,
  ARTICULATED_NO varchar(50) DEFAULT NULL,
  WEIGHT decimal(7,2) DEFAULT NULL COMMENT '车辆自重',
  DGPSW varchar(20) DEFAULT NULL COMMENT '东莞密码',
  QUICKQP varchar(20) DEFAULT NULL COMMENT '快速跨境',
  PSWONOFF varchar(20) DEFAULT NULL COMMENT '密码开关',
  TRUCK_CUSTOMS_CODE varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_VEHICLE_INFO_RECORD */

DROP TABLE IF EXISTS COM_VEHICLE_INFO_RECORD;

CREATE TABLE COM_VEHICLE_INFO_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT,
  TRUCKCODE varchar(20) DEFAULT NULL,
  TRUCKTYPE varchar(20) DEFAULT NULL,
  TYPEDESC varchar(50) DEFAULT NULL,
  TRUCKMODELCODE varchar(50) DEFAULT NULL,
  TRANSPORTTYPE varchar(10) DEFAULT NULL,
  ENGINECODE varchar(50) DEFAULT NULL,
  OWNERS varchar(20) DEFAULT NULL,
  TRUCKCODEII varchar(20) DEFAULT NULL,
  COMPANYCODE varchar(8) DEFAULT NULL,
  ICCARDNO varchar(50) DEFAULT NULL,
  LENGTH decimal(18,2) DEFAULT NULL,
  WIDTH decimal(18,2) DEFAULT NULL,
  HEIGHT decimal(18,2) DEFAULT NULL,
  BOXLENGTH decimal(18,2) DEFAULT NULL,
  BOXWIDTH decimal(18,2) DEFAULT NULL,
  BOXHEIGHT decimal(18,2) DEFAULT NULL,
  TRANSCODE varchar(50) DEFAULT NULL,
  BRACKETCODE varchar(20) DEFAULT NULL,
  BRACKETTYPE varchar(50) DEFAULT NULL,
  BRACKETDATE datetime DEFAULT NULL,
  BTREGISTERCODE varchar(50) DEFAULT NULL,
  BTTAXCODE varchar(50) DEFAULT NULL,
  LOCKED tinyint(1) DEFAULT NULL,
  VEHICLEDATE datetime DEFAULT NULL,
  BTBOXCODE varchar(50) DEFAULT NULL,
  REMARK varchar(50) DEFAULT NULL,
  TRUCKBU varchar(50) DEFAULT NULL,
  TRUCKCARBU varchar(50) DEFAULT NULL,
  HASGPS tinyint(1) DEFAULT NULL,
  MAX_WEIGHT decimal(18,2) DEFAULT NULL,
  VEHICLE_TYPE varchar(30) DEFAULT NULL COMMENT '平板车 ',
  COMPANY_ID int(10) DEFAULT NULL,
  ACCOUNT_ID int(10) DEFAULT NULL,
  VIN varchar(50) DEFAULT NULL,
  HSCODE varchar(10) DEFAULT NULL,
  ARTICULATED_NO varchar(50) DEFAULT NULL,
  WEIGHT decimal(18,2) DEFAULT NULL COMMENT '车辆自重',
  DGPSW varchar(20) DEFAULT NULL COMMENT '东莞密码',
  QUICKQP varchar(20) DEFAULT NULL COMMENT '快速跨境',
  PSWONOFF varchar(20) DEFAULT NULL COMMENT '密码开关',
  TRUCK_CUSTOMS_CODE varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_VEHICLE_TRAY */

DROP TABLE IF EXISTS COM_VEHICLE_TRAY;

CREATE TABLE COM_VEHICLE_TRAY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  TRAY_NO varchar(50) DEFAULT NULL COMMENT '托架编号',
  TRAY_TYPE_CODE varchar(30) DEFAULT NULL COMMENT '托架类型代码COM_ALL_TYPE',
  TRAY_WEIGHT int(6) DEFAULT NULL COMMENT '托架自重',
  VEHICLE_ID int(10) DEFAULT NULL COMMENT '车辆ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table COM_VEHICLE_TRAY_RECORD */

DROP TABLE IF EXISTS COM_VEHICLE_TRAY_RECORD;

CREATE TABLE COM_VEHICLE_TRAY_RECORD (
  ID int(10) NOT NULL AUTO_INCREMENT,
  TRAY_NO varchar(50) DEFAULT NULL COMMENT '托架编号',
  TRAY_TYPE_CODE varchar(30) DEFAULT NULL COMMENT '托架类型代码COM_ALL_TYPE',
  TRAY_WEIGHT int(6) DEFAULT NULL COMMENT '托架自重',
  VEHICLE_ID int(10) DEFAULT NULL COMMENT '车辆ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table QRTZ_BLOB_TRIGGERS */

DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;

CREATE TABLE QRTZ_BLOB_TRIGGERS (
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  BLOB_DATA blob,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  KEY SCHED_NAME (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  CONSTRAINT QRTZ_BLOB_TRIGGERS_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
)  DEFAULT CHARSET=utf8;

/*Table structure for table QRTZ_CALENDARS */

DROP TABLE IF EXISTS QRTZ_CALENDARS;

CREATE TABLE QRTZ_CALENDARS (
  SCHED_NAME varchar(120) NOT NULL,
  CALENDAR_NAME varchar(200) NOT NULL,
  CALENDAR blob NOT NULL,
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table QRTZ_CRON_TRIGGERS */

DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;

DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;
DROP TABLE IF EXISTS QRTZ_LOCKS;
DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_JOB_DETAILS;
DROP TABLE IF EXISTS QRTZ_CALENDARS;


CREATE TABLE QRTZ_JOB_DETAILS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  JOB_NAME  VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  JOB_CLASS_NAME   VARCHAR(250) NOT NULL,
  IS_DURABLE VARCHAR(1) NOT NULL,
  IS_NONCONCURRENT VARCHAR(1) NOT NULL,
  IS_UPDATE_DATA VARCHAR(1) NOT NULL,
  REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
)  DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  JOB_NAME  VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  NEXT_FIRE_TIME BIGINT(13) NULL,
  PREV_FIRE_TIME BIGINT(13) NULL,
  PRIORITY INTEGER NULL,
  TRIGGER_STATE VARCHAR(16) NOT NULL,
  TRIGGER_TYPE VARCHAR(8) NOT NULL,
  START_TIME BIGINT(13) NOT NULL,
  END_TIME BIGINT(13) NULL,
  CALENDAR_NAME VARCHAR(200) NULL,
  MISFIRE_INSTR SMALLINT(2) NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
  REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_SIMPLE_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  REPEAT_COUNT BIGINT(7) NOT NULL,
  REPEAT_INTERVAL BIGINT(12) NOT NULL,
  TIMES_TRIGGERED BIGINT(10) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_CRON_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  CRON_EXPRESSION VARCHAR(200) NOT NULL,
  TIME_ZONE_ID VARCHAR(80),
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_SIMPROP_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  STR_PROP_1 VARCHAR(512) NULL,
  STR_PROP_2 VARCHAR(512) NULL,
  STR_PROP_3 VARCHAR(512) NULL,
  INT_PROP_1 INT NULL,
  INT_PROP_2 INT NULL,
  LONG_PROP_1 BIGINT NULL,
  LONG_PROP_2 BIGINT NULL,
  DEC_PROP_1 NUMERIC(13,4) NULL,
  DEC_PROP_2 NUMERIC(13,4) NULL,
  BOOL_PROP_1 VARCHAR(1) NULL,
  BOOL_PROP_2 VARCHAR(1) NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_BLOB_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  BLOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_CALENDARS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  CALENDAR_NAME  VARCHAR(200) NOT NULL,
  CALENDAR BLOB NOT NULL,
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_GROUP  VARCHAR(200) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_FIRED_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  ENTRY_ID VARCHAR(95) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  FIRED_TIME BIGINT(13) NOT NULL,
  SCHED_TIME BIGINT(13) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE VARCHAR(16) NOT NULL,
  JOB_NAME VARCHAR(200) NULL,
  JOB_GROUP VARCHAR(200) NULL,
  IS_NONCONCURRENT VARCHAR(1) NULL,
  REQUESTS_RECOVERY VARCHAR(1) NULL,
  PRIMARY KEY (SCHED_NAME,ENTRY_ID)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_SCHEDULER_STATE
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
  CHECKIN_INTERVAL BIGINT(13) NOT NULL,
  PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
) DEFAULT CHARSET=utf8 ;

CREATE TABLE QRTZ_LOCKS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  LOCK_NAME  VARCHAR(40) NOT NULL,
  PRIMARY KEY (SCHED_NAME,LOCK_NAME)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_AUTHORITY */

DROP TABLE IF EXISTS SYS_AUTHORITY;

CREATE TABLE SYS_AUTHORITY (
  ID int(10) NOT NULL AUTO_INCREMENT,
  AUTH_NAME varchar(50) DEFAULT NULL COMMENT '权限名称',
  AUTH_URL varchar(50) DEFAULT NULL COMMENT '权限URL',
  AUTH_STATUS int(2) DEFAULT NULL COMMENT '权限状态（采用系统共用的状态标准）',
  AUTH_CODE varchar(100) DEFAULT NULL,
  MENU_ID int(10) DEFAULT NULL COMMENT '必填',
  CREATE_TIME datetime DEFAULT NULL,
  AUTH_DESC varchar(100) DEFAULT NULL,
  CONTROLLER_PATH varchar(200) DEFAULT NULL,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_DEPARTMENT */

DROP TABLE IF EXISTS SYS_DEPARTMENT;

CREATE TABLE SYS_DEPARTMENT (
  ID int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  DEPT_NAME varchar(100) DEFAULT NULL COMMENT '部门名称',
  DEPT_CODE varchar(100) DEFAULT NULL COMMENT '部门编号',
  DEPT_STATUS int(2) DEFAULT NULL COMMENT '部门状态',
  DEPT_SORT int(4) DEFAULT NULL COMMENT '部门排序号',
  P_DEPT_ID int(10) DEFAULT NULL COMMENT '父部门ID',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
)   DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_EXCEPTION_LOG */

DROP TABLE IF EXISTS SYS_EXCEPTION_LOG;

CREATE TABLE SYS_EXCEPTION_LOG (
  ID int(10) NOT NULL AUTO_INCREMENT,
  EX_CLASS varchar(200) DEFAULT NULL COMMENT '异常类信息',
  EX_MESSAGE text COMMENT '异常信息',
  EX_PARAM text COMMENT '异常信息参数',
  EX_CAUSE text COMMENT '异常引起原因',
  EX_USER varchar(20) DEFAULT NULL COMMENT '异常发生时登录用户',
  CUSTOM_EX_NO int(5) DEFAULT NULL COMMENT '自定义异常编号',
  CREATE_TIME datetime DEFAULT NULL COMMENT '异常发生时间',
  EX_STATUS int(2) DEFAULT NULL COMMENT '异常状态(1、未解决，2、已解决，3、未知异常)',
  EX_DESC varchar(200) DEFAULT NULL COMMENT '异常原因描述（开发人员填写异常原因）',
  SOLVE_TIME datetime DEFAULT NULL COMMENT '异常问题解决时间',
  SOLVE_USER int(10) DEFAULT NULL COMMENT '解决人员',
  EX_LEVEL int(10) DEFAULT NULL COMMENT '字典表（一般，紧急，特急）',
  FROM_SYS varchar(20) DEFAULT NULL COMMENT '所属系统',
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_MENU */

DROP TABLE IF EXISTS SYS_MENU;

CREATE TABLE SYS_MENU (
  MENU_ID int(10) NOT NULL AUTO_INCREMENT COMMENT '菜单ID',
  MENU_CODE varchar(50) DEFAULT NULL COMMENT '字母数字下划线',
  MENU_NAME varchar(20) DEFAULT NULL COMMENT '菜单名称',
  MENU_URL varchar(100) DEFAULT NULL COMMENT '菜单URL',
  MENU_ICON varchar(100) DEFAULT NULL COMMENT '菜单图标URL',
  MENU_STATUS int(2) DEFAULT NULL COMMENT '采用系统公用的状态标准，只有超级管理员角色的人员才能删除',
  P_MENU_ID int(10) DEFAULT NULL COMMENT '根菜单ID为（-1）',
  MENU_SORT int(4) DEFAULT NULL COMMENT '同一个父菜单下的排序号',
  MENU_LEVEL int(4) DEFAULT NULL COMMENT '一级、二级、三级等等',
  MENU_DESC varchar(200) DEFAULT NULL,
  PRIMARY KEY (MENU_ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_PARAMETER */

DROP TABLE IF EXISTS SYS_PARAMETER;

CREATE TABLE SYS_PARAMETER (
  PARAM_ID int(10) NOT NULL AUTO_INCREMENT COMMENT '参数ID',
  PARAM_NAME varchar(100) NOT NULL COMMENT '参数名称',
  PARAM_CODE varchar(100) DEFAULT NULL COMMENT '参数编码',
  PARAM_TYPE int(2) DEFAULT NULL COMMENT '参数类型(1、字符串，2、整形，3、浮点型，4、json字符串)',
  PARAM_OBJECT varchar(200) DEFAULT NULL COMMENT '针对参数类型为JSON字符串，必须提供映射的对象类路径',
  PARAM_STATUS int(2) DEFAULT NULL COMMENT '参数状态',
  PARAM_VALUE varchar(500) DEFAULT NULL COMMENT '参数值',
  PARAM_DEFAULT_VALUE varchar(500) DEFAULT NULL COMMENT '参数默认值',
  PARAM_DESC varchar(200) DEFAULT NULL COMMENT '参数描述',
  PRIMARY KEY (PARAM_ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_ROLE */

DROP TABLE IF EXISTS SYS_ROLE;

CREATE TABLE SYS_ROLE (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ROLE_NAME varchar(100) DEFAULT NULL,
  ROLE_CODE varchar(100) DEFAULT NULL COMMENT '字母数字下划线组成',
  ROLE_LEVEL int(2) DEFAULT NULL COMMENT '角色级别',
  ROLE_STATUS int(2) DEFAULT NULL COMMENT '角色状态（1、可用、2、禁用）',
  ROLE_DESC varchar(100) DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8  COMMENT='系统默认有一个超级管理员角色，拥有所有权限';

/*Table structure for table SYS_ROLE_AUTHORITY_REL */

DROP TABLE IF EXISTS SYS_ROLE_AUTHORITY_REL;

CREATE TABLE SYS_ROLE_AUTHORITY_REL (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ROLE_ID int(10) DEFAULT NULL,
  AUTH_ID int(10) DEFAULT NULL,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_ROLE_MENU_REL */

DROP TABLE IF EXISTS SYS_ROLE_MENU_REL;

CREATE TABLE SYS_ROLE_MENU_REL (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ROLE_ID int(10) DEFAULT NULL,
  MENU_ID int(10) DEFAULT NULL,
  PRIMARY KEY (ID)
)  AUTO_INCREMENT=12 DEFAULT CHARSET=utf8  COMMENT='此表保存角色和菜单的关联关系，当给角色设置了子菜单的关联关系后，默认也要配置父菜单的关联关系';

/*Table structure for table SYS_ROLE_USER_REL */

DROP TABLE IF EXISTS SYS_ROLE_USER_REL;

CREATE TABLE SYS_ROLE_USER_REL (
  ID int(10) NOT NULL AUTO_INCREMENT,
  ROLE_ID int(10) DEFAULT NULL,
  USER_ID int(10) DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;

/*Table structure for table SYS_USER */

DROP TABLE IF EXISTS SYS_USER;

CREATE TABLE SYS_USER (
  ID int(10) NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(50) DEFAULT NULL,
  USER_ACCOUNT varchar(50) DEFAULT NULL,
  USER_PASSWORD varchar(200) DEFAULT NULL,
  DEPT_ID int(10) DEFAULT NULL,
  STATUS int(2) DEFAULT NULL COMMENT '状态采用系统共用的状态标准',
  CREATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 ;



